### ISSUE TITLE
CRAM reference

### ISSUE THREAD

**Issue by hlenghi** [samtools/htslib#1015]
Hello, I'm making some test converting my BAM files into CRAM. I'm using this command:

`samtools view -O CRAM -T reference.fasta -o myOutFile.cram myFile.bam`

Now I'm trying to make some analysis using directly htslib (version 1.9, that's what we have installed in our cluster). However, when calling

`sam_read1(...)`

I receive an error like:

`[W::find_file_url] Failed to open reference "https://www.ebi.ac.uk/ena/cram/md5/28d8562f2f99c047d792346835b20031": Protocol not supported`

even if my reference is local: why?
Furthermore, since our cluster is not connected with the internet, is it possible to manually set (and/or overwrite) any reference URL to a local file path without receiving errors like this? 
Thanks

HL.

**Comment by jkbonfield** [comment]
"Protocol not supported" means it doesn't have https access.

Most likely the build of htslib and samtools you have didn't use the configure script, which means it didn't get built with libcurl.  You'll need to recompile to get https support.

However you should also be able to use the `--reference reference.fasta` option to all commands to specify the reference and/or set the `REF_PATH` environment variable to a local directory containing all the references indexed by their MD5sums.  This is what we do locally.  The ENVIRONMENT VARIABLES section of the samtools.1 man page gives information on how to do this, specifically with regard to running the `misc/seq_cache_populate.pl` script to populate the reference path.

**Comment by hlenghi** [comment]
thanks @jkbonfield 

I have not any internet connection on the cluster (it's isolated for security reasons). Furthermore, I haven't uploaded my reference on the www.ebi.ac.uk server. I have not libcurl available. 

Reply to your edit: yes I specified the absolute path on my original command. However, I'm getting the error message. I know that this is not a great solution for data sharing, but we have our internal pipeline and generally speaking, data we have could not be shared. 

Is there any way to overwrite the path using htslib API (I mean, without using samtools, just htlisb APIs)? so will be much cleaner than setting a system variable?
thanks once again

HL.

**Comment by jkbonfield** [comment]
There are htslib APIs for setting the reference file to be used (`hts_set_fai_filename`) but this is what is already called in samtools when you specify `--reference`, so if you feel it is cleaner than modifying the environment then modify the command line arguments.

IMO cleanest is to use REF_PATH and `misc/seq_cache_populate.pl` script.  For example locally we have something like this:

```
export REF_PATH=/nfs/references/cram_cache/%2s/%2s/%s
```

Which then takes the M5 SQ entry and splits it into 2-char/2-char/remaining-chars as the file to load.  You could also run a local reference server instead of relying on an external one.  We use a similar mechanism here, although I can't find where our sample server resides.  I thought it was in samtools or htslib, but apparently not.  Anyway - a directory of M5s is easiest by far.

**Comment by bw2** [comment]
For anyone else that runs into this issue, the following worked for me:

```
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai 
wget https://storage.googleapis.com/gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.ref_cache.tar.gz

tar xzf Homo_sapiens_assembly38.ref_cache.tar.gz
export REF_PATH="$(pwd)/ref/cache/%2s/%2s/%s:http://www.ebi.ac.uk/ena/cram/md5/%s"
export REF_CACHE="$(pwd)/ref/cache/%2s/%2s/%s"

...

{command that was generating the '[W::find_file_url] Failed to open reference..' error}
```
