### ISSUE TITLE
extract variants of chrX from vcf 

### ISSUE THREAD

**Issue by yiqiangz318** [samtools/htslib#1036]
Hello, I was trying to use tabix to extract variants in some genomic regions from the 1000 genomes vcfs. Everything works perfectly except variants from chromosome X are not outputted.

1,
ls ALL.chr*.gz |sort -V  > file

2,
for a in `ls ALL.chr*.gz`; do bcftools index $a; done

3,
bcftools concat -f file -o 1kg38.vcf --threads 10

4,
sort bed -k1V -k2n > extract.bed

The content of extract.bed looks like:
1       59814786        59876370        ENSG00000134709 +
2       218264123       218270257       ENSG00000127837 -
3       10285675        10292947        ENSG00000157017 -
11      118657316       118679690       ENSG00000118094 -
15      34229996        34338060        ENSG00000140199 -
17      63477061        63498380        ENSG00000159640 +
19      18434388        18438301        ENSG00000105655 -
X       15627318        15675012        ENSG00000147003 -
X       30653359        30731456        ENSG00000198814 +

5,
bgzip 1kg38.vcf -@ 10

6,
tabix -p vcf 1kg38.vcf.gz

7,
tabix -h -R extract.bed 1kg38.vcf.gz > extract.vcf

So, could you advice how could I extract the variants of chrX from vcf, efficiently and correctly?

**Comment by jkbonfield** [comment]
I'm not sure what 1kg38 is, but if is it really aligned against GRC h38?  If so it uses chrX instead of "X" (although the same applies for chr1 vs 1).

**Comment by yiqiangz318** [comment]
1kg38 is the output of "bcftools concat". It is a multiple chromosome vcf file created from 23 single chromosome vcfs  downloaded from http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL/

It is X not chrX, and 1 not chr1.

**Comment by yiqiangz318** [comment]
Hi, I probably figure it out. It is not the problem of tabix, but the problem of the 1000G vcf records. There is a huge gap in the chrX vcf, the coordinate jumps from 2781457 to 155703812, leaving no info in the middle. 
 
Sorry about that.
