### ISSUE TITLE
Embedded reference issues?

### ISSUE THREAD

**Issue by jkbonfield** [samtools/htslib#1038]
_Originally posted by @pauldwolfe in https://github.com/samtools/htslib/pull/514#issuecomment-594128762_

> Thanks for quick reply. We have a cohort containing about 10k (human) BAMs and we're compressing them all to CRAM. Our process has a post-compression validation step which decompresses back to BAM then compares fidelity with the original BAM to assert the compression was lossless.

> Our compression uses the HG37 ref genome, and embeds it:
`samtools view -h -O cram,embed_ref=1 -T [ref genome]
-o [output file] -@ $(nproc) [input file]`

> Our decompression attempts to use the embedded genome (no supplied reference):
`samtools view -O bam -o [output BAM] -@ $(nproc) [input CRAM]`

> We've seen this failure in about 1% of our CRAMs so far. I've been digging a bit more today and actually it seems to be undeterministic (ie I've seen the same BAM fail and pass the validation)

> Could definitely be this is a problem in the compression operation itself, and this error is exposing the corruption. Just trying to figure out the root cause.

> Thanks for any additional insight.

**Comment by jkbonfield** [comment]
I suspect this is something to do with embedded references and a multi-threading bug.

It certainly *should* work, but not many people tend to embed their references so it's quite likely this is a less well tested part of the code.  I will investigate.

Meanwhile it would be helpful if you could do a few tests at your end too.
- Do you still see this issue if you don't use `embed_ref=1`?
- Do you still see this issue if you don't use `-@ $(nproc)`?

**Comment by pauldwolfe** [comment]
Thanks for opening the issue.

Established yesterday that the issue is indeterministic, so can't be 100% certain based on a test of a single BAM. That said, I have tested single-threaded and with embedded reference disabled with one of the BAMs which had the original issue and confirm I was able to encode/decode without issues.

I could redo a large batch of say 500 or 1000 as a better test, but as we use cloud infrastructure for this that would carry some expense. If you really cannot progress without this test please let me know and I'll do it, I guess it'll only cost a couple hundred bucks (also not sure exactly what performance impact will be without multi-threading).

**Comment by jkbonfield** [comment]
So far I've drawn a blank, but if it's tricky at your end then I'll keep  bashing away here to see if I can trigger it.  I've been running it under gcc's thread-sanitizer, but I could try valgrind helgrind or drd too, as well as just thrashing it.

In order to try and replicate things, what sort of depth are your samples? What read technologies & read lengths?  What's the typically `$nproc` you're using?  Which version of samtools are you running? (`samtools --version` will tell you.)

Also given the error you report is part of `cram_decode.c` I assume once you get this error that every time you attempt to decode it you'll see a repeat of the same error rather than just 1% of the time?  That would be useful to know as it informs me whether it's an encoder bug (seems more likely somehow) or a decoder one.

**Comment by pauldwolfe** [comment]
Thanks for the support, realize this must be quite tricky without an example to work with.

To your questions:
- Seen on both 30x and 90x depth
- Believe these are Illumina HiSeqX
- 150 read length, paired end
- 6 cores
- samtools 1.9
- Indeed we get it every time we attempt to decode. Feels like its an issue that occurs in encoding, exposed by decoding.

I do have an example I can fairly reliably reproduce (while its not completely deterministic, certain samples seem to be far more likely to hit it). While I can't share it due to privacy, I can definitely try things out and feed back to you.

**Comment by pauldwolfe** [comment]
Update: I was able to reproduce the problem today **without** multi-threading enabled on the encoding, although I did have `-@ 6` enabled on the decoding. 

Trying single threaded decode not to rule out a concurrency bug in decode.

**Comment by pauldwolfe** [comment]
Update #2: Single threaded decode fails as well. So looks to not be concurrency related, but in the encode.

**Comment by jkbonfield** [comment]
OK that is interesting (and easier to fix!).  It also explains why my trials using gcc's thread-sanitizer have so far thrown up nothing.  You're right it sounds like it's an encoder bug.  Thanks for the extra diagnosis.

I find it bizarre then that it is nondeterministic.  Have you found a file that it occurs deterministically on, or at least commonly on?  If so that helps hugely.  It'd also help to know if this occurs with 1.10 as there were a _lot_ of changes between 1.9 and 1.10.

Also as you now have a file that is failing, maybe we need better diagnostics to say precisely which container / slice is at fault.  I'm thinking maybe just knowing some of the meta-data for this container may help.  [io_lib](https://github.com/jkbonfield/io_lib/) has a "cram_dump" tool which can be very useful here, but only if we know which offset it's at.

We ought to be able to work out which slice it is, and hence look at the data and `cram_dump` output at the offending region, by changing the error line from

```
                hts_log_error("Embedded reference is too small");
```

to

```
                hts_log_error("Embedded reference is too small for slice at ref %d pos %ld-%ld", ref_id, (long)s->ref_start, (long)s->ref_end);
```

As far as changes between 1.9 and 1.10 go, there were bug fixes to embedded references when combined with multiple slices per container, but it doesn't look like you're doing that (it defaults to 1).  I couldn't see anything else obviously related.

**Comment by pauldwolfe** [comment]
I'm also now doubting whether the "non-determinism" was just a mistake on my part. I'm going to repeat my experiment now to see if I can get a sample to fail then pass. This takes some time so will update later today.

In the meantime I will try samtools 1.10. 

To finding the slice, could you supply a build with that logging change? Also fine to wait on that until we've confirmed determinism and tried new samtools.

**Comment by jkbonfield** [comment]
Thanks for the continued research.

I've updated this and several other error messages and made a PR to htslib: https://github.com/samtools/htslib/pull/1042  (aka https://github.com/jkbonfield/htslib/tree/improved_cram_err)

**Comment by pauldwolfe** [comment]
Found another interesting tidbit. While trying to establish determinism I noticed the decoded BAM failed when it was about 63GB big... which is strange as the original BAM was only 61GB.

I'll try to build your PR and run it now

**Comment by pauldwolfe** [comment]
What's the easiest way to get a build of samtools with your htslib change? (Sorry I'm a Java guy!)

**Comment by pauldwolfe** [comment]
Actually think I figured it out, I copied your source into a samtools 1.10 release tree (has the source) in the htslib-1.10 directory and built

**Comment by pauldwolfe** [comment]
Also can confirm its definitely deterministic. The observation from earlier was due to some very similarly named samples getting mixed up.

**Comment by pauldwolfe** [comment]
After all that it seems that samtools 1.10 fixes the issue. I can confirm that the issue was on encode, as only encoding with the new samtools had any impact.

Feel free to close this and thanks for all your help.

**Comment by jkbonfield** [comment]
Hmm, I guess we can close it as we're not going to be able to diagnose this anyway without access to data.  It does feel a bit unsatisfactory to have fixed a bug without quite knowing how.

Is it possible you'd be willing to try one last test for us please?  That is to compile your samtools using the gcc or clang address sanitizer?

Probably the easiest route here is make clean in both htslib and samtools dirs followed by adding -fsanitize=address to the make line with e.g.

```
make CC="gcc -fsanitize=address"
```

This build will be slower, but it'll validate memory accesses to look for any uninitialised memory accesses or malloc/free errors.

**Comment by pauldwolfe** [comment]
Of course, would you like me to do it from a the latest code or a 1.9 tag to really replicate the error?

Bit of a busy day today, but I should be able to get to it early this week.

**Comment by jkbonfield** [comment]
You just know I'm going to answer that with both! :-)

However probably the most important is the latest code base, just to be sure it's fixed and not just some undefined behaviour which is now flukily working.

**Comment by pauldwolfe** [comment]
hehe, i'll see what i can do. keep you posted.

**Comment by pauldwolfe** [comment]
Shouldn't be a problem to try this with both 1.9 and 1.10. Will memory issues end up in stdout/stderr?

**Comment by pauldwolfe** [comment]
The plot thickens, when I compile 1.9 with gcc address sanitizeron the VM with which I'm running (Debian 9) i don't see the issue at all. Also don't see any additional logging coming from the sanitization. 

I'm trying to track down exactly where the samtools 1.9 we've been using was built, but that information looks lost. There is a chance it was built on Fedora, and now running on Debian. Could that be the cause?

Given all this uncertainty might be best we chock this one up to an environmental issue.

**Comment by jkbonfield** [comment]
Hmm.  I'm thinking perhaps it's something quirky like that too.  Note complete silence from the address sanitizer is good.  You only get output (to stderr) if it fails.

If we cannot find any problems with 1.10 and the address sanitizer isn't saying there is something specific about your data that triggers a bug, then I'm inclined to ignore this until (if) we find it happening again on a modern build.

Rather unsatisfactory, but it's hard to do anything more concrete with such a hard to test case.

**Comment by jkbonfield** [comment]
I did try testing a variety of corner cases here, such as data aligned off the ends of chromosomes, but was not able to reproduce it - even with 1.9.  That leaves me a little unsure as I can't say for sure we found and fixed a bug.

However I'm closing it as we haven't seen this happen with the current release.  Feel free to prod the issue again if you get issues with 1.10 and I'll reopen.
