### ISSUE TITLE
Reading from stdin

### ISSUE THREAD

**Issue by Shhsvri** [samtools/htslib#1043]
I would like to format a .bcf file in with these two commands:

bcftools view -R $REF $OUTPUT/$i.bcf | grep -v ^# |
printf 'CHROM\tPOS\tREF\tALT\tDP\t\n' && bcftools query -f '[%CHROM:%POS %REF %ALT %GT %DP\n]' -

$REF is a tab delimited file of the genomic coordinates I am hoping to pull.

Is there a way to combine these two somehow? I am willing to fork and find a way if it is not currently supported.

**Comment by pd3** [comment]
This question should be asked on bcftools github page (https://github.com/samtools/bcftools/issues) not here. I don't know what exactly are you trying to achieve but assuming you want to stream both parts of the output into another command, in bash you can do it like this:
````
(printf 'CHROM\tPOS\tREF\tALT\tDP\t\n';
bcftools query -R $REF file.bcf -f '[%CHROM:%POS %REF %ALT %GT %DP\n]') | ...
````
