### ISSUE TITLE
Question about the API: reusing a bcf_srs_t for a new iteration ?

### ISSUE THREAD

**Issue by lindenb** [samtools/htslib#1058]
Hi all,

Not a bug, but a question; is it possible to _reset_ a `bcf_srs` for a new iteration ?

say I `break` into a  `bcf_sr_next_line`  loop 

```
while(bcf_sr_next_line(fp)) {
    (....)
    break;
     } 
```

and now I want to get all the variants in the vcf: Is it possible without re-opening everything (?) and is there a standard way to `clear` the previous iteration.

It's not clear to me when I read `synced_bcf_reader.h` 

Thanks !
Pierre

**Comment by lindenb** [comment]
oh, I see now, it's a one-iteration only.

**Comment by pd3** [comment]
I am not sure if I fully understand the question. There is the function `bcf_sr_regions_seek`, but it is not possible to go back to the previous result, if that's what you mean.
