### ISSUE TITLE
Cram Indexing Failed to populate reference

### ISSUE THREAD

**Issue by Roj4ck** [samtools/htslib#1069]
I'm currently trying to index a cram file using 
samtools index -b  123456.cram
After executing that command I'm getting continuous errors
[E::cram_get_ref] Failed to populate reference for id 37
[E::cram_get_ref] Failed to populate reference for id 38 
etc.  
I've seen searched through other issues in github where the solution is utilizing a a reference directory in the form of REF_PATH.  
export REF_PATH=/home/pathtomd5files/ 
I have all of the md5's, the cram files, the hg19.fa reference and hg19.fai in the same folder and i'm using the command but I'm still getting the same error.  Is there an additional step that I'm missing here or some other step that I need to take to index these cram files?

**Comment by Roj4ck** [comment]
Additionally I did try using the perl script from misc but there seems to be an error in the script so I got the following response from that:
syntax error at seq_cache_populate.pl line 10, near "<"
Excessively long <> operator at seq_cache_populate.pl line 21.

**Comment by daviesrob** [comment]
Running `seq_cache_populate.pl` should work like this:

```
./misc/seq_cache_populate.pl --root /tmp/seq_md5 /tmp/fasta/S_cerevisiae_S288c.fa
Reading /tmp/fasta/S_cerevisiae_S288c.fa ...
/tmp/seq_md5/d0/5f/97502be63502b1dc28cba2e4d8f8 chrI
/tmp/seq_md5/67/2c/cac60edc61550caa540019ada6fa chrII
/tmp/seq_md5/77/28/abd795a836a28ac5302a822ae3bf chrIII
/tmp/seq_md5/62/8a/68c42c3b90b5a99e1f0432dd1a0d chrIV
/tmp/seq_md5/2b/9a/eb682e653932db18aa15141a894f chrV
/tmp/seq_md5/4f/08/2ebb0ff6891de0977a44b979a828 chrVI
/tmp/seq_md5/5d/d0/00119c3d998a90045aff8ef4a724 chrVII
/tmp/seq_md5/d6/66/bf2e0615bfaea40d4e28f50a7407 chrVIII
/tmp/seq_md5/2f/d3/4473d35a98406b22cf1acc7e4272 chrIX
/tmp/seq_md5/ad/c3/af690772dda4a3f1df4a3d537db3 chrX
/tmp/seq_md5/c8/31/338ca9079d76bebd0b0a5eb102ef chrXI
/tmp/seq_md5/e3/67/1a75d26be1bd238fca7603aeb1c7 chrXII
/tmp/seq_md5/bd/77/49aa603a68c807c4b5eaa92bb797 chrXIII
/tmp/seq_md5/ff/d6/aeffb54ade3d28ec7644afada2e9 chrXIV
/tmp/seq_md5/b8/51/ae530640b418070c789fa2e93c32 chrXV
/tmp/seq_md5/2e/40/64f6a9abf2a34ab64e37149875fb chrXVI
/tmp/seq_md5/71/c3/9cf065b8d574f636b654c274cf1b chrMT
```

Then the corresponding `REF_PATH` would be `/tmp/seq_md5/%2s/%2s/%s`.

The `%2s/%2s/%s` part is there so the CRAM reader knows how to split the MD5 to get the path through the directory tree `seq_cache_populate.pl` made.

Of course in reality you would want to put them somewhere more permament than `/tmp`.

**Comment by Roj4ck** [comment]
I actually found this command on a different website and I'm currently executing the following commands:
wget -q https://raw.githubusercontent.com/samtools/samtools/develop/misc/seq_cache_populate.pl
perl seq_cache_populate.pl -root $(pwd)/cache ${fasta}
export REF_PATH=$(pwd)/cache/%2s/%2s/%s:http://www.ebi.ac.uk/ena/cram/md5/%s
export REF_CACHE=xx

It currently says Reading STDIN ... so I figured I'd let the process complete (hopefully that is the correct command to execute)

**Comment by daviesrob** [comment]
Does your `${fasta}` variable contain anything?  `Reading STDIN` suggests it was empty, so `seq_cache_populate.pl` is waiting for you to type something in for it to read.

**Comment by Roj4ck** [comment]
I didn't have that variable set.  I should utilize the hg19.fa for that correct?

**Comment by daviesrob** [comment]
Yes, or just use the path to the file in place of the variable.

Hopefully if it makes a reference cache for you, `samtools index` will start to work.

**Comment by Roj4ck** [comment]
This solved my problem and I was able to make all of my indexes!  Thank you so much!
