### ISSUE TITLE
[Feature Suggestion] optimize bam_read1 implementation for batch processing

### ISSUE THREAD

**Issue by Parsoa** [samtools/htslib#1082]
I've had a scenario recently that I need to read entries from a BAM file in large batches (say 2M at a time) and then distribute these between a pool of threads that each would do some work. With the current design `bam_read_1` will reuse the same `bam_1t` and `bam1_core_t` for every entry and would reallocate `data` if necessary. However this means that it's not possible to save results from the iterator for later access without copying the entire structure as the iterator will have entirely different values by the time it's actually used. This is inefficient as the structs need to be updated (and probably reallocated) once and then copied once again for later access in similar scenarios. In my case this resulted in a 2.5x slowdown.

I think it would be a useful addition to have a new `bam_read1` implementation that allocates new structs for each entry and hence allows lazy access without the need to copy the iterator structs each. I have already implemented this for my own purposes, however I can polish it up and send a pull request if you think it's something that may have wider use.

**Comment by daviesrob** [comment]
`bam_read1` will use whatever `bam1_t` you pass to it, so if you don't want to reuse a previous one you can simply give it a pointer to a new structure.

HTSlib 1.10 also got an interface that allows you to change how the memory is managed, while allows you to do things like read a block is records into an array.  You can also store the variable-length parts in a big block if you want to.  See the [documentation here](https://github.com/samtools/htslib/blob/9de45b7/htslib/sam.h#L860), which includes example code for how you use it.

**Comment by Parsoa** [comment]
Ah thanks, hadn't come across those before. I'll close this issue then.
