### ISSUE TITLE
[E::hts_hopen] Failed to open file, in folder with space in name (folder name cannot be changed)

### ISSUE THREAD

**Issue by TeresaPegan** [samtools/htslib#1099]
Hello,
I have some data on a Dropbox Business account, and Dropbox Business requires its folder name to have spaces and parentheses in it, e.g. "Dropbox (My University)". As a result, I am getting an htslib error when I try to do an analysis (with a program called ANGSD): htslib seems to not be able to understand the file path of an input file beyond the first space in the Dropbox folder name. When my file path is /Users/tmpegan/Dropbox (My University)/mydata/myfile, I get this error:
```
[E::hts_hopen] Failed to open file /Users/tmpegan/Dropbox
```

I have tried escaping the spaces and parentheses:  /Users/tmpegan/Dropbox\ \\(My\ University\\)/mydata/myfile
And I've tried putting the whole file path in quotes: "/Users/tmpegan/Dropbox (My University)/mydata/myfile"
But I still get this [E::hts_hopen] message.

I am also in contact with Dropbox about how to deal with the spaces in the file name - really, it seems kind of ridiculous the folder must be named this way - but I was also wondering if anyone knows whether it is possible and how to input a file path with spaces in it so that htslib can read it properly. I'm not sure why escaping or quoting the file path does not work?

Thanks!
-Teresa

**Comment by valeriuo** [comment]
HTSlib seems to not have received the full file name from the calling application. So the issue, might be higher up on the calling stack. Can you give a full description of the command/script you are trying to run?
As a workaround, can you try creating a symbolic link to your file, without spaces in its name, and run your command/script on it?

Also, as a means to diagnose HTSlib issues, there is a bundled utility called `htsfile` in the HTSlib root folder. Can you try running it on your Dropbox file?
`./htsfile "/Users/tmpegan/Dropbox (My University)/mydata/myfile"`

**Comment by jmarshall** [comment]
A symbolic link should provide a good workaround.

This is indeed an angsd problem: contrary to the documentation, the filenames in `-bam filelist` are separated by whitespace, not newlines. See `angsd::getFilenames()` in angsd's _argStruct.cpp_.

**Comment by TeresaPegan** [comment]
Thank you very much, that helps clear it up for me.
