### ISSUE TITLE
How to avoid bam1_t * been cleanup by itself.

### ISSUE THREAD

**Issue by huangnengCSU** [samtools/htslib#1103]
Hi,
    I met a problem when using htslib library to read mpileup alignments. Bam1_t * automatically cleanup when reading more than a certain amount of mpileup data. I have found the `bam_set_mempolicy` API, and i using it like ` bam_set_mempolicy(bam1_t *p, 1| 2)`. But it stilled been cleanup. How can I use it and let the bam1_t * won't been cleanup until the program ends. Thanks so much.
Neng

**Comment by daviesrob** [comment]
You can't easily do this.  Mpileup copies your bam records into its own internal structures, which it manages.  These copies are the `bam1_t` records pointed to in the `bam_pileup1_t` structures returned by `bam_mplp64_auto()` and `bam_mplp_auto()`. When a record is no longer needed it will reuse the memory for a new one, and everything will be freed when you call `bam_mplp_destroy()`.

If you do want to keep the data for longer than mpileup you would have to take your own copy.  You could do this in your `bam_plp_auto_f` callback function, but be aware that mpileup may change the data in its copy if you have BAQ or overlap detection turned on.  You could alternatively take copies of the records returned in the `bam_pileup1_t` structures, taking care to track which ones you've already got.

I'm not sure why you would want to do this, though.  Unless you have a small amount of input data or a lot of memory, wouldn't you run out of space to store everything before the program finished?

**Comment by huangnengCSU** [comment]
Thank you for your response. I wanted to read the bam file with a small window size each time. If so, I have to open and close a BAM file frequently, which affects the reading speed seriously. So I think maybe I can load all BAM data into memory at one time. It turns out that I'm trying a very bad solution. Finally, I chose to read a portion of the data at a time, and then the read window was larger to avoid frequently opening and closing files.
