### ISSUE TITLE
Enable forward declarations

### ISSUE THREAD

**Issue by lczech** [samtools/htslib#1106]
Hi there,

I am working in C++, and want to avoid including htslib headers in my headers, so that the global namespace of my library doesn't get polluted with other library's symbols. However, to be able to use htslib data in my classes, I then would at least need to forward declare them. Unfortunately, the htslib structs are all declare as typdefs of anonymous structs, such as 

    typedef struct {
        // ...
    } htsFile;

These cannot be forward declared (see [here](https://stackoverflow.com/questions/10249548/forward-declaring-a-typedef-of-an-unnamed-struct) and [here](https://stackoverflow.com/questions/38874235/forward-declaring-anonymous-structure-from-c-in-c) for example). Hence, I suggest to add names to these structs, such as

    typedef struct htsFile_s {
        // ...
    } htsFile;

As far as I can tell, this would not change anything else, and would not destroy any compatibilities. But it would make integration into C++ way nicer. (Even better would be to somehow offer namespaces if compiled with C++, but let's go one step at a time).

Is that something that would be possible? I could write a PR if needed.

Best
Lucas

**Comment by valeriuo** [comment]
Since we are naming some structs (e.g. `htsFormat`, `hts_opt`), we could named them all. Please make the PR.

**Comment by daviesrob** [comment]
Yes, there's no harm in this.  But if you do make a PR, please give the struct the same name as the typedef, i.e.:
```
typedef struct htsFile {
} htsFile;
```

Both `struct htsFile` and `htsFile` will co-exist quite happily.

**Comment by jmarshall** [comment]
Relatedly, I have an upcoming branch ([see reserved-identifiers](https://github.com/jmarshall/htslib/tree/reserved-identifiers)) that in part renames e.g. `typedef struct __hts_idx_t hts_idx_t` to `typedef struct hts_idx_t hts_idx_t`. So you might skip those ones in your PR, or feel free to add the changes in jmarshall/htslib@015f59f5b0bed7ceb7535fd76771ff47c427bc14 to your PR. (Or as this commit changes existing albeit weirdly-underscored public struct tags, the maintainers may prefer not to.)

**Comment by lczech** [comment]
Thanks. Currently, I am only working with `htsFile` from `htslib/hts.h`, as well as most of the structs defined in `htslib/vcf.h`. So, at least for now, I'm shying away from applying this to all of htslib, as I feel that I am lacking deeper understanding of the other parts of the library. 

Would I just need to adjust the headers in `htslib/*.h`, or other files as well? A quick search gives (with htslib 1.10.2):

    # in the main htslib dir
    grep -rn "typedef struct" . | wc -l
    164

with [typedef_struct.txt](https://github.com/samtools/htslib/files/4969843/typedef_struct.txt) containing the list of all these definitions that might need to change.

Which of these would need to be changed?

**Comment by valeriuo** [comment]
> Which of these would need to be changed?

You only make use of the exported ones. That is `hts.h`, `sam.h`, `vcf.h`, `synced_bcf_reader.h`, `tbx.h`, `regidx.h`, contained in `<HTSlib_root>/htslib`. The other exported interfaces (`cram.h`, `bgzf.h` etc.) already have named structures.

**Comment by lczech** [comment]
Thanks! As of now, I'm lacking the time to dive into this (and I'm okay for now with having to pull the `vcf.h` header into my headers). But I'll keep it in mind and hopefully will be able to return to this at some point.

**Comment by lczech** [comment]
Oh wow, thanks! I didn't expect someone else to pick that issue up, thanks @jmarshall !

**Comment by lczech** [comment]
Hi again,

it's been a while since I worked on the code that uses htslib, but now finally got back to it, and wanted to try the newly-enabled forward declarations.

However, as I am working in C++, this seems to fail with `conflicting declarations` - I think the rules differ there for C and C++. 

I tried:

```
extern "C" {
    typedef struct htsFile htsFile;
    // OR
    struct htsFile;
    typedef htsFile htsFile;
}
```

in my header, and neither works. Any hints?

**Comment by valeriuo** [comment]
The `struct` name from C becomes a type in C++, because structs in C++ behave more like classes. So you don't need the `struct` keyword any more when creating a `struct` variable in C++. Thus, forward declaring `struct htsFile` should suffice. Nevertheless, `typedef htsFile htsFile;` should be harmless. What compiler are you using and what is the exact error message?
Also, are you including your header file from multiple places?

**Comment by lczech** [comment]
Hi @valeriuo, and thanks for the quick reply!

I now tried this:
```
extern "C" {
    struct htsFile;
    typedef htsFile htsFile;
}
```
and also without the `typedef` line in my C++ header, and then actually including `hts.h` from my cpp file. I also tried without the `extern "C"`, but that does not change anything.

With gcc 9.3.0, I then get:

```
In file included from /home/lucas/Dropbox/GitHub/genesis/lib/genesis/population/formats/hts_file.cpp:36:
/home/lucas/Dropbox/GitHub/genesis/build/genesis-htslib/include/htslib/hts.h:249:3: error: conflicting declaration ‘typedef struct htsFile htsFile’
  249 | } htsFile;
      |   ^~~~~~~
In file included from /home/lucas/Dropbox/GitHub/genesis/lib/genesis/population/formats/hts_file.cpp:33:
/home/lucas/Dropbox/GitHub/genesis/lib/genesis/population/formats/hts_file.hpp:40:12: note: previous declaration as ‘struct htsFile’
   40 |     struct htsFile;
      |            ^~~~~~~
```
in the first case (just struct), and almost identical, but with `note: previous declaration as ‘typedef struct htsFile htsFile’` for the second case (with the additional typedef).

In that compilation unit, `hts.h` is included once now - it was twice before, once in the my header, and once in the cpp, but the whole point of this exercise is to get rid of the header include, so that my global C++ namespace is not full of htslib symbols. But all that should not matter, seeing that htslib uses proper header guards, right?

Thanks for your advice and so long
Lucas

**Comment by jmarshall** [comment]
Your _genesis_ project is compiling against HTSlib 1.10.2, which does not include PR #1115 — which is what enabled this forwarding for `htsFIle` (and a number of others).

**Comment by lczech** [comment]
Haha, oh my... I really thought that I updated that locally. Apparently not... Works fine now! Still a bit cumbersome to completely avoid including any htslib headers in my headers, but I guess that is the price I have to pay if I want to have my headers be completely independent of htslib.

Thanks for the support!
