### ISSUE TITLE
tabix multipule regions with delimited between output regions #30

### ISSUE THREAD

**Issue by ekushele** [samtools/htslib#1107]
I was not sure where to post my question.. so the question is [here](https://github.com/samtools/tabix/issues/30)

Hi,

Say I have a bed file, `file.bed`, and I want to retrieve multipule regions.
file.bed:

```
chr1    10468   10469   
chr1    10470   10471   
chr1    10483   10484   
chr1    10488   10489   
chr1    10492   10493   
chr1    10496   10497 
```
running `tabix file.bed chr1:10468-10490 chr1:10478-10490 chr1:10496-10497` gives me all the rows that matches region in the file.bed:

```
chr1    10468   10469  
chr1    10470   10471  
chr1    10483   10484  
chr1    10488   10489  
chr1    10483   10484  
chr1    10488   10489 
chr1    10496   10497 
```
Can I have an option to separate between the results, i.e. to define which rows came from each region? Something like:

```
chr1    10468   10469  
chr1    10470   10471  
chr1    10483   10484  
chr1    10488   10489
  
chr1    10483   10484  
chr1    10488   10489 

chr1    10496   10497 
```

**Comment by valeriuo** [comment]
Yes, it should be possible with an extra option.

**Comment by ekushele** [comment]
OK, so is this option exists?

**Comment by valeriuo** [comment]
Not yet.

**Comment by ekushele** [comment]
"Not yet" you mean that your are going to add this option? 

Thanks!

**Comment by valeriuo** [comment]
It's in the oven. You can test the pre-merged solution by pulling the PR branch from https://github.com/samtools/htslib/pull/1108

**Comment by ekushele** [comment]
Sorry if it's a very simple question... But how exactly I pull the PR from the specific branch?

**Comment by ekushele** [comment]
Amazing, thanks!

**Comment by ekushele** [comment]
Maybe it will be useful to add the source window as a title to each chunk, where something like 
`tabix file.bed chr1:10468-10490 chr1:10478-10490 chr1:10496-10497 ----separate-regs`

would give:
```
>chr1:10468-10490
chr1    10468   10469  
chr1    10470   10471  
chr1    10483   10484  
chr1    10488   10489
>chr1:10478-10490  
chr1    10483   10484  
chr1    10488   10489 
>chr1:10496-10497
chr1    10496   10497 
```
(My final target is to take the separate regions, and to write each one of them as a separate file, with the source window as file name)

**Comment by valeriuo** [comment]
> (My final goal is to take the separate regions, and to write each one of them as a separate file, with the source window as file name)

That's a different request and would merit its own solution (pull request). The **region:start-end** would not work as a filename, due to the inclusion of the colon symbol. It would most likely be something like **region_start_end**.

**Comment by ekushele** [comment]
Sorry for that, I thought it would be enough, but then I had a problem with regions that has no records.
So maybe just to add the **region:start-end** as the separator, like the example I brought.
(For now, I used the PR you mentioned above, and changed it a little, so in line 298 (inside the `for` loop, first command) I have:
```
 if (args->separate_regs)
                {
                        fputs(">",stdout);
                        puts(regs[i]);
                }
```
and I removed line `if (args->separate_regs && i < nregs-1 && found) puts("");`

**Comment by jmarshall** [comment]
Tabix is used for arbitrary data, so it is not trivial to construct a title line that is distinguishable from whatever the records might be. The only option would be to use the comment character that is recorded in the _.tbi_ file.

> (My final goal is to take the separate regions, and to write each one of them as a separate file, with the source window as file name)

At this point, it would seem to be best to write a script that invokes tabix once for each region:

```sh
for region in $REGIONS
do
    tabix file.bed $region > $region.bed
done
```

**Comment by ekushele** [comment]
Why what I did above is not good?

Yes, but the problem is that it takes a long time, and if I read the `file.bed` only once (I.e. running tabix command on multipule regions) it reduces the run time sharply

**Comment by valeriuo** [comment]
I changed the PR #1108 to show the region name on top of the group. I followed @jmarshall's suggestion to have the leading character be the file specific comment symbol. The option was renamed to `--separate-regions` by popular demand, and it doesn't print the region name if no records overlap that region.

```
#chr1:10468-10490
chr1    10468   10469  
chr1    10470   10471  
chr1    10483   10484  
chr1    10488   10489
#chr1:10478-10490  
chr1    10483   10484  
chr1    10488   10489 
#chr1:10496-10497
chr1    10496   10497 
```

**Comment by ekushele** [comment]
That's great, thanks!!
