### ISSUE TITLE
i have problem

### ISSUE THREAD

**Issue by amine900-tech** [samtools/htslib#1120]
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'shared' failed
make: *** [shared] Error 1
make: *** Waiting for unfinished jobs....

**Comment by valeriuo** [comment]
And how is it connected to HTSlib? There is no target named **shared** in the Makefile.

**Comment by amine900-tech** [comment]
so..What is the solution in your opinion??

**Comment by amine900-tech** [comment]
er -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -lm -ldl -rdynamic -lCLHEP -lgsl -lgslcblas -lm -lboost_system -lboost_filesystem vis/VRML.o: file not recognized: File truncated collect2: error: ld returned 1 exit status Makefile:22: recipe for target 'shared' failed make: *** [shared] Error 1 make: *** Waiting for unfinished jobs....
