### ISSUE TITLE
so..What is the solution in your opinion??

### ISSUE THREAD

**Issue by amine900-tech** [samtools/htslib#1121]
so..What is the solution in your opinion??

_Originally posted by @amine900-tech in https://github.com/samtools/htslib/issues/1120#issuecomment-674435352_

**Comment by amine900-tech** [comment]
er -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -lROOTDataFrame -pthread -lm -ldl -rdynamic -lCLHEP -lgsl -lgslcblas -lm -lboost_system -lboost_filesystem vis/VRML.o: file not recognized: File truncated collect2: error: ld returned 1 exit status Makefile:22: recipe for target 'shared' failed make: *** [shared] Error 1 make: *** Waiting for unfinished jobs....

**Comment by jkbonfield** [comment]
I don't know what package this error is from (and I tried googling the error and all I get is your identical question to Ask Ubuntu), but it is not htslib.  Sorry, but we cannot help you with this.
