### ISSUE TITLE
C compiler doesn't work

### ISSUE THREAD

**Issue by zeyunlu** [samtools/htslib#1125]
Hello, I am totally new to the samtools. I need to use tabix to finish my job.

When I follow the steps to install htslib, `./configure` gives me

checking for gcc... PATH/miniconda3/bin/x86_64-conda_cos6-linux-gnu-cc
checking whether the C compiler works... no
configure: error: in PATH/tools/htslib-1.10.2:
configure: error: C compiler cannot create executables
See config.log for more details

I'm on my university high computing server using ssh.
I really appreciate your help! Thanks!

**Comment by valeriuo** [comment]
What is error message from `config.log`?

**Comment by zeyunlu** [comment]
Hello, You may close the issue!
