### ISSUE TITLE
CRLF line termination not handled properly in sam_parse_worker

### ISSUE THREAD

**Issue by anderskaplan** [samtools/htslib#1148]
To reproduce: `unix2dos test/index.sam`, then run the test suite.

Actual: The test test_index fails, but only in the multi-threaded case. The single-threaded case passes.
This is because the line parser in sam_parse_worker does not handle CRLF line endings properly. The CR is passed on to sam_parse1 where it is included in the aux field data. The resulting BAM differs from the reference.

Expected: The test suite should pass regardless of line endings.

**Comment by whitwham** [comment]
Fixed in #1149.
