### ISSUE TITLE
INSTALL: provide an example of building with libdeflate in a non-standard localization 

### ISSUE THREAD

**Issue by darked89** [samtools/htslib#1173]
Hello,

to make things a bit easier for people installing libdeflate in i.e. /opt/soft, you may consider adding an extra info to the INSTALL file:
```
## configure with --libdeflate

* if libdeflate was installed using a non-canonical prefix ( not /usr/local/) but in i.e. /opt/soft:

./configure CFLAGS="-I/opt/soft/include" LDFLAGS="-L/opt/soft/lib" --with-libdeflate --prefix=/opt/soft

* check that the configure output contains:
checking for libdeflate.h... yes
checking for libdeflate_deflate_compress in -ldeflate... yes

```

Hope it helps,

Darek Kedra

**Comment by jkbonfield** [comment]
The [original PR ](https://github.com/samtools/htslib/pull/581) has a DIR option so you could do e.g. `--with-libdeflate=/opt/soft`.   I still think this is less confusing that having to manually set CFLAGS and LDFLAGS.  There's very little difference frankly between:

```
./configure CFLAGS="-I/opt/soft/include" LDFLAGS="-L/opt/soft/lib" --with-libdeflate
```

and

```
./configure CFLAGS="-I/opt/soft/include -DHAVE_LIBDEFLATE" LDFLAGS="-L/opt/soft/lib -ldeflate"
```

(other than validating it works).

**Comment by darked89** [comment]
Hello,

I am fine with whichever option The Developers will choose as the recommended one. My issue was mainly with including such command example in INSTALL so the other people doing the installation will not need to search for it. 

Best wishes,

Darek Kedra

**Comment by jkbonfield** [comment]
It does already have this just below the libdeflate bit:

```
    ./configure CPPFLAGS=-I/usr/pkg/include \
                LDFLAGS='-L/usr/pkg/lib -Wl,-R/usr/pkg/lib'
```

I'm not sure what more you're asking for specifically.

**Comment by darked89** [comment]
OK, I got it, indeed this is in the INSTALL file. I have been just lazy searching for the libdeflate string, not getting it, then getting into a googling mode and finally opening the issue after I tested the solution.  

Thank you for your help 

DK
