### ISSUE TITLE
Tabix doesn't recognize -S (--skip-lines) option

### ISSUE THREAD

**Issue by jrobinso** [samtools/htslib#1186]
Perhaps I'm misinterpreting this option, or making some other error, but I assumed the "-S" option would ignore the number of lines specified.   I'm trying to index a bed file with a track line, so to tell tabix to skip the first line (the "track" line) I tried this

```
tabix -S 1  -p bed gcnv_track_example_data.chr22.bed.gz
[E::get_intv] failed to parse TBX_GENERIC, was wrong -p [type] used?
The offending line was: "track  type=gcnv highlight=RP-1425_BON_B17_29_1_D1_v1_Exome_GCP;blue highlight=RP-1425_BON_B18-97_3_D1_v1_Exome_GCP;red viewLimits=0:5 maxHeightPixels=500:200:50"
Segmentation fault: 11
```

This file indexes fine if I delete the track line,  but I want to keep it.   Many bed files have track lines so I think I must be missing something.

**Comment by valeriuo** [comment]
There is definitely a bug. A fix will be available shortly.

**Comment by twmccart** [comment]
This bug appears to still be active.
