### ISSUE TITLE
Missing "ks_initialize" when installing htslib by Conda on a Mac

### ISSUE THREAD

**Issue by Jingwen7** [samtools/htslib#1192]
Hi,

I find that when installing htslib by Conda on a Mac, function "ks_initialize" is missing from kstring.h. But when I install htslib on linux through Conda, function "ks_initialize" is there. Do you know why this is happening? I just wonder if the version of htslib for OSX on Conda is not up to date? If it's the case, can you please update it? Thank you very much!

Best,
Jingwen

**Comment by jkbonfield** [comment]
This function arrived with htslib 1.10.  The difference you are seeing is simply that your conda is installation two different versions on two different operating systems.

This is a known conda bug (see the issue John referred to).  You may find that using "mamba" as a package installer will work, but it's not guaranteed as it can also depend on what other packages you've already installed in your conda environment.

Note you can be explicit in the version installed.  For example:

```
conda install 'htslib>=1.10'
```

However IMO you shouldn't need to.  It should always install the latest available.  I would strongly advise that you add your voice to the Conda bug reports.  The more that do so, the more likely it is to get fixed.

**Comment by jkbonfield** [comment]
Closing this as it's not an htslib issue per-se.
