### ISSUE TITLE
Byte Swapping Code Inconsistent with BCF Specification

### ISSUE THREAD

**Issue by jonathonl** [samtools/htslib#1194]
The BCF specification at http://samtools.github.io/hts-specs/BCFv2_qref.pdf defines the n_allele_info field as a uint32 field that is bit-packed with two subfields (n_allele and n_info). This suggests that the byte swapping to support big endian systems should happen on the 32-bit integer before/after n_allele and  n_info are unpacked/packed. This is also consistent with how the n_fmt_sample bit-packed field is handled. Yet the code at the links below treat n_allele and n_info as two separate 16-bit fields and perform byte swapping on them independently as 16-bit integers, which seems contrary to the original intent in the specification. 

https://github.com/samtools/htslib/blob/9583bf8b41dbf1c27ca18dc752f0eb22d7cc1d8b/vcf.c#L1775-L1776
https://github.com/samtools/htslib/blob/9583bf8b41dbf1c27ca18dc752f0eb22d7cc1d8b/vcf.c#L1236-L1237

**Comment by daviesrob** [comment]
HTSlib only supports [BCFv3](https://samtools.github.io/hts-specs/VCFv4.3.pdf#subsection.6.3), and not BCFv2, however the encoding of the `n_info`, `n_allele`, `n_sample` and `n_fmt` fields is the same.  (Note that the BCFv3 specification linked to is a bit broken at the moment - it will be fixed once samtools/hts-specs#456 is merged.)  In both versions of the specification the on-disk format is little-endian and the data should end up looking like this, in file order:

```
n_info_lo
n_info_hi
n_allele_lo
n_allele_hi
```

This is the form that is produced and consumed by HTSlib, irrespective of the platform endian-ness.

**Comment by pd3** [comment]
I believe with support BCFv2.2, BCFv3 does not exist as far as I know

**Comment by daviesrob** [comment]
Yes, sorry.  I was confusing it with BCF2.1 (I think).

**Comment by jonathonl** [comment]
Ok, thanks for the clarification.
