### ISSUE TITLE
error with autoconf 2.70

### ISSUE THREAD

**Issue by mr-c** [samtools/htslib#1197]
Hello,

As you may know, there has been a [new release of autoconf for the first time in 8 years](https://lists.gnu.org/archive/html/autoconf/2020-12/msg00002.html). Alas, building htslib with autoconf 2.70 currently fails.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978835
Full build log is at http://qa-logs.debian.net/2020/09/26.ac270/htslib_1.10.2-5_unstable_ac270.log

**Comment by jmarshall** [comment]
Yes, I saw Matthias's bug report. It is a byproduct of this (from autoconf 2.70's _NEWS_):

> *** More macros use config.sub and config.guess internally.
>
> As a consequence of improved support for cross compilation [snip]

and the basic fix is to rename a variable. A fix is gestating.

**Comment by jmarshall** [comment]
Fixed by PR #1198; see also PR #1199.

**Comment by davmlaw** [comment]
If anyone needs a work around for an old version, I found this helped me

https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html

```
wget -O config.guess 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
wget -O config.sub 'https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'
```

**Comment by jkbonfield** [comment]
Or just install a new version which fixes this.  Generally there should be no requirement for sticking with old releases of samtools/htslib if you're compiling from source.  If there are issues with backwards compatibility, then it would be interesting to know.
