### ISSUE TITLE
tabix custom index file

### ISSUE THREAD

**Issue by anderspitman** [samtools/htslib#1213]
Does tabix support running with a custom index file, similar to the -X functionality in samtools?

https://github.com/samtools/samtools/issues/485

**Comment by valeriuo** [comment]
It does, but in a different [manner](https://github.com/samtools/htslib/commit/7e583ccea8e8a1a31c16bf5224d8f7785182dd82).

```
Example of usage:
    tabix file.vcf.gz##idx##crazy-index-file-name 1:10000060-10000060
```

**Comment by anderspitman** [comment]
Ah ok I've seen the ##idx## syntax mentioned, but I actually thought it was implemented in samtools, not htslib. And when I tried to get it to work in samtools, it wasn't working (-X did though). I'll try ##idx## with tabix and seen if I have more luck.

It should work with URLs, right?

**Comment by valeriuo** [comment]
> It should work with URLs, right?

Yes, it does. You can also use **-D** to prevent downloading the index file locally.
It should also work for samtools. What issue/error did you encounter?

**Comment by valeriuo** [comment]
Please reopen with additional info, if issue persists.
