### ISSUE TITLE
Orders of optional columns (Col no. 11 onwards) in CRAM files.

### ISSUE THREAD

**Issue by snashraf** [samtools/htslib#1232]
When we convert BAM to CRAM, the order of the optional columns are not fixed in the cram file. Did someone else face the same issue?We are moving to CRAM from BAM in our core lab so just wondering if this may affect any downstream analysis.

**Comment by jkbonfield** [comment]
I suspect the issue you're seeing is with MD, NM and RG as these are (normally) generated on the fly and so will appear out of order.

The order of the auxiliary tag columns have no meaning.  Indeed tools like picard will scramble the order routinely, even with SAM and BAM.  It shouldn't be an issue, although it can make validation a bit complex.  We have a test program (albeit slow) that helps with this: `test/compare_sam.pl file1.sam file2.sam`.

**Comment by jkbonfield** [comment]
Closing as assumed question is answered.
