### ISSUE TITLE
Making programs but clean deletes them

### ISSUE THREAD

**Issue by BJWiley233** [samtools/htslib#1233]
Is there a reason in the Makefile after building bgzip, htsfile, and tabix that they get deleted with `clean`?

```
BUILT_PROGRAMS = \
	bgzip \
	htsfile \
	tabix
```
...
```
clean: mostlyclean clean-$(SHLIB_FLAVOUR)
	-rm -f libhts.a $(BUILT_PROGRAMS)
```

**Comment by BJWiley233** [comment]
Nevermind it get install to /usr/local

**Comment by jkbonfield** [comment]
It's normal for clean to remove everything that has been built, including the final targets.
