### ISSUE TITLE
Skip reads with bad CIGAR strings

### ISSUE THREAD

**Issue by jakewendt** [samtools/htslib#1236]
My research lab has a number of large WGS bam files that were aligned for us by the provider using `Sentieon`.

```
@PG	ID:sentieon-ReadWriter	CL:/home/ec2-user/sentieon-genomics-201711.01/libexec/driver
 -r data/hg38.fa -t 40 -i data/XXXXXX.realigned.bam -q data/XXXXXX.recal_data.table
 --algo ReadWriter data/XXXXXX.recaled.bam	VN:sentieon-genomics-201711.01
```

We recently tried to run `bcftools mpileup` on these bam files and for many it would eventually crash with ...

```
bcftools: sam.c:3948: resolve_cigar2: Assertion `k < c->n_cigar' failed.
```

After some code modification I found a few reads with CIGAR strings like **97I37S**, **73I75S**, **71I79S**, **69I81S**, **68I82S** and **150I** which seem rather useless. I presume that there are many reads with CIGAR strings like this and that they are the problem.

Could the error be changed to include the offending read entry or at least the name and CIGAR string?

More importantly, could `bcftools` be modified to skip reads with bad CIGAR strings rather than fail?

Otherwise, assuming that I'm correct, the alternative would be to recreate my bam files, replacing all CIGAR strings that don't include an **M** with an **\***. Agreed?

**Comment by jkbonfield** [comment]
Those cigar strings aren't illegal or even "bad", but they are unusual.  My guess is Sentieon has done local reassembly and has placed reads entirely within large insertions.  If so it's likely correct, although sadly most of our tools won't utilise such data.

This shouldn't be producing an error in mpileup though.  Silently dropping them would be the easy fix I think.  Not ideal, but better than dying on valid data.

**Comment by jkbonfield** [comment]
I cannot reproduce this.  Specifically data with no overlapping bases never appears to even enter the `resolve_cigar2` function.

What version of samtools are you using? (`samtools --version` will give the appropriate details.) Do you have a single-line SAM file (you can replace any meta-data and sequence) demonstrating the problem?

**Comment by jakewendt** [comment]
Bummer that you could not reproduce. I'll keep digging. 

Our cluster currently has htslib, samtools and bcftools 1.11 installed.

I'm currently editing `bcftools-1.11/htslib-1.11/sam.c` to try to debug. I added a few lines and this is the tail of my log at failure. (Note that the line of failure will be different due to my additions.)

```
[E::bam_read1] query name E00368R:278:HJ2L7CCXY:6:1105:6238:51289
[E::bam_read1] query name E00368R:278:HJ2L7CCXY:3:1107:10074:26150
[E::bam_read1] query name E00368R:278:HJ2L7CCXY:3:1114:32370:19487
[E::resolve_cigar2] Jake testing c->n_cigar :2:
[E::resolve_cigar2] Jake testing k :1:
[E::bam_read1] query name E00368R:278:HJ2L7CCXY:1:2105:29762:9941
[E::bam_read1] query name E00368R:278:HJ2L7CCXY:2:1111:7923:47140
[E::bam_read1] query name E00368R:278:HJ2L7CCXY:2:1123:13636:16393
[E::bam_read1] query name E00368R:278:HJ2L7CCXY:6:1110:10551:12842
[E::resolve_cigar2] Jake testing c->n_cigar :2:
[E::resolve_cigar2] Jake testing k :2:
bcftools: sam.c:3975: resolve_cigar2: Assertion `k < c->n_cigar' failed.
```

I created smaller and smaller bam files by clipping out the region of failure.

```
~/.local/bcftools-1.11/bcftools mpileup -Ou -f 18.fa bcftools_test.bam -o /dev/null
[mpileup] 1 samples in 1 input files
[mpileup] maximum number of reads per input file set to -d 250
Assertion failed: (k < c->n_cigar), function resolve_cigar2, file sam.c, line 3948.
Abort trap: 6
```

It did not fail on my laptop running bcftools 1.6.

github would not allow the upload of a bam file so I gzipped a sam file.

[18.fa.gz](https://github.com/samtools/htslib/files/5997224/18.fa.gz)
[bcftools_test.sam.gz](https://github.com/samtools/htslib/files/5997231/bcftools_test.sam.gz)

**Comment by jkbonfield** [comment]
Ah I can see why it doesn't fail now.

f39dae751dae8c1abf8477074c5fbaea66d229df fixes the bug, so the develop branch is fine.  The bug was introduced in a2fdf3b which was in 1.11.  So 1.10 and earlier is fine.  1.12 (soon) will be fine, but 1.11 had an issue.

Thanks for the test cases and sorry I didn't think to try the official release instead of the dev branch.

**Comment by jakewendt** [comment]
Understood. I will downgrade to 1.10.2.
