### ISSUE TITLE
How can I get the reference sequence name of an alignment in a BAM file?

### ISSUE THREAD

**Issue by HatakeKakaxi** [samtools/htslib#1248]
I'm trying to parse a BAM file using htslib. However, I find it hard to get the reference sequence name of an alignment, which should be RNAME field in the alignment section of  a SAM file. So how can I get this field ?

**Comment by valeriuo** [comment]
Have you tried using the `bam_get_qname` macro from `sam.h`?
Something like:
```c
#include <stdio.h>
#include <sam.h>

int main(int argc, char **argv) {
	samFile *in = sam_open(argv[1], "r");
	bam_hdr_t *header = sam_hdr_read(in);
	bam1_t *b = bam_init1();
	int ret = sam_read1(in, header, b);
	printf("rname='%s'\n", bam_get_qname(b));
	sam_close(in);

	return 0;
}
```
with proper error and function result checking.

**Comment by HatakeKakaxi** [comment]
> I'm trying to parse a BAM file using htslib. However, I find it hard to get the reference sequence name of an alignment, which should be RNAME field in the alignment section of a SAM file. So how can I get this field ?

Now I get to know that the RNAME field has been parsed in sam.h. It is located in htslib/sam.h:
 `typedef struct bam1_core_t {
    hts_pos_t pos;
    int32_t tid;  // chromosome ID, defined by sam_hdr_t , a.k.a RNAME
    uint16_t bin; // NB: invalid on 64-bit pos
    uint8_t qual;
    uint8_t l_extranul;
    uint16_t flag;
    uint16_t l_qname;
    uint32_t n_cigar;
    int32_t l_qseq;
    int32_t mtid;
    hts_pos_t mpos;
    hts_pos_t isize;
} bam1_core_t;` 
The **tid** variable represents the RNAME field.

**Comment by HatakeKakaxi** [comment]
> Have you tried using the `bam_get_qname` macro from `sam.h`?
> Something like:
> 
> ```c
> #include <stdio.h>
> #include <sam.h>
> 
> int main(int argc, char **argv) {
> 	samFile *in = sam_open(argv[1], "r");
> 	bam_hdr_t *header = sam_hdr_read(in);
> 	bam1_t *b = bam_init1();
> 	int ret = sam_read1(in, header, b);
> 	char *rname = bam_get_qname(b);
> 	printf("rname='%s'\n", rname);
> 	sam_close(in);
> 
> 	return 0;
> }
> ```
> 
> with proper error checking.

No, I haven't thought about that yet.

**Comment by valeriuo** [comment]
`tid` is the numerical identifier of the reference name in the header structures. Also, it appears you are using an old version of HTSlib API, since the latest released `sam.h` does not contain that comment about the `tid` field.
What exactly is your use case?

**Comment by valeriuo** [comment]
I corrected my initial comment. You should use the `sam_hdr_tid2name` on the `tid` field.

**Comment by HatakeKakaxi** [comment]
> `tid` is the numerical identifier of the reference name in the header structures. Also, it appears you are using an old version of HTSlib API, since the latest released `sam.h` does not contain that comment about the `tid` field.
> What exactly is your use case?

I got it. Thank you very much. I'm trying to get the subsequence in the range [start, stop] of the reference file. Can I reach this goal using HTSlib API?

**Comment by jkbonfield** [comment]
Take a look at `sam_itr_queryi` or `sam_itr_querys` and `sam_itr_next`.  Example usage here:

https://github.com/samtools/htslib/blob/develop/test/test_view.c#L139-L152

**Comment by HatakeKakaxi** [comment]
> Take a look at `sam_itr_queryi` or `sam_itr_querys` and `sam_itr_next`. Example usage here:
> 
> https://github.com/samtools/htslib/blob/develop/test/test_view.c#L139-L152

Thank you but maybe you have a misunderstanding. I want to get the specific subsequence of the reference file which is FASTA format. Can I reach this goal using HTSlib API?

**Comment by valeriuo** [comment]
> Can I reach this goal using HTSlib API?

Yes, check the methods in `faidx.h`. Particularly 
`char *fai_fetch(const faidx_t *fai, const char *reg, int *len)`
and
`char *faidx_fetch_seq(const faidx_t *fai, const char *c_name, int p_beg_i, int p_end_i, int *len)`

**Comment by HatakeKakaxi** [comment]
> Take a look at `sam_itr_queryi` or `sam_itr_querys` and `sam_itr_next`. Example usage here:
> 
> https://github.com/samtools/htslib/blob/develop/test/test_view.c#L139-L152
> 
> Edit: I'm not sure what you mean by "subsequence" though. If it's the fragment of reference sequence you want and not the sequences aligned against it, then that's the faidx interface (used by `samtools faidx chrname:start-end` syntax). See htslib/faidx.h; likely `fai_load` and `fai_fetch` / `fai_fetch64`.

I got it. Thank you very much.

**Comment by HatakeKakaxi** [comment]
> > Can I reach this goal using HTSlib API?
> 
> Yes, check the methods in `faidx.h`. Particularly
> `char *fai_fetch(const faidx_t *fai, const char *reg, int *len)`
> and
> `char *faidx_fetch_seq(const faidx_t *fai, const char *c_name, int p_beg_i, int p_end_i, int *len)`

OK, Thank you.
