### ISSUE TITLE
Support for zlib-ng.

### ISSUE THREAD

**Issue by ghuls** [samtools/htslib#1257]
Add support for `zlib-ng`.
https://github.com/zlib-ng/zlib-ng

zlib-ng has its own API, but can also be compiled with zlib compatibility support.
https://github.com/zlib-ng/zlib-ng/blob/develop/PORTING.md

For now it seems to fail when running `samtools view`:
```
samtools: bgzf.c:540: bgzf_hopen: Assertion `compressBound(0xff00) < 0x10000' failed.
```
as zlib-ng might require a bigger buffer than zlib.

**Comment by jkbonfield** [comment]
Generally we suggest using [libdeflate ](https://github.com/ebiggers/libdeflate) as it's faster (see https://quixdb.github.io/squash-benchmark/unstable/).

I haven't tested linking against zlib-ng yet, but the source implies this should be impossible. 

https://github.com/zlib-ng/zlib-ng/blob/develop/compress.c#L75-L83

```
z_size_t Z_EXPORT PREFIX(compressBound)(z_size_t sourceLen) {
#ifndef NO_QUICK_STRATEGY
    /* Quick deflate strategy worse case is 9 bits per literal, rounded to nearest byte,
       plus the size of block & gzip headers and footers */
    return sourceLen + ((sourceLen + 13 + 7) >> 3) + 18;
#else
    return sourceLen + (sourceLen >> 12) + (sourceLen >> 14) + (sourceLen >> 25) + 13;
#endif
}
```

With 0xff00 as input, I make that either 0xff19 or 0xff1f if my maths is correct.  I'll debug it though.

**Comment by jmarshall** [comment]
I make it 73460, which is larger than 64K and in particular exceeds BGZF's BSIZE field. So in the worst case of a not very successfully zlib-ng-compressed block, the code would have retry it with plain zlib or make the input block smaller or something.

All that hardly seems worth implementing when libdeflate is a superior alternative. But if zlib-ng was made another compression alternative, it would be good to finally define a compression plugin point so HTSlib didn't grow another compression library link-time dependency…

**Comment by jkbonfield** [comment]
zlib-ng being ABI compatible just means you can drop in the library and it needs no change at all to our code.  Bar this!  Furthermore, when used in that zlib-compat way there is no way we can fall back to using vanilla zlib.  So we'd need to write a zlib-ng-native implementation, which all seems rather like pointless effort.

I changed the #define in htslib/bgzf.h to this and it works:

```
#define BGZF_MAX_BLOCK_SIZE 74000                                               
```

However it's questionable what ABI impact this has given the expected usage is to define static sized arrays.  While technically not an ABI change in *our* code as we expose nothing using that define, any code relying on that #define would need recompiling.

That said - it is infact pretty nippy so the public benchmarks aside, it looks like zlib-ng works well on BAM.  I'll do some bigger tests and include vcf.gz.

**Comment by jkbonfield** [comment]
Also there's another hack maybe... if zlib-ng is used limit it to level 2 as a minimum compression ratio and skip the compressBound assert!  That's not exactly an ideal solution, but it'd work as the higher memory limit is explicitly only for level 1 compression (which is pretty poor).

**Comment by jmarshall** [comment]
> I changed the #define in htslib/bgzf.h to this and it works:
>
>      #define BGZF_MAX_BLOCK_SIZE 74000

As well as the impact on the fixed-size arrays that would need to be audited: this only worked because you didn't encounter a compressed block that actually exceeded 64K.

It'd be better to adjust `BGZF_BLOCK_SIZE` to 58235, which would maintain the invariant that `compressBound_zlibng(BGZF_BLOCK_SIZE) < 64K`. But we've already spent more time thinking about this than it deserves… :smile:

**Comment by jkbonfield** [comment]
Correcting my earlier comment.  For what I've tested it is ABI-compatible as I can just do tweak LD_LIBRARY_PATH and get a running executable, but the official docs claim this may not be true for all cases.

> Please note that zlib-ng in zlib-compat mode is API-compatible but not
> ABI-compatible, meaning that you cannot simply replace the zlib library/dll
> files and expect the application to work. The application will need to be
> recompiled against the zlib-ng headers and libs to ensure full compatability.

So we could do something like:

```
#ifdef ZLIBNG_VERSION
#define BGZF_MAX_BLOCK_SIZE 74000
#else
#define BGZF_MAX_BLOCK_SIZE  0x10000
#endif
```

**Comment by jkbonfield** [comment]
> It'd be better to adjust `BGZF_BLOCK_SIZE` to 58235, which would maintain the invariant that `compressBound_zlibng(BGZF_BLOCK_SIZE) < 64K`. But we've already spent more time thinking about this than it deserves… 😄

Oh good point - bigger blocks would totally wreck bgzf indexing!

However yes, the ifdef ZLIBNG_VERSION check above could be used to change BGZF_BLOCK_SIZE.  That's a trivial non-intrusive change.

It's actually a shame it's not ABI compatible.  It's about time someone retired zlib with something more performant, and just replacing the dynamic library with a more modern implementation would be a huge win for thousands of applications.  I wonder why they chose to not keep compatibility.  I big mistake IMO. :/

**Comment by ghuls** [comment]
The assertion I encountered was when decompressing a BAM file (which was created with vanilla zlib), so it seems highly unlikely that the final decompressed size would be bigger than when zlib decompresses those blocks:

```samtools view test.bam```

So I assume it just makes sure it has more than enough space while decompressing, but actually uses less.
The main reason why zlib-ng support would be nice is that when zlib-ng is loaded for other zlib related tasks (like other parts of the pipeline (mapping, decompressing FASTQs) not related to SAMtools, it won't crash SAMtools like it does now.

**Comment by jmarshall** [comment]
Checking `compressBound()` when you're only going to use `inflate()` could be considered a bug, so the assertions could usefully be moved to inside `bgzf_write_init()` (which would mean you wouldn't encounter it in your decompression use case). And ideally converted to something less dramatic than an assertion…

**Comment by ghuls** [comment]
The assert seems to be used wrongly as far as I can tell as after calling compress or compress2, you get the actual length of the compressed data:
```
Z_EXTERN int Z_EXPORT compress(unsigned char *dest, unsigned long *destLen, const unsigned char *source, unsigned long sourceLen);
/*
     Compresses the source buffer into the destination buffer.  sourceLen is
   the byte length of the source buffer.  Upon entry, destLen is the total size
   of the destination buffer, which must be at least the value returned by
   compressBound(sourceLen).  Upon exit, destLen is the actual size of the
   compressed data.  compress() is equivalent to compress2() with a level
   parameter of Z_DEFAULT_COMPRESSION.
     compress returns Z_OK if success, Z_MEM_ERROR if there was not
   enough memory, Z_BUF_ERROR if there was not enough room in the output
   buffer.
*/

Z_EXTERN int Z_EXPORT compress2(unsigned char *dest, unsigned long *destLen, const unsigned char *source,
                              unsigned long sourceLen, int level);
/*
     Compresses the source buffer into the destination buffer.  The level
   parameter has the same meaning as in deflateInit.  sourceLen is the byte
   length of the source buffer.  Upon entry, destLen is the total size of the
   destination buffer, which must be at least the value returned by
   compressBound(sourceLen).  Upon exit, destLen is the actual size of the
   compressed data.
     compress2 returns Z_OK if success, Z_MEM_ERROR if there was not enough
   memory, Z_BUF_ERROR if there was not enough room in the output buffer,
   Z_STREAM_ERROR if the level parameter is invalid.
*/

Z_EXTERN unsigned long Z_EXPORT compressBound(unsigned long sourceLen);
/*
     compressBound() returns an upper bound on the compressed size after
   compress() or compress2() on sourceLen bytes.  It would be used before a
   compress() or compress2() call to allocate the destination buffer.
*/
```
https://github.com/zlib-ng/zlib-ng/blob/bc33b26ca5391eb6b2c952cd032920033be27a53/zlib.h

**Comment by jkbonfield** [comment]
I did some testing on a 1000Genomes VCF file (18Gb uncompressed) using bgzip.

| Tool          | Decompression | Recompresion | Size       |                   
| ------------- | ------------- | ------------ | ---------- |                   
| Zlib          | 0m28.156s     | 2m47.601s    | 341851007  |                   
| Zlib -1       |               | 1m3.631s     | 542381792  |                   
| Zlib-ng       | 0m21.422s     | 1m22.839s    | 394521678  |                   
| Zlib-ng  -1   |               | 0m40.212s    | 857844905  |                   
| Libdeflate    | 0m34.891s     | 1m15.881s    | 349434708  |                   
| Libdeflate -1 |               | 0m56.464s    | 408778568  |                   

- Zlib-ng is faster at decompression than libdeflate on this file.  This is a surprise, and infact bgzip -d is faster than the supplied minigzip -d (which took 34s).  I cannot explain this, unless somehow it's avoiding work - like not checking CRC?  It's odd.

- Zlib-ng's default compression size is poor on this data.  It's only barely smaller than libdeflate -1.

- Libdeflate compression speed is faster at default compression level, and considerably smaller.

- Zlib-ng is a bit faster compression at level 1, but the file size is vast.  Over double that of libdeflate -1.  I'm not convinced the trade off is worth it.

Testing decompression speeds on a BAM file, I get 10s for zlib-ng and 6s for libdeflate.  So the speed up there clearly isn't universal.

**Comment by jkbonfield** [comment]
> Checking `compressBound()` when you're only going to use `inflate()` could be considered a bug, so the assertions could usefully be moved to inside `bgzf_write_init()` (which would mean you wouldn't encounter it in your decompression use case). And ideally converted to something less dramatic than an assertion…

Given where it's done, it looks like it was added more as a developer check, to ensure we never set the block size too big.

I agree it should be put into the write side instead.  However arguably I think the assert is pointless as it fails if something *may* fail later, when in reality that's vanishingly rare.  We'd be better off just checking the zlib return value for each compression call to see if it completed the block or ran out of space.  (I'd hope we already do that, but haven't checked.) 

So frankly I expect just culling the assert completely would be the correct solution.

> (I suppose the truly heroic thing to do would be to replace the assertion with code in `bgzf_write_init()` to probe for a suitable value of `BGZF_BLOCK_SIZE` that satisfies the invariant, and use that instead of the constant in `bgzf_flush_try()` and `bgzf_write()`. Then zlib-ng's compatibility layer would work for BGZF compression too, just doing a slightly worse job of chopping the stream into blocks than classic zlib does.)

It's only level 1 of zlib-ng which has such an extreme growth.  Even then, it doesn't appear to on our data because it's just not random enough.  I'd be more inclined to simply try a higher compression level if it fails to fit, and if it *still* fails to fit then die horribly.  However that chance is tiny - it's never been an issue with normal zlib and I'm sure it wouldn't be in zlib-ng either.

**Comment by ghuls** [comment]
zlib-ng can be compiled with `NO_QUICK_STRATEGY` which probably solves this big growth (but compresses slower, I assume) ```c
../zlib-ng/deflate.c
140-} config;
141-
142-static const config configuration_table[10] = {
143-/*      good lazy nice chain */
144-/* 0 */ {0,    0,  0,    0, deflate_stored},  /* store only */
145-
146:#ifndef NO_QUICK_STRATEGY
147-/* 1 */ {4,    4,  8,    4, deflate_quick},
148-/* 2 */ {4,    4,  8,    4, deflate_fast}, /* max speed, no lazy matches */
149-#else
150-/* 1 */ {4,    4,  8,    4, deflate_fast}, /* max speed, no lazy matches */
151-/* 2 */ {4,    5, 16,    8, deflate_fast},
152-#endif
```

**Comment by jmarshall** [comment]
> However arguably I think the assert is pointless as it fails if something may fail later, when in reality that's vanishingly rare. We'd be better off just checking the zlib return value for each compression call to see if it completed the block or ran out of space.
[…]
> and if it still fails to fit then die horribly

You're quite right.

In fact, rather than die horribly what _bgzf.c_ could do is manually write out the BGZF block as a DEFLATE BTYPE=00 non-compressed block (which is guaranteed to fit) and succeed — and in fact it already has code to do that, it just wants to be extracted into a reusable function.

**Comment by jkbonfield** [comment]
I have a simple solution for now, which can be expanded if needs be.  I question whether "needs be" is likely to ever occur though.  Time will tell I guess!

**Comment by ghuls** [comment]
@jkbonfield 
Wouldn't you need to make sure the compression buffer will be large enough, just in case, so you don't overwrite arbitrary memory?

I had this in my local patched version (where compressed block size was arbitrary 2 * BGZF_MAX_BLOCK_SIZE bigger). 
```
diff --git a/bgzf.c b/bgzf.c
index b2ee7c8..e58dfe7 100644
--- a/bgzf.c
+++ b/bgzf.c
@@ -398,7 +398,7 @@ static BGZF *bgzf_read_init(hFILE *hfpr, const char *filename)
     if (fp == NULL) return NULL;
 
     fp->is_write = 0;
-    fp->uncompressed_block = malloc(2 * BGZF_MAX_BLOCK_SIZE);
+    fp->uncompressed_block = malloc(3 * BGZF_MAX_BLOCK_SIZE);
     if (fp->uncompressed_block == NULL) { free(fp); return NULL; }
     fp->compressed_block = (char *)fp->uncompressed_block + BGZF_MAX_BLOCK_SIZE;
     fp->is_compressed = (n==18 && magic[0]==0x1f && magic[1]==0x8b);
@@ -452,7 +452,7 @@ static BGZF *bgzf_write_init(const char *mode)
     }
     fp->is_compressed = 1;
 
-    fp->uncompressed_block = malloc(2 * BGZF_MAX_BLOCK_SIZE);
+    fp->uncompressed_block = malloc(3 * BGZF_MAX_BLOCK_SIZE);
     if (fp->uncompressed_block == NULL) goto mem_fail;
     fp->compressed_block = (char *)fp->uncompressed_block + BGZF_MAX_BLOCK_SIZE;
 
@@ -491,7 +491,7 @@ fail:
 BGZF *bgzf_open(const char *path, const char *mode)
 {
     BGZF *fp = 0;
-    assert(compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE);
+    assert(compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE * 2);
     if (strchr(mode, 'r')) {
         hFILE *fpr;
         if ((fpr = hopen(path, mode)) == 0) return 0;
@@ -514,7 +514,7 @@ BGZF *bgzf_open(const char *path, const char *mode)
 BGZF *bgzf_dopen(int fd, const char *mode)
 {
     BGZF *fp = 0;
-    assert(compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE);
+    assert(compressBound(BGZF_BLOCK_SIZE) < BGZF_MAX_BLOCK_SIZE * 2);
     if (strchr(mode, 'r')) {
         hFILE *fpr;
         if ((fpr = hdopen(fd, mode)) == 0) return 0;
```

**Comment by jkbonfield** [comment]
> In fact, rather than die horribly what _bgzf.c_ could do is manually write out the BGZF block as a single DEFLATE BTYPE=00 non-compressed block (which is guaranteed to fit) and succeed — and in fact it already has code to do that, it just wants to be extracted into a reusable function.

I've been blind!  Infact yes this is absolutely the right response, and it's *trivial* as bgzf_compress actually handles this case itself.  It's nothing more than a "if I didn't fit, jump up to level 0 code above". :-)

**Comment by ghuls** [comment]
Should the compression buffer not made large enough for the level 1 case, so when it tries to compress the output it does not over write memory after the buffer?

**Comment by jkbonfield** [comment]
> 
> 
> @jkbonfield
> Wouldn't you need to make sure the compression buffer will be large enough, just in case, so you don't overwrite arbitrary memory when level 1 was specified.
> 
> I had this in my local patched version (where compressed block size was arbitrary 2 * BGZF_MAX_BLOCK_SIZE bigger).

I'm not really sure where the double size came from (other than fd721f10, but why that number?).  Maybe it's something to do with the gzip layer, but the bgzf format explicitly can never go above BGZF_MAX_BLOCK_SIZE anyway as it has to be 64k blocks.  Indeed even the gzip layer appears to work in 64k segments, so I don't really understand the 2* unless it's doing some cunning double-buffering and flip-flopping between comp/uncomp in the same memory.

This doesn't solve the problem you have though.  If it is a problem, then it's a different one.  Note the compressed block size *cannot* be over 64k or the bgzf index no longer works.  Hence John's solution of using an uncompressed block is clearly better (and also smaller!).

**Comment by ghuls** [comment]
I get that the compressed block can never be over a certain size. 

Just from the porting comments it looks like zlib-ng might use temporarily more memory than stock zlib (not clear if this only applies to level 1 or that this can happen for each compression level (=e.g uses some scratch space)):
> If your application is pre-allocating a memory buffer and you are providing deflate/inflate init with your own allocator that allocates from that buffer (looking at you nginx), you should be aware that zlib-ng needs to allocate more memory than stock zlib needs. The same problem exists with Intels and Cloudflares zlib forks. Doing this is not recommended since it makes it very hard to maintain compatibility over time.

https://github.com/zlib-ng/zlib-ng/blob/develop/PORTING.md

**Comment by jkbonfield** [comment]
I'm assuming that is referring to use of the `alloc_func` and `free_func` members of the `z_stream` structure, which we don't change.

**Comment by jmarshall** [comment]
> I'm not really sure where the double size came from (other than fd721f10668de49d02f613678aa0c4105bd7f0b5, but why that number?). 

There are two buffers of size `BGZF_MAX_BLOCK_SIZE` each, so if you allocate them both in the same `malloc()` you need to malloc `N + N` = `2*N` = double the space. I'm not sure what the upcoming code referred to in that commit message is (and didn't find a hint in today's _bgzf.c_)… I suspect I was planning to implement plain gzip I/O using a 128K buffer and reuse the existing allocation for that case.

> Maybe it's something to do with the gzip layer, but the bgzf format explicitly can never go above BGZF_MAX_BLOCK_SIZE anyway as it has to be 64k blocks. Indeed even the gzip layer appears to work in 64k segments

…as I've always thought the existing plain gzip code in _bgzf.c_ was plugged in in the wrong place, and that 64K blocking has led to various plain gzip bugs in the past.
