### ISSUE TITLE
inconsistent behavior in `bcf_remove_allele_set` can lead to malformed GT fields

### ISSUE THREAD

**Issue by CreRecombinase** [samtools/htslib#1259]
Consider the file:
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##reference=file://some/path/human_g1k_v37.fasta
##contig=<ID=22,length=51304566>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE1	SAMPLE2	SAMPLE3
22	16051457	.	A	G,C	3.42882	PASS	.	GT	0/1	0/2	0/1
```

if we call `bcf_remove_allele_set` to remove the `G` allele, we end up with: 

```
22	16051457	.	A	C	3.42882	PASS	.	GT	0/0	0/1	0/0
```

as an aside I feel like ideally it should be replaced by something like: 
```
22	16051457	.	A	C	3.42882	PASS	.	GT	./0	0/1	./0
```
but let's set that aside for now.  If we try to remove the `C` allele, the GT fields are entirely unchanged, this leaves the  `2` referring to nothing :
```
22	16051457	.	A	G	3.42882	PASS	.	GT	0/1	0/2	0/1
```
I believe this is because the `if ( i<line->n_allele )` [on line 500 of vcfutils.c](https://github.com/samtools/htslib/blob/9672589346459d675d62851d5b7b5f2e5c919076/vcfutils.c#L500) doesn't take into account that `n_allele` is updated by a call to `bcf_update_alleles_str` [on line 283](https://github.com/samtools/htslib/blob/9672589346459d675d62851d5b7b5f2e5c919076/vcfutils.c#L283) (i.e it should be `if (i<nR_ori)` instead?).  I'd make a pull request but I'm not 100% sure that's what's going on here.

Thanks!

**Comment by pd3** [comment]
I think the function assumes that only unseen alleles are deleted and uses this assumption to make some shortcuts. Therefore it should be extended to deal with such cases. And yes, it probably makes sense to replace with a missing value.
