### ISSUE TITLE
Are buffers for bam1_t data required to be zeroed or are they safe to reuse?

### ISSUE THREAD

**Issue by jcasc** [samtools/htslib#1263]
In the example given regarding the BAM_USER_OWNS_DATA flags in sam.h, calloc is used to allocate the buffer.

Is the data buffer required to be zero'd or can it be used for other bam1_t structs' data at a later point without reinitialization?

**Comment by valeriuo** [comment]
Since the `bam1_t` is publicly exposed, it can be accessed directly or through the API, so the answer to your question mostly depends on this aspect. API methods that modify the record, such as `bam_read1()` and `bam_set1()`, take care of resizing the memory and setting the proper lengths and flags. For a single record, initialization can be done with `bam_init1()`, which is just an API wrapper over `calloc`.

**Comment by jcasc** [comment]
Thanks for your response. However,  am referring specifically to the the case that a manually managed buffer is used for a bam1_t whose storage is also managed manually.
For example, If I was using both BAM_USER_OWNS_DATA and BAM_USER_OWNS_STRUCT like this:

```
auto buf = std::array<uint8_t, BUF_SIZE>{}; // zero-initialization neccessary or are indeterminate values ok?
bam1_t b1;
sam_set_mempolicy(&b1, BAM_USER_OWNS_STRUCT | BAM_USER_OWNS_DATA);
bam1_t.data = buf.data();
bam1_t.m_data = BUF_SIZE;
bam_set1(&b1,....) // assume data fits and BAM_USER_OWNS_DATA still set
// do something like sam_write1(my_fp, my_hdr, &b1)
bam_destroy1(&b1); // won't actually do anything, i presume

// can I now safely do the following?
bam1_t b2;
bam1_t.data = buf.data(); // reuse same buffer for different bam1_t without zeroing or reallocation.
bam1_t.m_data = BUF_SIZE;
// ...
```

The reason why I'm wondering about this is because in the example for the OWNS_DATA flag, calloc was used to initialize the buffer, which lead me to assume that maybe internally, the bam_set1 and bam_write1 are requiring the memory pointed to by the bam1_t::data pointer member to be zero, which in turn would mean that I would have to memset it before reusing it for another bam1_t's data.

**Comment by jcasc** [comment]
I just realized that malloc *is* actually used for the buffer, so presumably indeterminate values are fine. I'm sorry. I must have misread that.

**Comment by valeriuo** [comment]
> `bam_destroy1(&b1); // won't actually do anything, i presume`

Correct.

>
```c
// can I now safely do the following?
bam1_t b2;
b2.data = buf.data(); // reuse same buffer for different bam1_t without zeroing or reallocation.
b2.m_data = BUF_SIZE;
// ...
```

Yes, but you should also set the used length of the data buffer to 0.
`b2.l_data = 0;`

**Comment by jcasc** [comment]
Oh, I meant to 0-initialize b1, and b2 of course, and have edited the comment.
Thanks for your response and for clarifying this.
