### ISSUE TITLE
BAM subsetting broken in 1.12

### ISSUE THREAD

**Issue by dancooke** [samtools/htslib#1279]
Subsetting appears to be broken in htslib 1.12. In particular, reads are being missed when the target region is too large:

```shell
$ samtools version | head -2
samtools 1.12
Using htslib 1.12
$ samtools view mybam.bam 13:23907893-23907932 | wc -l
87
$ samtools view mybam.bam 13:16907893-23907932 | wc -l
1750673
$ samtools view mybam.bam 13:15907893-23907932 | wc -l
0
```

The problem does not occur with 1.11:

```shell
$ samtools 2>&1 >/dev/null | head -3

Program: samtools (Tools for alignments in the SAM format)
Version: 1.11 (using htslib 1.11)
$ samtools view mybam.bam 13:15907893-23907932 | wc -l
2124456
```

This is with Conda installed samtools/htslib on Linux but I see the same issue on MacOS with Homebrew installed samtools/htslib. I'm confident this is a htslib issue as I also see the same behaviour in my tool [octopus](https://github.com/luntergroup/octopus) that directly calls htslib.

**Comment by dancooke** [comment]
Also confirmed the problem on latest develop branch building from source on MacOS with Clang 12.0.

**Comment by dancooke** [comment]
I've made a reduced test case: [debug.bam](https://www.dropbox.com/s/28qa34kll9uic87/debug.bam?dl=1) ([debug.bam.bai](https://www.dropbox.com/s/cz8965ehes7xvzv/debug.bam.bai?dl=1)). e.g.:

```shell
$ samtools view debug.bam chr22:15836198-15836198 | wc -l
18
$ samtools view debug.bam chr22:0-15836198 | wc -l
0
```

**Comment by dancooke** [comment]
Reverting 49059d3cbb1ac145fadbafed18bce2a8eb5dc0d9 from @valeriuo and @jkbonfield restores normal function.

**Comment by jkbonfield** [comment]
Thanks for the report, research and test data for this one.  An important bug to fix.
