### ISSUE TITLE
Another gcc 11.1 issue

### ISSUE THREAD

**Issue by jkbonfield** [samtools/htslib#1283]
Not exercised by this library, but by samtools instead, kseq.h also trips up the new gcc 11.1 compiler.

```
gcc11 -g -Wall -O2 -I. -I../htslib -I./lz4  -c -o dict.o dict.c
In file included from dict.c:32:
In function 'kseq_read',
    inlined from 'write_dict' at dict.c:73:17,
    inlined from 'dict_main' at dict.c:176:5:
../htslib/htslib/kseq.h:212:40: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  212 |                 seq->seq.s[seq->seq.l] = 0;     /* null terminated string */ \
      |                 ~~~~~~~~~~~~~~~~~~~~~~~^~~
../htslib/htslib/kseq.h:237:9: note: in expansion of macro '__KSEQ_READ'
  237 |         __KSEQ_READ(SCOPE)
      |         ^~~~~~~~~~~
../htslib/htslib/kseq.h:239:35: note: in expansion of macro 'KSEQ_INIT2'
  239 | #define KSEQ_INIT(type_t, __read) KSEQ_INIT2(static, type_t, __read)
      |                                   ^~~~~~~~~~
dict.c:35:1: note: in expansion of macro 'KSEQ_INIT'
   35 | KSEQ_INIT(gzFile, gzread)
      | ^~~~~~~~~
dict.c: In function 'dict_main':
../htslib/htslib/kseq.h:210:45: note: at offset -2 into destination object of size 0 allocated by 'realloc'
  210 |                         seq->seq.s = (char*)realloc(seq->seq.s, seq->seq.m); \
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../htslib/htslib/kseq.h:237:9: note: in expansion of macro '__KSEQ_READ'
  237 |         __KSEQ_READ(SCOPE)
      |         ^~~~~~~~~~~
../htslib/htslib/kseq.h:239:35: note: in expansion of macro 'KSEQ_INIT2'
  239 | #define KSEQ_INIT(type_t, __read) KSEQ_INIT2(static, type_t, __read)
      |                                   ^~~~~~~~~~
dict.c:35:1: note: in expansion of macro 'KSEQ_INIT'
   35 | KSEQ_INIT(gzFile, gzread)
      | ^~~~~~~~~
```

This ugly mess of macro warnings (which it does a reasonable job of untangling actually), boils down to it not knowing that seq.l < seq.m so it thinks it can overflow the buffer.

It's possibly due to the use of `kroundup32` confusing it.  It doesn't know what's happening there, even if we explicitly use the kroundup.h copy to guarantee it doesn't decrease or overflow.

A trivial bit of compiler education is to put a code path in that handles this case and die.  If this code is ever reached, something terrible has gone wrong, such as the `seq->seq.l + 2` wrapping around.  Frankly once we're doing that we're way outside the parameters of what sensible behaviour is already and crashing and burning is probably appropriate (at least that doesn't constitute buffer overruns or nasty security issues).

What do we feel about something like this?  (I was tempted by abort() given it would have gone bang with a core dump anyway...)

```
diff --git a/htslib/kseq.h b/htslib/kseq.h
index ee13dd0..307486f 100644
--- a/htslib/kseq.h
+++ b/htslib/kseq.h
@@ -207,6 +207,7 @@
                if (seq->seq.l + 1 >= seq->seq.m) { /* seq->seq.s[seq->seq.l] below may be out of boundary */ \
                        seq->seq.m = seq->seq.l + 2; \
                        kroundup32(seq->seq.m); /* rounded to the next closest 2^k */ \
+                       if (seq->seq.l < seq->seq.m) return -3; \
                        seq->seq.s = (char*)realloc(seq->seq.s, seq->seq.m); \
                } \
                seq->seq.s[seq->seq.l] = 0;     /* null terminated string */ \
```

The entire code is missing far more common causes of errors, like running out of memory, but that's a topic for another day.

**Comment by jmarshall** [comment]
Looks like a good idea to me. Not sure that's the right way around, and it would be good to repeat the guard conditional:

```c
```

**Comment by jmarshall** [comment]
Looks like a good idea to me. Not sure that's the right way around, and it would be good to repeat the `l`/`m` guard conditional from just above:

```c
+    if (seq->seq.l + 1 >= seq->seq.m) return -3; /* error: adjusting m overflowed */ \
```

**Comment by daviesrob** [comment]
We actually got rid of the `kroundup` in kstring in e1d314931f on the grounds that it expanded to a lot of code, had issues with overflow and wasted a lot of space in the strings.  Couldn't we replace most of the above with this?
```c
   if (ks_expand(seq->seq, 2) < 0) return -3;
   seq->seq.s[seq->seq.l] = 0;
```

`ks_expand()` already knows about the possibility of overflow.  Also, do we really need to expand by 2, or would 1 do?

**Comment by jkbonfield** [comment]
Ah wait a moment, no this doesn't work.  It's totally the wrong function.

`ks_expand` expands the buffer by 2 for each and every sequence.  The old code simply ensured it was large enough by checking l vs m.  This permits it to keep reusing the same buffer.

**Comment by jmarshall** [comment]
All the other mallocing and reallocing is inline in the `#defines` and ends up inline in your application code. Won't changing one of the paths to use a function inside _libhts.dll_ screw up the Windows separate-memory-arenas crowd?

**Comment by jkbonfield** [comment]
That's a good point too.  I reverted my implementation of Rob's suggestion and went back to what I had before.  I'll make a PR for it in a mo.

**Comment by daviesrob** [comment]
@jkbonfield Look at the code.  `ks_expand()` is a [thin wrapper](https://github.com/samtools/htslib/blob/2b682671/htslib/kstring.h#L169) around `ks_resize()`, which [does check against `m`](https://github.com/samtools/htslib/blob/2b682671/htslib/kstring.h#L150).  It will not resize the buffer unless it needs to.

@jmarshall `ks_resize()` is a static inline which does the realloc.  It no longer calls into libhts.dll.  That was actually the main point of the change in commit e1d314931fe.

**Comment by jmarshall** [comment]
Good point. I had neglected to check whether the functions being talked about were themselves inline too, or how this had been previously fixed in that commit.

So I will fall back to my previously unstated opinion: _kseq.h_ should die in a :fire: so the minimal change is indicated :smile:

**Comment by jkbonfield** [comment]
> @jkbonfield Look at the code. `ks_expand()` is a [thin wrapper](https://github.com/samtools/htslib/blob/2b682671/htslib/kstring.h#L169) around `ks_resize()`, which [does check against `m`](https://github.com/samtools/htslib/blob/2b682671/htslib/kstring.h#L150). It will not resize the buffer unless it needs to.

Duh! So it does.

What a terribly named function in that case.  Anyway,  I have made the PR already.  You can either accept it or replace it with your own - it's pointless modifying it as every single line would be removed and replaced by new ones. :)
