### ISSUE TITLE
Does samFile has some function like fseek?

### ISSUE THREAD

**Issue by LambertZhaglog** [samtools/htslib#1287]
I want handle sam/bam file with multi-thread. My server has 64 cores. thread_pool can help decode sam file with multi-thread, but it can only use 6 core. If I can fseek sam file to somewhere and decode from there, I can fully use my 64 cores by using 64 thread, every thread open sam file but seek to different position and decode from there.
Does htslib have some utility to do this, or combine some function  to do this, how to do ?

**Comment by valeriuo** [comment]
There is `bgzf_useek` for BGZF compressed files or low-level `hseek`. `hts_useek` blends these two together. Unfortunately it is not a public method. Presumably, you want to open the file in each thread and map a different file offset to a different core.

**Comment by LambertZhaglog** [comment]
Thanks for your help @valeriuo
