### ISSUE TITLE
samtools index a.bam when a.cram is present overwrites a.cram.crai?

### ISSUE THREAD

**Issue by isthisthat** [samtools/htslib#1294]
Something strange happened (samtools 1.11):
In a folder containing:
`a.cram`
`a.cram.crai`
I ran `samtools view -b -T ref.fa -o a.bam a.cram`
Then `samtools index a.bam`
The last command overwrote the existing `a.cram.crai` with a zero-byte file and then produced `a.bam.bai`
Has anyone else noticed this?

**Comment by jkbonfield** [comment]
I cannot reproduce this (1.12, but doubt we changed that).

Are you certain samtools index is doing this?  You can see what it's doing using something like `strace`.  Eg:

```
$ strace samtools index a.bam 2>&1 | egrep 'a\.(b|cr)am'
execve(".../bin/samtools", ["samtools", "index", "a.bam"], 0x7fffa351ccb0 /* 85 vars */) = 0
openat(AT_FDCWD, "a.bam", O_RDONLY)     = 3
openat(AT_FDCWD, "a.bam.bai", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 4

$ ls -l a.*
-rw-r--r-- 1 jkb team117 130680 Jun  4 09:25 a.bam
-rw-r--r-- 1 jkb team117    816 Jun  4 09:26 a.bam.bai
-rw-r--r-- 1 jkb team117  77972 Jun  4 09:24 a.cram
-rw-r--r-- 1 jkb team117     52 Jun  4 09:24 a.cram.crai
```

**Comment by isthisthat** [comment]
Thanks @jkbonfield. Let me do a bit more digging and get back to you. I'll try to produce a minimal example if I can.

**Comment by isthisthat** [comment]
closing since I haven't been able to reproduce.
