### ISSUE TITLE
GCE implementation with user pays buckets

### ISSUE THREAD

**Issue by migrau** [samtools/htslib#1313]
I am trying to read remotely a CRAM file stored in a GCE bucket that is configured as user pay:

```
(google-cloud) mgrau@z25:~$ samtools view -H gs://bucket_name/file.cram
[E::hts_open_format] Failed to open file "gs://bucket_name/file.cram" : Invalid argument
samtools view: failed to open "gs://bucket_name/file.cram" for reading: Invalid argument
```

And with `--verbosity`, these are the last lines:

```
authorization: Bearer < my GCS_OAUTH_TOKEN >

* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 400 
< x-guploader-uploadid: ADPycdu-ouZqyc1jYHhl__xxxxx
< content-type: application/xml; charset=UTF-8
< content-length: 266
< date: Tue, 03 Aug 2021 16:25:01 GMT
< expires: Tue, 03 Aug 2021 16:25:01 GMT
< cache-control: private, max-age=0
< server: UploadServer
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<
* Connection #0 to host bucket_name.storage-download.googleapis.com left intact
[main_samview] fail to read the header from "gs://bucket_name/file.cram".
```

I tried using the `GCS_REQUESTER_PAYS_PROJECT=my-project-name` option (as explained [here](https://github.com/samtools/htslib/issues/993) and [here](https://github.com/samtools/htslib/pull/1255)) but I end up with the same error: `Invalid argument`. I tried with project-name and project-id with same result.

**Comment by migrau** [comment]
Yes

**Comment by migrau** [comment]
@whitwham, appreciate your help. Is it actually possible reading remotely a CRAM file stored in a GCE bucket that is configured as user pay?

**Comment by whitwham** [comment]
@migrau It should be.

Give it a try with a simpler program.   See what kind of result you get with htsfile. e.g.
`htsfile --copy gs://my_bucket/myfile.file myfile_local.file`

**Comment by daviesrob** [comment]
You might want to try `htsfile -vvvvvvvv --copy gs://my_bucket/myfile.file myfile_local.file`

Turning the verbosity up high enough [disables fail-on-error](https://github.com/samtools/htslib/blob/7ba9ecd7/hfile_libcurl.c#L1260) in `hfile_libcurl`, which means there's a chance that the error response text from Google will be saved in the local file.  That might give a few clues about what the problem is.

`hfile_s3` [always disables fail-on-error](https://github.com/samtools/htslib/blob/7ba9ecd79/hfile_s3.c#L1192) so it can better handle 400 responses.  It might be worth doing something similar in `hfile_gcs`.

**Comment by daviesrob** [comment]
Hopefully you got this to work.  Please re-open if not.

**Comment by SHuang-Broad** [comment]
If anyone found this ticket looking for a solution, just do the following export before your typical samtools command (if you come from samtools)

```bash
export GCS_OAUTH_TOKEN=`gcloud auth application-default print-access-token`
export GCS_REQUESTER_PAYS_PROJECT="<fill_in_your_gcp_project_here>"
```

the source is this line of code: https://github.com/samtools/htslib/blob/a6a6350ec24c043dad6d12d213e7e62d8f2d93fe/hfile_gcs.c#L85
