### ISSUE TITLE
htslib version update

### ISSUE THREAD

**Issue by dnarna2108** [samtools/htslib#1318]
Hi, 

I tried to update the version of htslib (1.9 > 1.13), and downloaded the latest version of files following the instruction at http://www.htslib.org/download/.

But when I check the version of bgzip (bgzip --version), tabix (tabix --version), it still appears as verion 1.9.

Is there any other further step needed to get updated version of htslib, bgzip, tabix ?

Thanks in advance.

**Comment by valeriuo** [comment]
Did you run `make install`?
What do `which bgzip` and `which tabix` show? Is this the intended install path?
Most likely, the 1.9 executables are in a folder that has higher precedence in the `PATH` list than the 1.13 executables.

**Comment by daviesrob** [comment]
Assuming you found the 1.13 binaries, we're closing this.  Please reopen if you're still having trouble.
