### ISSUE TITLE
Improper locking bugs(e.g., deadlocks) on the lock

### ISSUE THREAD

**Issue by ryancaicse** [samtools/htslib#1329]
Hi, developers, thank you for your checking. It seems the lock `fd->refs->lock` is not released correctly when `start < 1 `in the function `cram_get_ref`?

https://github.com/samtools/htslib/blob/575db47d185481fdaec0dfab45a6bbf99f8e123e/cram/cram_io.c#L3419-L3443

Best,

**Comment by ryancaicse** [comment]
Also, for the lock `fd->ref_lock`
https://github.com/samtools/htslib/blob/575db47d185481fdaec0dfab45a6bbf99f8e123e/cram/cram_io.c#L3375

**Comment by jkbonfield** [comment]
Thanks for the bug report.  It looks like a real issue.

I'm curious if you tripped over this with real data.  I don't believe start should ever be < 1 on valid files, which is likely why we've never triggered it, but as we have an error case where we bail out here then we should also free the locks.

**Comment by ryancaicse** [comment]
@jkbonfield Thanks. 
They are found by code scan. Yes, it looks like, the programs come to the corner cases where the locks are not released properly.

**Comment by daviesrob** [comment]
@ryancaicse Out of interest, what did you use to find this?

**Comment by ryancaicse** [comment]
@daviesrob Thank you for your interest. I used [Pinpoint.](https://www.sourcebrella.com/) Its code technique could be found [here.](https://dl.acm.org/doi/10.1145/3192366.3192418)

**Comment by daviesrob** [comment]
Thanks, I'll take a look.
