### ISSUE TITLE
Compiler error in htscodecs.c

### ISSUE THREAD

**Issue by ellliott** [samtools/htslib#1346]
Hi @jkbonfield I hope this finds you well. I'm new to `samtools` and `htslib` but I'm currently trying to install ANGSD using the following docs (http://popgen.dk/angsd/index.php/ANGSD) and when I run the htslib make command I receive the following error:

```
...
gcc -g -Wall -O2 -fvisibility=hidden -I.  -c -o htscodecs/htscodecs/htscodecs.o htscodecs/htscodecs/htscodecs.c
htscodecs/htscodecs/htscodecs.c:43:12: error: use of undeclared identifier 'HTSCODECS_VERSION_TEXT'
    return HTSCODECS_VERSION_TEXT;
           ^
1 error generated.
make: *** [htscodecs/htscodecs/htscodecs.o] Error 1
```

I wondered is `HTSCODECS_VERSION_TEXT` a variable I need to define and pass or should this be set in my environment. Any help you can provide would be greatly appreciated.

**Machine**
macOS Big Sur
Apple M1
**ANGSD**
angsd0.934.tar.gz

**Comment by jkbonfield** [comment]
This is an issue for @angsd to solve.

The angsd0.934.tar.gz tar ball (note not gzipped, so incorrect filename) contains its own bundled copy of htslib (which is a clone somewhere between 1.11 and 1.12).  This appears to be in error.  I don't know if ANGSD has modified it in any way, but if so it would be better to rename the package so as not to confuse people.  You could try simply deleting that directory and putting htslib 1.13 from the release tarball in its place instead.

**Comment by jkbonfield** [comment]
Alternatively, you can fix it by creating an htscodecs/htscodecs/version.h file.  It looks like the Makefile attempts to do this, but for some reason doesn't work.  Try:

```
echo '#define HTSCODECS_VERSION_TEXT "1.0"' > htscodecs/htscodecs/version.h
```

from within the htslib directory.

Our own tarball releases already include this file.  I suggest angsd should do the same, if it wishes to bundle its own release tarballs of htslib.  It'd also be good if it stuck to official release tags too.

(Note for me angsd still didn't build after doing this, failing with libcrypto errors.  It needed `make HTSSRC=../htslib CRYTOLIB=` to negate that.)

**Comment by ellliott** [comment]
Thanks @jkbonfield appreciate the effort and help in trying to debug this. I'll follow the steps you recommend above and see if I can get pass angst's build errors. Thanks again - enjoy your day!
