### ISSUE TITLE
vcfutils::bcf_remove_allele_set should unpack to BCF_UN_INFO

### ISSUE THREAD

**Issue by brentp** [samtools/htslib#1353]
`bcf_remove_allele_set` currently checks that the record is unpacked up to `BCF_UN_STR`, but it later modifies the INFO fields with Number=A, R, or G. So it should unpack up to `BCF_UN_INFO`.

https://github.com/samtools/htslib/blob/9045785cef02e7cd97b0b4caecbdcaf6217a986a/vcfutils.c#L262

**Comment by brentp** [comment]
Actually it's modifying GT as well so BCF_UN_FMT is needed too.

**Comment by pd3** [comment]
I believe `bcf_get_info_values()` and `bcf_get_genotypes()` take care of unpacking. Did you spot any problems with using the code or just came to this conclusion by reading the sources?

**Comment by brentp** [comment]
indeed, I get a segfault that goes away with unpack.

**Comment by brentp** [comment]
I think it's that you can get to here: https://github.com/samtools/htslib/blob/c5b815c31e9b2f06c7484f534bad609c76b3c15d/vcfutils.c#L302

without unpacking info so d.info is still null?

**Comment by pd3** [comment]
Ah, you are right, indeed. Thanks for bringing this up, will fix
