### ISSUE TITLE
The unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by comatosejones** [samtools/htslib#1376]
No longer able to pull updates when using SSH to connect to my servers.

**Comment by jmarshall** [comment]
Try again tomorrow: https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective

**Comment by jkbonfield** [comment]
Or better still, upgrade your SSH keys to not be using one of the deprecated DSA or RSA/SHA-1 protocols listed.  Thanks John for the documentation.

I'm closing this though as it's not an htslib issue.

**Comment by comatosejones** [comment]
I may be an idiot, but following the steps on github is not working for me.
