### ISSUE TITLE
cram_io.h error

### ISSUE THREAD

**Issue by wuyunqiq** [samtools/htslib#1382]
when I call the cram_io.h, I got error below:

*/htslib/cram/cram_io.h: In function ‘int block_resize_exact(cram_block*, size_t)’:
*/htslib/cram/cram_io.h:217:33: error: invalid conversion from ‘void*’ to ‘unsigned char*’ [-fpermissive]
     unsigned char *tmp = realloc(b->data, len);

I want to know how to solve it.

**Comment by jkbonfield** [comment]
What compiler are you using?

Also, how are you including this?  Is it simply building htslib, or are you attempting to include this (internal) file directly from your own program?  (If so, it's not intended for use that way, but if we have missing dependencies in the include file then we should still fix them.)

**Comment by jkbonfield** [comment]
Closing this as no reply and I suspect it's due to the inappropriate use of a C++ compiler on internal headers (C permits realloc to be assigned to any pointer type).
