### ISSUE TITLE
Interface with htslib.a

### ISSUE THREAD

**Issue by fredjarlier** [samtools/htslib#1385]
Hi guys,
I have a little question for you. I would like to stream memory with create_hfile_mem in my project but it does not appear in the headers after installation is it normal? do you plan to expose some internals in the future ? 
Best
fred

**Comment by jkbonfield** [comment]
This is an internal function and we don't have plans to make it public.

The official way to do this is via the mem: URI.  This can be called directly via external tools.  See https://github.com/samtools/htslib/blob/develop/test/hfile.c#L216-L244 for examples.

**Comment by fredjarlier** [comment]
thanks very much. Exactly what I was looking for.
