### ISSUE TITLE
CRAM with relative path to reference

### ISSUE THREAD

**Issue by lczech** [samtools/htslib#1401]
Hello!

I was wondering if CRAM files support relative paths to the fasta/fai reference files. I have only found [this thread](https://bioinformatics.stackexchange.com/questions/4836/can-i-create-a-cram-file-with-a-relative-reference-path), which also mentions to get in contact with the htslib team, hence I am writing here. If this is better suited as a samtools issue, please let me know!

The problem is relatively simple: I am using the [samtools example file](https://github.com/samtools/samtools/tree/develop/examples) for my code's unit testing, and also converted it to cram:

    samtools faidx ex1.fa
    samtools view -S -C -t ex1.fa.fai -o ex1.cram ex1.sam.gz

But that won't work unless the files are in the paths where this was executed - which they won't be if a user of my code wants to run the unit tests on their machine.

Is there a solution to this?
Thanks in advance
Lucas

**Comment by daviesrob** [comment]
It is possible to convert a SAM file with a relative path in it, but when you use it the path is taken relative to the current working directory.  It isn't possible to specify a location relative to the CRAM file at the moment, which is I guess what you want?

For our tests, we include the reference file, and either make the CRAMs from SAM files, which embeds the absolute path of the reference when the test is run; or we store the reference in a file named after the sequence MD5 and access them via `REF_PATH`.  For the latter method, HTSlib's `test.pl` script [creates a cache](https://github.com/samtools/htslib/blob/3e6f13c2/test/test.pl#L308) from the `test/ce.fa` file, and then [sets `REF_PATH`](https://github.com/samtools/htslib/blob/3e6f13c2/test/test.pl#L818) to the directory it created before running some of the CRAM-related tests.
