### ISSUE TITLE
Feature Request: Expose the total length of a contig

### ISSUE THREAD

**Issue by svetlin-mladenov** [samtools/htslib#1404]
The current API for indexed files (like Tabix, CSI) allows for retrieving the list of contigs and iterating over all the records for a contig but does not expose the total length of a contig. The only way to get it at the moment is (as far as I can tell) to just iterate over all the records and get the position of the last one which is obviously slow. An API that exposes the total length of a contig would be useful in the following cases:

1. Splitting the contig into equal size regions and processing each region in parallel.
2. Better debug and error messages.
3. Progress bars - knowing the number of the current record and the total number of records allows for nice progress bars.

Cheers,
Svetlin

**Comment by whitwham** [comment]
I'm not sure what you mean by length of the contig?

If number of bases then that information should be in the header.
If number of reads then I think you can find that through the index API.
