### ISSUE TITLE
Samtools MPileup : [E::Incorrect %s tag type (%c) for read %s]

### ISSUE THREAD

**Issue by GasparQ** [samtools/htslib#1405]
Hello,

Somebody I know used the command `samtools mpileup` and get the following error:
```
[E::Incorrect %s tag type (%c) for read %s] ZQ
```

Despite the fact that command inputs might be invalid, the error message is invalid itself and do not give a clear understanding of the problem.

After few researches, I found that the call to `hts_log` is invalid in the function `realn_check_tag` of the file `realn.c`.

Here the function `hts_log` is called with 5 arguments:
- severity
- format string
- 3 format parameters

```C
static int realn_check_tag(const uint8_t *tg, enum htsLogLevel severity,
                           const char *type, const bam1_t *b) {
    if (*tg != 'Z') {
        hts_log(severity, "Incorrect %s tag type (%c) for read %s",
                type, *tg, bam_get_qname(b));
        return -1;
    }
    if (b->core.l_qseq != strlen((const char *) tg + 1)) {
        hts_log(severity, "Read %s %s tag is wrong length",
                bam_get_qname(b), type);
        return -1;
    }
    return 0;
}
```

However, the `hts_log` function prototype takes the following arguments:
- severity
- context
- format
- variadic parameters...

```C
void hts_log(enum htsLogLevel severity, const char *context, const char *format, ...)
```

So in the call of `realn_check_tag`, the format string is passed as the `context` parameter which is print inside the `[]` of the error instead of being written at the end of the message.

It means that, in our case, the `type` variable is passed as a format string, and is displayed after the `[]`.

In my present case, it prints `ZQ` and other parameters are ignored.

It is not only a misuse of `hts_log` which lead to unconsistent errors but also _(if parsing checks are not totally well performed)_ a security breach that can be used to insert a custom format string through a sam/bam file to access invalid memory blocks thanks to the variadic parameters.

I would suggest to check to all the calls of `hts_log` in the project and correct them to fix this issues.

Regard

**Comment by daviesrob** [comment]
Yes, `hts_log` is being called incorrectly here.  I'll ensure it gets fixed.

**Comment by GasparQ** [comment]
Thank you very much for your reactivity 🙂

**Comment by jmarshall** [comment]
`-Wformat=2` would have caught this issue. It may be worth turning this on in a (GCC-based) CI job — but see #1407.
