### ISSUE TITLE
failed to use libdeflate in htslib

### ISSUE THREAD

**Issue by HatakeKakaxi** [samtools/htslib#1413]
I want to use htslib with libdeflate in Ubuntu now. I have installed libdeflate in a standard localization (/usr/local). When I run `./configure --with-libdeflate`, it shows 
```
checking for libdeflate.h... yes 
checking for libdeflate_deflate_compress in -ldeflate... yes
```
However, when I use `ldd libhts.so` to check for dependencies, it shows 
` libdeflate.so.0 => not found `. 
Why does this happen? Can anyone help me?

**Comment by jkbonfield** [comment]
I assume this means you don't have /usr/local/lib in your LD_LIBRARY_PATH environment variable.  You'll need to add it as while it's a reasonable standard location, it's not typically searched in by default.

**Comment by daviesrob** [comment]
If your copy of Ubuntu is focal (20.04) or newer, you can get libdeflate simply using `apt install libdeflate-dev`.

For the library you built, you may just need to update the dynamic linker cache file to allow it to be found without setting LD_LIBRARY_PATH.  You can do this by running `ldconfig` as root.

**Comment by HatakeKakaxi** [comment]
> I assume this means you don't have /usr/local/lib in your LD_LIBRARY_PATH environment variable. You'll need to add it as while it's a reasonable standard location, it's not typically searched in by default.

I got it. Thank you.

**Comment by HatakeKakaxi** [comment]
> I assume this means you don't have /usr/local/lib in your LD_LIBRARY_PATH environment variable. You'll need to add it as while it's a reasonable standard location, it's not typically searched in by default.

I got it. Thank you.
