### ISSUE TITLE
Index of aux tag in sam/bam record

### ISSUE THREAD

**Issue by lczech** [samtools/htslib#1417]
Hi there,

I would like to separate reads in a `bam_pileup1_t` by their RG aux tag (Is "aux" or "tag" the correct word here? htslib seems to use both). I found the following solution (simplified):

    bam_pileup1_t const* p = ...;
    uint8_t* tag = bam_aux_get( p->b, "RG" );
    char* rg = bam_aux2Z( tag );

to get the actual name of the RG. However, I do not need the name; I merely want to use it to distinguish reads by RG, so all I need is some form of index or indicator. The above solution however seems rather slow, and additionally requires me to go via a string lookup from `rg` to my final index (which I based on indexing the RG list as obtained from the header).

Is there a way to instead retrieve some kind of index of the RG instead?

Looking at

    char *bam_aux2Z(const uint8_t *s)
    {
        int type;
        type = *s++;
        if (type == 'Z' || type == 'H') return (char*)s;
        errno = EINVAL;
        return 0;
    }

and from what I understand about the data blob of `bam1_t`, it seems to me that the `tag` variable of my above example is some very convoluted type with lots of casting in the background, so I am not sure how to properly turn it into a simple index, where (for example) 0 is the first RG tag in the header, 1 the second, etc...

Thanks in advance and so long
Lucas

**Comment by lczech** [comment]
Update: 

I did some more experimentation, and apparently, just calling `bam_aux_get` and `bam_aux2Z` is already most of the runtime of my function to get the RG, with the string lookup being negligible. 

Hence, I guess that solving this issue would not gain me much, unless there is some better way of just getting an index or some other stable number for the RG of each read. If not, this issue can be closed ;-) 

Thanks
Lucas

**Comment by jkbonfield** [comment]
Firstly I think the original SAM paper just used the name "tag", but you are correct we often call then aux tags (auxilliary tags) in the code.

As to the question, the tags in BAM are just serialised {name,type,data} tuples.  There is no idex there so the only way to find a specific tag is to linearly search.  Granted there could be some mileage in indexing in a hash table (I think htsjdk does this), but only if looking for multiple tag names in the same record, otherwise it's simply overhead.  BAM does not turn these strings into dictionary lookups.  (CRAM however does store RG differently, as a link to the Nth RG header field, but this isn't exposed to the public htslib API.)   Hence finding a tag can be a time consuming operation if there are many or long tag fields present in a record (although it'll be fast if they occur at the start of the list instead of the end, which may be something to consider if you control this).

The `sam_hdr_find_line_id` can use a hash table built from the `@RG` lines to turn the RG string into a numeric value (the Nth RG record).  That should be quite a quick operation.

**Comment by lczech** [comment]
Thank you very much for the quick answer! 

I see, so when reading sam/bam, htslib just stores the tags more or less unprocessed (except for the parsing itself) in the data blob. That makes sense, in order to save processing time if that data is not needed - and so now that I need to access it, I need to pay the extra cost of reading through it to find the tag I'm looking for. Sounds reasonable. All right, then my solution seems to be as efficient as possible :-)

**Comment by jkbonfield** [comment]
Out of interest, are you input files BAM or CRAM?

Technically CRAM could short-cut some of this by adding to an index during decode as all the separate tags come from separate data-series anyway and get serialised together, but so far there's not been a need and internally (mainly for historical reasons) all sequence data is held in memory as BAM.

Although decoding CRAM is a higher CPU cost anyway, in which case the overhead of searching is probably no longer the dominant issue anyway.

**Comment by lczech** [comment]
I'm writing this as part of a C++ wrapper in my library (see [here](https://github.com/lczech/genesis/blob/master/lib/genesis/population/formats/sam_variant_input_iterator.hpp)), which is intended to work with all SAM/BAM/CRAM files. That seems to work (as far as I have tested), because thankfully htslib takes care of all three formats internally already ;-)
The wrapper simply turns these files into nucleotide counts per position (potentially a separate set of counts for each RG, hence my request here), using `bam_plp_auto` to go through all reads at a position.

Given how I iterate the data, that unfortunately means that the RG tag has to be determined for each position of each read again and again... but trying to add some bookkeeping to only do that once would make my code way more complex, so I'm refraining from that idea for now.

Hence, and given that the internal structure is BAM anyway, I think my current way of finding the RG tag per read is good enough - thank you though for your quick reply and helpful insights!

**Comment by jkbonfield** [comment]
Ah I see.

You can cache things like the RG per record.   This will almost completely remove the overhead you see. You get an array of `bam_pileup1_t` objects which internally have `bam_pileup_cd cd` as a structure member.  "cd" means client-data; where the client is you.  Basically it's somewhere for you to stash whatever data you wish and it'll be carried along between successive pileup calls.  This value is a union of pointer, integer or double.

For simple non-allocated things (a single number) this is easy to initialise, as it is also for something that you don't allocate yourself such as the RG pointer.  For anything more complex, you need to use the constructor and destructor functions which were added in v1.4 (88517dfc50c932bb7213c6bbb4a15450e0a5c812).  The various `plp` interfaces call the constructor on each new BAM object added to the pileup, and the destructor once it goes out of scope.

As these interfaces didn't used to exist, their usage isn't very wide spread in our code.  However examples of usage can be seen here:

https://github.com/samtools/samtools/blob/develop/bam_plcmd.c#L554-L557
https://github.com/samtools/samtools/blob/develop/bam_plcmd.c#L336-L351
https://github.com/samtools/samtools/blob/develop/bam_plcmd.c#L76

This should allow you to cache information as each new record arrives, and tidy it up in a clean and safe manner.

**Comment by lczech** [comment]
Oh wow, I am glad that I asked, and I am very grateful for your thorough and helpful answer, thank you very much! Indeed, using the `bam_pileup_cd` to cache an index of the RG tag (simply using the `i` field of the union), the runtime only increased by 5% compared to when not splitting by RG, instead of 500% that it was before.

Thank you very much again, that was super helpful!

PS: As a side note, the way that `bam_pileup_cd` is currently defined, as a typedef'ed anonymous union, I could not forward declare it, and hence had to use a bit of trickery to avoid pulling htslib headers into my headers. Not a big issue, but might be worth giving that union (as well as other types) a proper name in future releases ;-)
