### ISSUE TITLE
Can't install htslib by using autoheader

### ISSUE THREAD

**Issue by lizhan96** [samtools/htslib#1428]
I following the INSTALL File but I get ERROR. The following is the code i used and error message i got.
`$/data_6t/lizhan/02.software/autoconf-2.10/autoheader `

> m4: cannot open 'autoheader.m4': No such file or directory
m4: cannot open 'configure.in': No such file or directory

Do I miss some file? 
How can I get them?

**Comment by daviesrob** [comment]
It looks like your copy of autoconf may be broken.  However, if you download the [latest release](https://github.com/samtools/htslib/releases) then it already includes the `configure` script so you can skip running `autoreconf`.  Make sure you get the `.tar.bz2` file, NOT the "source code" ones which are automatically made by GitHub and don't work.

**Comment by daviesrob** [comment]
Hopefully you got this working now.  Let us know if not.
