### ISSUE TITLE
Maximum number of RG tags (or any aux tags)

### ISSUE THREAD

**Issue by lczech** [samtools/htslib#1444]
Hi there!

If I read [this](https://github.com/samtools/htslib/blob/008eabd3b38600a187b8d2fe94be9f8f9260545e/htslib/sam.h#L1641) correctly

```cpp
uint8_t *bam_aux_get(const bam1_t *b, const char tag[2]);
```

then the maximum number of distinct values for any aux tag, such as RG (read group) tags, is 256, due to the return type of the function. Is that correct? Is that also a limitation of the file format (sam/bam/cram) itself, or are the tag values stored with more bits there?

I am wondering about this, as we are working with several thousands of samples, and that basically would mean that we could never merge them into one gigantic bam file while keeping distinct RG tags for each of them, is that right? Not that this would be a reasonable thing to do anyway - I'm just curious about the theoretical limitations here.

Cheers and thanks in advance
Lucas

**Comment by daviesrob** [comment]
No, it returns a pointer into the internals of the `bam1_t` structure.  The pointed-to value will be the type code for the tag, followed by the tag data.

[`RG` tags should be type `Z`](https://samtools.github.io/hts-specs/SAMtags.pdf#subsection.1.2) so to get the tag data you can pass the value returned by `bam_aux_get()` to [`bam_aux2Z()`](https://github.com/samtools/htslib/blob/008eabd3/htslib/sam.h#L1697).  That will give you a `char *` to the read group name.  Note that this is still pointing back into the `bam1_t` structure, so making any changes there (e.g. reading a new record, or even editing the aux tags) will make the pointer returned by `bam_aux2Z` invalid.  You should copy the data elsewhere if you want it to last longer.

As read groups are strings, a very large number is possible as long as you name them sensibly.

**Comment by lczech** [comment]
Oh I see, thanks! Yes, I checked `bam_aux2Z()` now, and see how this is done. Honestly, these pointer casts that rely on the hard-coded order of member variables of structs are... trippy :-(
