### ISSUE TITLE
issue when trying to use htslib

### ISSUE THREAD

**Issue by JunxiFeng** [samtools/htslib#1459]
Hello,

I am an undergraduate student trying to use htslib to parse vcf files in c++, but after I included the header files needed and tried to open the vcf file, I ran into this error as shown below...
![截屏2022-06-22 下午9 23 47](https://user-images.githubusercontent.com/60299660/175208603-36a5f507-a2eb-46ba-843d-cdf38b32b753.png)
![截屏2022-06-22 下午9 24 53](https://user-images.githubusercontent.com/60299660/175208733-d88d6834-94e9-4d68-8e03-124c0e7e218e.png)
![截屏2022-06-22 下午9 25 07](https://user-images.githubusercontent.com/60299660/175208759-4493c2a4-ddd7-49f8-922d-00591f18709b.png)

Can anyone point me to the right direction please?

Thanks!

**Comment by daviesrob** [comment]
Did you remember to add `-lhts` to the command that links your program together?

**Comment by JunxiFeng** [comment]
Sorry for all the questions, but I am new to this, do you mind specifying where to add -lhts in the command? Thank you so much!

**Comment by JunxiFeng** [comment]
The problem has been solved! Thanks! @daviesrob
