### ISSUE TITLE
How to get a specific chromosome

### ISSUE THREAD

**Issue by JunxiFeng** [samtools/htslib#1472]
Hi,

Is there a specific function in htslib that retrieves a specific chromosome? thanks!

**Comment by daviesrob** [comment]
You need to use an index along with an iterator to do this.  For an example, see `sam_loop` in the [test_view](https://github.com/samtools/htslib/blob/1fba06c2c0/test/test_view.c#L64) program, and in particular [this part](https://github.com/samtools/htslib/blob/1fba06c2c0/test/test_view.c#L121) which makes an iterator over a set of regions given on the command line and then uses it to read through the data.
