### ISSUE TITLE
0 coordinate overflows in VCF format

### ISSUE THREAD

**Issue by Rapsssito** [samtools/htslib#1475]
As stated here: https://github.com/samtools/bcftools/issues/1753. There is an overflow issue when treating a VCF file with zero positions. Here is an example:

### Unsorted VCF
```
MT	0	1915430843:1	N	]MT:16640]N	99	PASS	.
MT	0	3110098432:1	N	]MT:16638]N	99	PASS	.
MT	16638	3110098432:2	G	G[MT:0[	99	PASS	.
MT	16640	1915430843:2	G	G[MT:0[	99	PASS	.
```

#### Commands
```
bcftools sort test.vcf -o test.sorted.vcf
```

### Sorted VCF
```
MT	4294967296	3110098432:1	N	]MT:16638]N	99	PASS	.
MT	4294967296	1915430843:1	N	]MT:16640]N	99	PASS	.
MT	16638	3110098432:2	G	G[MT:0[	99	PASS	.
MT	16640	1915430843:2	G	G[MT:0[	99	PASS	.
```

Note how the `0` from `3110098432:1` has been wrongly changed to `4294967296`.

As described by @pd3 in https://github.com/samtools/bcftools/issues/1753#issuecomment-1190071361:
> This problem is not specific to `bcftools sort` but to a round trip through BCF via htslib. The format stores 0-based position in `hts_pos_t` type and 0 coordinate overflows. This needs to be fixed in htslib.

@daviesrob, could you check this out?

**Comment by daviesrob** [comment]
Fixed by #1476
