### ISSUE TITLE
Fail to generate a beagle file

### ISSUE THREAD

**Issue by cnxiaobo94** [samtools/htslib#1481]
Log.file:
-> angsd version: 0.921 (htslib: 1.3.2) build(Jul 26 2022 10:29:19)
[E::hts_open_format] fail to open file 'CADG522_wg_20220717_merge_rmdup.bam
'
angsd: multiReader.cpp:348: multiReader::multiReader(int, char**): Assertion `in' failed.

Command line:
nohup angsd -GL 2 -out 11reddeer_PCA Threads 64 -minmapQ 30 -minQ 30 -doGlf 2 -doMajorMinor 1 -SNP_pval 1e-6 -rmtrans 1 -doMaf 1 -minmaf 0.0909 -skiptriallelic 1 -uniqueonly 1 -minind 8 -bam 11reddeer_bamlist.txt -ref ../refgenomes/xbalbwg/ GCA_006408465.1_WLD_genomic.fa -rf Scaffold_1MB

Describe:
I'm going to generate a beagle file for PCA analysis via angsd (angsd-0.921), but when I run the command line (as above), it stopped. I don't know what happened and how to solve it. Do you mind doing me a favor?  Thanks!

**Comment by whitwham** [comment]
This is an issue for [angsd](https://github.com/ANGSD/angsd).  Also, their version of HSTlib is 7 years old and very much out of date.

**Comment by whitwham** [comment]
Though it could be that you are not linking to the latest HTSlib.

**Comment by daviesrob** [comment]
This seems to occasionally come up in angsd.  See for example, ANGSD/angsd#87, or much more recently ANGSD/angsd#477.  I notice that the closing quote on the filename in the `hts_open_format` error message is on the next line.  Assuming the file does exist, that might suggest an unwanted carriage return character may have been included on the end of the name by angsd's file list reader.  Is it possible that you created your `11reddeer_bamlist.txt` file using a Windows text editor?

It looks like angsd added a check that tries to spot such characters in ANGSD/angsd#93 (check input list for carriage return), but it looks like the test is in the wrong place.  It should be looking in the file contents, not the filename itself...

**Comment by cnxiaobo94** [comment]
> This seems to occasionally come up in angsd. See for example, [ANGSD/angsd#87](https://github.com/ANGSD/angsd/issues/87), or much more recently [ANGSD/angsd#477](https://github.com/ANGSD/angsd/issues/477). I notice that the closing quote on the filename in the `hts_open_format` error message is on the next line. Assuming the file does exist, that might suggest an unwanted carriage return character may have been included on the end of the name by angsd's file list reader. Is it possible that you created your `11reddeer_bamlist.txt` file using a Windows text editor?
> 
> It looks like angsd added a check that tries to spot such characters in [ANGSD/angsd#93](https://github.com/ANGSD/angsd/issues/93) (check input list for carriage return), but it looks like the test is in the wrong place. It should be looking in the file contents, not the filename itself...

thanks a lot. The bamlist file is good, but the Scaffold_1MB file was created in Windows. I made another Scaffold file in Linux and it worked. The problem has been solved.
