### ISSUE TITLE
Binning index virtual file offsets

### ISSUE THREAD

**Issue by mmalenic** [samtools/htslib#1482]
I have a question about binning index files such as BAI. I'm trying to find the smallest virtual file offset in the index that is after the end of the header in the target file. Would this just be the first non-zero 'ioffset' as described [here](https://samtools.github.io/hts-specs/SAMv1.pdf#subsection.5.2)? Or would I have to search through all offsets in the index file? I'm not sure if there is any inherent order across the whole index in terms of small file offsets and large file offsets.

**Comment by daviesrob** [comment]
The smallest `ioffset` should point to the first indexed record, which would normally be the first alignment record after the header.  However, there have been some problems in the past with unmapped reads not being added to the linear index.  You may get better results by scanning through the binning index.

Unfortunately while the ordering of references usually matches between the index and the indexed file, I don't think there's any guarantee of that.  So for robustness you should really check all of the references.  Although if you just want to find the first record after the header, it might be easier to ignore the index and open the target file, read the header and then record the file location you're at.  Which is quicker depends on the relative size and complexity of your header and index.

**Comment by mmalenic** [comment]
Thanks @daviesrob, that clears it up.

Using similar logic, does that mean that the last ioffset in the last reference sequence is the closest position to the unplaced unmapped reads. Or is that also not guaranteed due to the ordering of the references?

**Comment by daviesrob** [comment]
Again, ordering of references, or refs with no aligned reads can complicate things a bit.  HTSlib finds the unplaced unmapped reads by [iterating through the whole index](https://github.com/samtools/htslib/blob/b7addd3151/hts.c#L3011) and finding the highest ioffset.
