### ISSUE TITLE
Avoid sprintf in cram_to_bam

### ISSUE THREAD

**Issue by lomereiter** [samtools/htslib#150]
Performance killer, takes 60% of the total time spent in the function.
By the way, there's a reasonable FIXME there about including container numbers in the name, but that's another matter.

![callgrind](https://cloud.githubusercontent.com/assets/662555/5191127/060b60e0-74fd-11e4-9039-be8a1323052a.png)

**Comment by jkbonfield** [comment]
It looks like this was fixed with PR #151 above, but failed to correctly report that it fixes this issue to it didn't auto-close.
