### ISSUE TITLE
tok3_decode_names() in cram/cram_io.c is undefined.

### ISSUE THREAD

**Issue by wangyugui** [samtools/htslib#1508]
Hi,

tok3_decode_names() in cram/cram_io.c is undefined.

or which external lib we need for it?

Best regards.

**Comment by wangyugui** [comment]
We need to checkout master of subproject htscodecs

**Comment by jkbonfield** [comment]
This can be automatically done when initially cloning with:

```
git clone --recurse <giturl>
```

Or added later on if you forget (as I invariably do) via:

```
git submodule update --init
```

(These are both in the INSTALL file.)
