### ISSUE TITLE
Can we pass an input file descriptor to bgzf_mt ?

### ISSUE THREAD

**Issue by rpadmanabhan** [samtools/htslib#1553]
Hi,
We can pass an input file descriptor to `bgzf_mt` right ? The function doc says "the file must be open for writing" [https://github.com/samtools/htslib/blob/develop/htslib/bgzf.h#L333].
But it looks like there were updates in the past that enable multi-threading when reading bgzf files as well ? It works for me when I pass an input file descriptor. Just wanted to confirm.

Also, thanks for all the great work in making such a high quality library available to the bioinformatics community.

**Comment by daviesrob** [comment]
Yes.  The comment "must be open for writing" pre-dates the current threading code.  We should remove it.
