### ISSUE TITLE
faidx_fetch_nseq() / faidx_nseq() API change between 1.0 and 1.1

### ISSUE THREAD

**Issue by jmarshall** [samtools/htslib#156]
In htslib 1.0 there was a `faidx_fetch_nseq()` function in faidx.h returning the number of reference sequences in the FASTA index.  (This function has been in faidx.h with that name since samtools/samtools@5edf84137d9ca68041477d36f2be640c42f46651 in 2009.)

830ea7395a00e4e9ad9de04e31d4b6014b776546 was committed prior to 1.1 and is included in that release.  It adds a new `faidx_nseq()` function doing the same thing, removes the implementation of `faidx_fetch_nseq()`, and leaves both declarations in _htslib/faidx.h_.

This means that:

1. Programs using `faidx_fetch_nseq()` compiled and linked against a shared 1.0 htslib will fail to run against _libhts.so.1.1_.

2. Programs using `faidx_fetch_nseq()` will fail to link against the 1.1 or current **develop** htslib, even though the function remains documented in _htslib/faidx.h_ and they compile successfully.

**Comment by jmarshall** [comment]
This problem broke pysam, as [reported on debian-med](https://lists.debian.org/debian-med/2014/09/msg00145.html) back in September.

**Comment by lh3** [comment]
I have seen a few libraries binding to htslib and a few tools using htslib. From now on, every change that breaks backward compatibility of APIs should be taken with great caution.
