### ISSUE TITLE
htslib make install error on 3 production servers

### ISSUE THREAD

**Issue by comatosejones** [samtools/htslib#1561]
/usr/bin/ld: cannot find @VERSION_SCRIPT_LDFLAGS@: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:358: libhts.so] Error 1

**Comment by daviesrob** [comment]
You probably need to rebuild your `configure` script and re-run it:
```
autoreconf -i
./configure
```

**Comment by comatosejones** [comment]
That worked, ty -- would it be prudent to rebuild before every update?

**Comment by jkbonfield** [comment]
Yes.  It won't harm, and any new release may in theory add something to the configure.ac and related machinery.
