### ISSUE TITLE
Extract auxiliary tags from BAM file

### ISSUE THREAD

**Issue by sagnikbanerjee15** [samtools/htslib#1588]
Hello,

I wish to extract some fields from a BAM file of `B` type. For example, `jM:B:c,1 jI:B:i,3914,3995`. Here is the code I am using:

```
uint8_t *jI = bam_aux_get(aln,"jI");
printf("\nValue of jI: %hhn", jI);
if(jI != NULL)
{
    char *jI_val = NULL;
    jI_val = bam_aux2Z(jI);
    printf("\njI:%s", jI_val);
}
```

I know what I am doing is incorrect but I am unsure what to replace it with. Could you please help?

Also, is there detailed documentation about the API?

Thank you.

**Comment by daviesrob** [comment]
For B tags, use `bam_aux_get()` followed by [bam_auxB_len](https://github.com/samtools/htslib/blob/c1634e743a/htslib/sam.h#L1740), then [bam_auxB2i](https://github.com/samtools/htslib/blob/c1634e743a/htslib/sam.h#L1751) or [bam_auxB2f](https://github.com/samtools/htslib/blob/c1634e743a/htslib/sam.h#L1763) depending on type.

**Comment by sagnikbanerjee15** [comment]
Thanks it worked!
