### ISSUE TITLE
typo in kh_int_hash_func2 definition

### ISSUE THREAD

**Issue by fanxinping** [samtools/htslib#1598]
htslib/khash.h line 450:
```c
#define kh_int_hash_func2(k) __ac_Wang_hash((khint_t)key)
```
should be
```c
#define kh_int_hash_func2(key) __ac_Wang_hash((khint_t)key)
```

**Comment by jkbonfield** [comment]
Good catch.   Looks like this was changed upstream in https://github.com/attractivechaos/klib/commit/384277a1cb85b8f83eb0ff6f52a591b38e52a55b

It's not something that any of our own code uses, so I'm not sure what the original author's intention was of adding this, but I'll make the trivial edit.  Thanks
