### ISSUE TITLE
Segfault when writing uncompressed BAM

### ISSUE THREAD

**Issue by tijyojwad** [samtools/htslib#1617]
Hi,

I am running into a segfault when I attempt to write a header into an uncompressed BAM. I'm opening the file using `hts_open(fname, "wbu")`. I tried with the commit `6143086502567c5c4bb5cacb2951f664ba28ed6e` (release 1.17) but still see that issue.

The same code runs if I just change the mode to "wb".

Could that be looked into?
Thanks!

**Comment by tijyojwad** [comment]
thanks to a tip from @cjw85 I learnt that `wb0` did the trick for generating uncompressed BAMs. Could the API documentation be updated for that?

**Comment by daviesrob** [comment]
`u` should work, and certainly shouldn't segfault.  We'll look into it.
