### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by najoshi** [samtools/htslib#162]
Hello,

I apologize for posting this here, but I can't find a better place to ask this question. All I want to do is get the reference name from a SAM alignment line. I've figured out how to use sam_read1 to iterate through the file (after calling sam_hdr_read) but I can't find how to get the actual reference string (i.e. the 3rd column). Any help would be highly appreciated!

- Nik.

**Comment by jmarshall** [comment]
The  better place for questions like this would be the [samtools-devel mailing list](https://lists.sourceforge.net/lists/listinfo/samtools-devel).

The [samtools](https://github.com/samtools/samtools) code can effectively be used as (over-complicated) sample code.  Anyway, if `hdr` is the headers you got from `sam_hdr_read()` and `aln` is an alignment from `sam_read1()`, the current way to get the name of the reference contig is

    hdr->target_name[aln->core.tid]
