### ISSUE TITLE
Request to support multiple input files.  Currently, bgzip <file1> <file2> only compresses <file1>. 

### ISSUE THREAD

**Issue by bw2** [samtools/htslib#1642]
bgzip's command-line interface is similar to gzip, so I was surprised to see that 

```
bgzip file1   file2   file3  ...
```
only compressed the first file1 (while gzip would compress each of the files).

I think `bgzip` would be more user-friendly if it behaved like gzip in this case, or at least threw an error to say that the extra files were unrecognized arguments instead of silently ignoring them.

**Comment by jmarshall** [comment]
See also #391.

**Comment by daviesrob** [comment]
Yes, it's about time we made this work.  We'll look into it.
