### ISSUE TITLE
iRODS write problem

### ISSUE THREAD

**Issue by keithj** [samtools/htslib#168]
I've build htslib from develop and also samtools from develop. To get samtools to build once iRODS support was enabled I used:

````
make HTSDIR=../htslib.git LDFLAGS=-L"$IRODS_HOME/lib/core/obj" LDLIBS="-lRodsAPIs -lgssapi_krb5"
````

This builds samtools successfully. I can read BAM and CRAM files in iRODS (although not with an index locally or remotely). I can't insert files successfully. A zero length file of the correct name is added to iRODS, but it is marked as being in the resource "demoResc" and consequently non-existent server-side filesystem path.

````
./samtools view toy.sam -b -o irods:toy.bam
ERROR: readMsgHeader:header read- read 0 bytes, expect 4, status = -4115
ERROR: readAndProcApiReply: readMsgHeader error. status = -4115 status = -4115 SYS_HEADER_READ_LEN_ERR, Operation now in progress
samtools: error closing "irods:toy.bam": -1

ils -L toy.bam
kdj               0 demoResc                        0 2015-01-28.13:56 & toy.bam
          generic    /usr/local/iRODS/Vault/home/kdj/toy.bam
````

**Comment by jmarshall** [comment]
The _index locally or remotely_ problem should have been fixed (or at least made differently problematic!) by 0ad99655e4f399bb876917802604681ede4e1cdb.

**Comment by jmarshall** [comment]
I don't know enough about iRODS to know what the `demoResc` resource thing means.  Is there some function that hfile_irods.c should be calling to set that?

I can reproduce this:

    $ ils -l
    /Sanger1/home/jm18:
      jm18              0 wtsiusers                  162509 2015-01-28.14:38 & testseq.bam
      jm18              0 wtsiusers                     904 2015-01-28.14:38 & testseq.bam.bai
      jm18              0 demoResc                        0 2015-01-28.14:43 & toy.bam
      jm18              0 demoResc                   162509 2015-01-28.14:49 & toy2.bam

toy.bam was created with your command and gave the same errors.  toy2.bam was created by commenting out the call to `rcDataObjFsync()` and running the same command, giving no errors and creating a well-sized file.  Hmmm...

Despite appearing to be zero-length, samtools appears to be able to get the same data out of toy.bam as toy2.bam:

    $ samtools view -c irods:toy.bam; samtools view -c irods:toy2.bam
    2000
    2000

Any ideas, iRODS expert? :smile:

**Comment by keithj** [comment]
Thanks, I hacked togther a poor version of  ````hisremote```` just earlier and was able to do random access reads. I'll take a look at ````rcDataObjFsync````. If I'm not back in an hour, I've been eaten by a grue.

**Comment by keithj** [comment]
To set the resource, add metadata to the args of ````rcDataObjOpen````
Not yet having CLI support for setting the desired resource, a good option is to pick up the default
resource from  ````rodsEnv````.

````
rodsEnv myEnv;
ret = getRodsEnv (&myEnv);

addKeyVal(&args.condInput, RESC_NAME_KW,  myEnv.rodsDefResource);
ret = rcDataObjOpen(irods.conn, &args);
````

**Comment by keithj** [comment]
I've raised an issue over at iRODS asking about the correct use of ````rcDataObjOpen````. As far as I can see neither the official clients (````iput```` etc), nor the cctools parrot client use it.

**Comment by jmarshall** [comment]
While the iRODS folks contemplate irods/irods#2499, I guess in the meantime we should just comment out the body of `irods_flush()`...

**Comment by keithj** [comment]
I think so. We have two precedents for not using it; ````iput```` and cctools parrot. Plus it seems to kill kittens.

**Comment by jmarshall** [comment]
:cat2: receives reprieve

**Comment by keithj** [comment]
Noted that there is no ````rcDataObjFsync.hpp```` in iRODS 4.x (you should be aware that they have renamed all the header files ````.h```` to ````.hpp````)

**Comment by jmarshall** [comment]
Okay, probably we can make `irods_flush()` a no-op permanently.

I don't suppose they provide compatibility `.h` headers (that just `#include` the corresponding `.hpp` header) in 4.x?

**Comment by keithj** [comment]
There are no compatability headers.

**Comment by keithj** [comment]
FYI they have just renamed the C headers back to `.h` in https://github.com/irods/irods/commit/00b78660acbccbe78fa2c319a0a47c552334d8fd

**Comment by jmarshall** [comment]
Excellent, I wait long enough and part of the 4.x compatibility story takes care of itself :smile:

**Comment by jkbonfield** [comment]
Just incase anyone else uses this as a ecipe for making iRODS work, a slight amendment to the above: you need LIBS="-lIrodsAPIS..." and not LDLIBS="..."

**Comment by jmarshall** [comment]
When htslib has been configured with --enable-plugins, you now just need `make LDFLAGS=-rdynamic LIBS=‑ldl` to compile samtools.  This too will go away with a sufficient sprinkling of pkg-config and/or configure…
