### ISSUE TITLE
Unchecked results from "write"s

### ISSUE THREAD

**Issue by mp15** [samtools/htslib#17]
Given the propensity of lustre and other network files systems to give up the ghost we probably should be checking our return values more carefully.  The current situations means its possible we'll miss a failed write and return success when we should bail out and fail. _razf_write is probably one place to start looking.

**Comment by jmarshall** [comment]
RAZF is gone as of b3a7868c80047c1ea3ee6b6330b12f80ad3680db, but I'm sure other unchecked writes remain.

Early in the next release cycle we should audit especially writes.

**Comment by jmarshall** [comment]
PR #271 should have hit most of these writes.
