### ISSUE TITLE
Unable to install the HTSlib on Ubuntu 20.04

### ISSUE THREAD

**Issue by LEGMCGILL** [samtools/htslib#1721]
Hello dear community, 

I am trying to install the HTSlib on my ubuntu 20.04. instance

I created a virtual environtment where I ran the following commands: 

cd /usr/bin
wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2
tar -vxjf htslib-1.9.tar.bz2
With the last command I am getting the following message. 

htslib-1.19.tar.bz2: Permission denied

Cannot write to ‘htslib-1.19.tar.bz2’ (Success).

Hence, I am being unable to continue the installation.

I would appreciate very much your help with some advice on how to solve this issue.
I have also included a screenshot of the error message: 

Best,

![image](https://github.com/samtools/htslib/assets/147701622/c9b5f84c-63b5-4383-ae14-a624ddcfbdda)

**Comment by daviesrob** [comment]
Hopefully you've managed to sort this out now.  Please let us know if not.
