### ISSUE TITLE
feature request: parallelize tabix

### ISSUE THREAD

**Issue by dbolser** [samtools/htslib#1735]
I'd like to index a bed file (tbi) using bcftools (because of the ability to use multiple threads).

Is this a feature that you could easily support?

Many thanks,
Dan.

**Comment by jkbonfield** [comment]
Is the issue here simply the multi-threaded bgzf decoding?  I admit I assumed we'd got that enabled for everything, but indeed tabix doesn't do it apparently.  I'm not sure why - either we simply missed it or perhaps it was testing and gave no major benefit (eg the primary CPU burden is elsewhere).

**Comment by dbolser** [comment]
I could imagine it's IO bound... perhaps...
