### ISSUE TITLE
bcftools-1.19: Invalid index is produced by --write-index and --threads on my bcf.gz files

### ISSUE THREAD

**Issue by graphenn** [samtools/htslib#1740]
The index is produces by command like this:
``` Shell
bcftools view --threads 6 -f PASS -Ob --write-index -o test.out.bcf.gz test.bcf.gz
```

On my full bcf file, most region of it works well, but when read variant at POS 2465975, it shows
``` Shell
[W::bcf_record_check] Bad BCF record at (unknown):1635086638: Invalid ID type 4 (unknown)
[W::bcf_record_check] Bad BCF record at (unknown):1635086638: Invalid REF/ALT type 0 (null)
[E::bcf_record_check] Bad BCF record at (unknown):1635086638 - shared section malformed or too short
```

After index again
``` Shell
bcftools index -f test.out.bcf.gz
```
Then read POS 2465975 works, no error.

I make a small sample bcf.gz file
[test.bcf.gz](https://github.com/samtools/bcftools/files/14123847/test.bcf.gz)

Run
``` Shell
bcftools view --threads 6 --write-index -Ob -o test2.bcf.gz test.bcf.gz chrY:2465910-2465990
```

Then read POS 2465975, can't read the variant.
``` Shell
[E::bgzf_read] Read block operation failed with error 4 after 0 of 32 bytes
```

Index again and then read POS 2465975, everything works well.
``` Shell
bcftools index test2.bcf.gz -f
```

I guess the issue is related with the long sample id lists in the file.

**Comment by daviesrob** [comment]
Thanks for the bug report and example.  This should be fixed by pull request #1742
