### ISSUE TITLE
Read failure on iRODS 4.x

### ISSUE THREAD

**Issue by keithj** [samtools/htslib#175]
iRODS 4.x may re-malloc over the byte buffer passed to ````rcDataObjRead````. I've been bitten by this when testing baton on iRODS 4.0.3. iRODS 3.3.1 does not do this.

Given that ````irods_read```` passes a buffer to ````rcDataObjRead```` I suspect that it may trigger the bug. I haven't tested yet, but will do so soon and update this issue.

See irods/irods#2503

**Comment by keithj** [comment]
Of course, this only affects if building against iRODS 4.x (which is what I was doing). I'll go ahead and test on 4.0.3, but will close this for now.

**Comment by jmarshall** [comment]
Presumably they will realise that that would be an unusable API for `rcDataObjRead` and revert this "feature" (or at least make it sane as [bpow suggested](https://github.com/irods/irods/issues/2503#issuecomment-73241993)).

I'm planning to start testing with 4.x as well... presumably the configurery at least will have to start detecting it and I guess its new client library names -- hopefully after they put them in the standard place in response to your irods/irods#2494.

**Comment by keithj** [comment]
I have got a working autoconf for baton that detects and builds on 3.3.x, 4.x .deb packaged and 4.x run-in-place. Some of that may be re-usable. (Unfortunately the iRODS libraries are different in the packaged and run-in-place versions of 4.0.3 - the RIP version is more like 3.3.x)

**Comment by keithj** [comment]
Confirmed bug in iRODS 4.0.3: test_view fails to read any files from iRODS. Can be fixed by defensive copying into the htslib read buffer (also confirmed).

**Comment by jmarshall** [comment]
This is fixed in iRODS 4.1.x, so our approach is to document that we don't support iRODS 4.0.x.

**Comment by jmarshall** [comment]
[This issue was repurposed to represent getting the iRODS plugin working with iRODS 4.x.]

The iRODS plugin has moved to the new [samtools/htslib-plugins](https://github.com/samtools/htslib-plugins) repository, and the version there supports 3.x, 4.1.x, and 4.2-to-be.

(_hfile_irods.c_ and the configury will soon be removed from HTSlib itself.)
