### ISSUE TITLE
Filter line always added to the VCF header when opening a file for writing

### ISSUE THREAD

**Issue by nh13** [samtools/htslib#1782]
See title.

This comes from using `pysam`:

```python
vcf_header = VariantHeader()
vcf = VariantFile("test.vcf", "w", header=vcf_header)
vcf.close()
```

I would expected the `fileformat` line and that's it in the header.

But we always get the following filter line:
```
##FILTER=<ID=PASS,Description="All filters passed">
```

My best guess is that it comes from [`bcf_hdr_init`](https://github.com/pysam-developers/pysam/blob/36a0304c33568764a0d7117917ca27ad9dc4a390/htslib/vcf.c#L1387)

The following is a work-around:

```python
vcf_header = VariantHeader()
vcf = VariantFile("test.vcf", "w", header=vcf_header)
vcf.header.filters.remove_header("PASS")
vcf.close()
```

Any reason why we always need to add this filter (the ship may have sailed, but curiosity killed the cat)?

**Comment by jmarshall** [comment]
I believe this is the HTSlib implementation's way of ensuring BCF's requirement that PASS be encoded as 0. (See the VCF spec §6.2.1, “Dictionary of strings”.)

**Comment by pd3** [comment]
That is exactly right. HTSlib makes the implicit PASS filter explicit to prevents problems, so this is working as intended.

**Comment by nh13** [comment]
Thank-you, this is super helpful, especially the link to §6.2.1!
