### ISSUE TITLE
assert(0) is bad practice

### ISSUE THREAD

**Issue by mp15** [samtools/htslib#1791]
if you compile with NDEBUG asserts go away 
https://github.com/samtools/htslib/blob/5f205334cd04bcdac74b1b6d46f88d57a05eaf1c/synced_bcf_reader.c#L545
suggest replacing with abort();

**Comment by pd3** [comment]
It seems this was unintentionally introduced by https://github.com/samtools/htslib/commit/f0fc3eea33477ed45f5f9ffa34f6fea7365513d8, should be fixed.
