### ISSUE TITLE
which function to get alignment of query's mate in sam.h or other header files

### ISSUE THREAD

**Issue by leon945945** [samtools/htslib#1804]
Hi, as the title describes, I want to get the alignment of query's mate, like chromosome aligned to, CIGAR information and others.
Which function would bring me to the information, perhaps I didn't find a proper function in sam.h.
Thanks very much.

**Comment by jkbonfield** [comment]
Positioning will be in the RNEXT and PNEXT fields.  There is minimal API for manipulating BAM (sadly), but they are present in the `b->core.mtid` and `b->core.mpos` fields, where `b` is a `bam1_t *`.  See https://github.com/samtools/htslib/blob/develop/htslib/sam.h#L214-L227

More detailed alignment information may be present in the SAM auxiliary fields, but they're optional so it depends on the aligner.    You can look for aux tags with the `bam_aux_get` function.  The official definition of which tags may be present is in http://samtools.github.io/hts-specs/SAMtags.pdf.   However be warned that they may not exist in your files.

The alternative is simply reading both alignments.  If you're doing adhoc queries then you can do a range query to the PNEXT/RNEXT location and load the data that way (or use `samtools view --fetch-pair` which basically does the same thing for all reads within a designated region).  If you find you're needing to do this for large swathes of data, the best alternative is probably to first run `samtools collate` to group pairs together.  This is messy and time consuming, but the file format simply doesn't store the information you need unless someone has already added it to the aux fields.  (You can obviously do this yourself post-alignment and pre-position-sorting.)

**Comment by leon945945** [comment]
Thanks very much, your detailed reply meets my need.
