### ISSUE TITLE
Support VN:1.5

### ISSUE THREAD

**Issue by jeremiahsavage** [samtools/htslib#185]
I've used biobambam to merge some files, and it ouputs
    `@HD     VN:1.5  SO:coordinate`
using https://github.com/gt1/libmaus/blob/master/src/libmaus/bambam/BamCatHeader.hpp#L116

According to the spec ( http://samtools.github.io/hts-specs/SAMv1.pdf ), 1.5 is the current version, but picard ValidateSamFile gives an error, which the diff below eliminates.

```
diff --git a/src/java/htsjdk/samtools/SAMFileHeader.java b/src/java/htsjdk/samtools/SAMFileHeader.java
index 2e237c4..ac361b1 100644
--- a/src/java/htsjdk/samtools/SAMFileHeader.java
+++ b/src/java/htsjdk/samtools/SAMFileHeader.java
@@ -46,9 +46,9 @@ public class SAMFileHeader extends AbstractSAMHeaderRecord
     public static final String VERSION_TAG = "VN";
     public static final String SORT_ORDER_TAG = "SO";
     public static final String GROUP_ORDER_TAG = "GO";
-    public static final String CURRENT_VERSION = "1.4";
+    public static final String CURRENT_VERSION = "1.5";
     public static final Set<String> ACCEPTABLE_VERSIONS =
-            new HashSet<String>(Arrays.asList("1.0", "1.3", "1.4"));
+            new HashSet<String>(Arrays.asList("1.0", "1.3", "1.4", "1.5"));
 
     /**
      * These tags are of known type, so don't need a type field in the text representation.
```

**Comment by jmarshall** [comment]
You have found the **C htslib** project, not the **Java htsjdk**.  Please re-file this issue in the [htsjdk project](https://github.com/samtools/htsjdk).

**Comment by jmarshall** [comment]
Thanks -- this is now samtools/htsjdk#183.  (The Java project is maintained by a different group of people y'see, so they wouldn't see your bug report here.)

**Comment by jeremiahsavage** [comment]
appreciated. thanks for the correct pointer.
