### ISSUE TITLE
segfault on `hclose`

### ISSUE THREAD

**Issue by ekg** [samtools/htslib#190]
If you uncomment [these lines in vg](https://github.com/ekg/vg/blob/master/alignment.cpp#L20-L24) and run:

```bash
vg view -bG aln.bam
```
It should segfault with something like:

```text
*** Error in `vg': free(): invalid pointer: 0x00000000015ded60 ***
```

It's not critical that this is resolved. I suspect I'm doing something silly. The entire code for handling the file is in the linked function, so hopefully it's clear.

**Comment by jmarshall** [comment]
You're effectively double-closing the file handle.

We should document it better, but `hts_hopen()` engulfs the input `hFILE*`, transferring responsibility for closing the underlying file to the output `htsFile*`.

So the complicated "I need to look at the hFILE first" sequence of events is `hopen ... hts_hopen ... hts_close`.

But usually you don't need to do that and can just use `htsFILE*` file pointers all the way, and simply use `hts_open ... hts_close`.

**Comment by ekg** [comment]
Great, I've sorted this out as of https://github.com/ekg/vg/commit/1bded93ddf8919948b337044d5d74b096f5c53b9
