### ISSUE TITLE
Is htslib threadsafe? (openmp?)

### ISSUE THREAD

**Issue by ekg** [samtools/htslib#195]
I'm having some pretty severe (and utterly confusing) problems with code that touches htslib. It seems likely that the problem is on my end, but I thought it'd be worth asking if there is any obvious reason why it might be unsafe to mix htslib functions and openmp. I have code that works perfectly with one thread, but falls down when there are two or more threads with completely random segfaults. There are no out-of-bounds reads as far as I can tell (as assessed by valgrind on another system... I can't get it to run on the system where the problem is occurring.)

Any ideas?

**Comment by ekg** [comment]
For reference, things seem to be failing around here: https://github.com/ekg/vg/blob/master/main.cpp#L262

**Comment by molpopgen** [comment]
IMO, writing from multiple threads should be considered "dangerous" in the absence of explicit guarantees to the contrary :). Have you tried placing a file access lock/unlock before/after that call?  

Forgetting mpi for a moment, but if you were doing this using C++11 threads, "out" could be a global variable and individual threads' access to that object could be managed using std::mutex.

> On Apr 2, 2015, at 10:06 AM, Erik Garrison <notifications@github.com> wrote:
> 
> For reference, things seem to be failing around here: https://github.com/ekg/vg/blob/master/main.cpp#L262
> 
> —
> Reply to this email directly or view it on GitHub.
> 

___________________________
Kevin Thornton
Associate Professor
Ecology and Evolutionary Biology
University of California, Irvine
http://www.molpopgen.org
http://github.com/molpopgen
http://github.com/ThorntonLab

**Comment by lh3** [comment]
I/O should be serialized.

**Comment by ekg** [comment]
@molpopgen : Yep, it's locked. The `#pragma omp critical` statement above the write call ensures that only one thread at a time enters the write call.

@lh3 : The omp pragma ensures that writes are happening only one-at-a-time.

That said, I've resolved the problem. It was elsewhere, with a map that was being accessed outside of a lock (https://github.com/ekg/vg/commit/0f2f4471125ce4738b72d9f9677cc5d0fa7f376c). Why this would trigger a problem only on a system where I couldn't run valgrind to find the invalid access is beyond me. But in any case I sat down today and fixed it with fresh eyes.

As usual, my problems with htslib are not problems with htslib at all! Thanks for listening :)
