### ISSUE TITLE
htsfile predicts "SAM version 1" for all text files

### ISSUE THREAD

**Issue by tseemann** [samtools/htslib#200]
I'm not sure what peeking "htsfile" does but on a random Ruby file it says:

```
% htsfile baps.rb
baps.rb:        SAM version 1 sequence text

% head baps.rb
Class Baps < Formula
  homepage "http://www.helsinki.fi/bsg/software/BAPS/"
  # doi ""
 <snip>
```

**Comment by jmarshall** [comment]
At present, `hts_detect_format()` reports pretty much [any text file as SAM](https://github.com/samtools/htslib/blob/develop/hts.c#L271-276).

Thanks for pointing out that in addition to the possibilities in that comment, it should say `unknown` for text that doesn't look tab-delimited.  (It needs to be conservative in saying `unknown` as this is used by `hts_open(filename, "r")` so it must not fail to recognise anything that can in fact be parsed.)

**Comment by jkbonfield** [comment]
On Mon, Apr 27, 2015 at 07:27:18PM -0700, Torsten Seemann wrote:
> I'm not sure what peeking "htsfile" does but on a random Ruby file it says:
> 
> ```
> % htsfile baps.rb
> baps.rb:        SAM version 1 sequence text
> 
> % head baps.rb
> Class Baps < Formula

The unfortunately situation is that SAM has no magic number.  BAM and
CRAM can be identified by their headers.  SAM *may* start with
"@"-something, but it's not necessarily required. Indeed even the
totally blank file (zero length) is a valid SAM file!

I guess what it needs is something cleverer to tell apart SAM from
other arbitrary files.  Ie starting with @..\t or a tab delimited file
of at least 11 columns.

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by tseemann** [comment]
I guess there are multiple levels of evidence that point to being a SAM file
* .sam extension
* possible SAM header with ```@```
* possible alignment lines, tab sep 11 columns
* specific types (int, DNA) in particular columns
The empty files etc are troublesome.

I guess the decision is what is worse: false positives, or false negatives?

What are they key use-cases for htsfile?
