### ISSUE TITLE
htslib v1.2.1 compilation error

### ISSUE THREAD

**Issue by santiagorevale** [samtools/htslib#205]
Hi there!

I was trying to compile latest version of htslib (1.2.1) but an error appeared and broke the compilation. Logs for the "configure" and "make" commands are at the end of the post. It also happened with version 1.2.

I'm performing the installation on a CentOS 5.5. I'm compiling with gcc version 4.7.4.

Any help would be really appreciated.

Best,
Santiago

$ ./configure 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for zlib.h... yes
checking for inflate in -lz... yes
configure: creating ./config.status
config.status: creating config.mk

$ make
gcc -g -O2 -I. -c -o kfunc.o kfunc.c
gcc -g -O2 -I. -c -o knetfile.o knetfile.c
gcc -g -O2 -I. -c -o kstring.o kstring.c
gcc -g -O2 -I. -c -o bgzf.o bgzf.c
gcc -g -O2 -I. -c -o faidx.o faidx.c
gcc -g -O2 -I. -c -o hfile.o hfile.c
gcc -g -O2 -I. -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.2.1"' > version.h
gcc -g -O2 -I. -c -o hts.o hts.c
gcc -g -O2 -I. -c -o regidx.o regidx.c
gcc -g -O2 -I. -c -o sam.o sam.c
gcc -g -O2 -I. -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -O2 -I. -c -o vcf_sweep.o vcf_sweep.c
gcc -g -O2 -I. -c -o tbx.o tbx.c
gcc -g -O2 -I. -c -o vcf.o vcf.c
gcc -g -O2 -I. -c -o vcfutils.o vcfutils.c
gcc -g -O2 -I. -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -O2 -I. -c -o cram/cram_decode.o cram/cram_decode.c
cram/cram_decode.c: In function ‘cram_dependent_data_series’:
cram/cram_decode.c:670:28: error: ‘SAM_QNAME’ undeclared (first use in this function)
cram/cram_decode.c:670:28: note: each undeclared identifier is reported only once for each function it appears in
cram/cram_decode.c:673:28: error: ‘SAM_FLAG’ undeclared (first use in this function)
cram/cram_decode.c:676:28: error: ‘SAM_RNAME’ undeclared (first use in this function)
cram/cram_decode.c:679:28: error: ‘SAM_POS’ undeclared (first use in this function)
cram/cram_decode.c:682:28: error: ‘SAM_MAPQ’ undeclared (first use in this function)
cram/cram_decode.c:685:28: error: ‘SAM_CIGAR’ undeclared (first use in this function)
cram/cram_decode.c:688:28: error: ‘SAM_RNEXT’ undeclared (first use in this function)
cram/cram_decode.c:691:28: error: ‘SAM_PNEXT’ undeclared (first use in this function)
cram/cram_decode.c:694:28: error: ‘SAM_TLEN’ undeclared (first use in this function)
cram/cram_decode.c:698:28: error: ‘SAM_SEQ’ undeclared (first use in this function)
cram/cram_decode.c:701:30: error: ‘SAM_AUX’ undeclared (first use in this function)
cram/cram_decode.c:705:28: error: ‘SAM_QUAL’ undeclared (first use in this function)
cram/cram_decode.c:711:28: error: ‘SAM_RGAUX’ undeclared (first use in this function)
cram/cram_decode.c: In function ‘cram_decode_slice_xref’:
cram/cram_decode.c:1699:30: error: ‘SAM_RNEXT’ undeclared (first use in this function)
cram/cram_decode.c:1699:42: error: ‘SAM_PNEXT’ undeclared (first use in this function)
cram/cram_decode.c:1699:54: error: ‘SAM_TLEN’ undeclared (first use in this function)
cram/cram_decode.c: In function ‘cram_decode_slice’:
cram/cram_decode.c:1913:32: error: ‘SAM_SEQ’ undeclared (first use in this function)
cram/cram_decode.c:2053:39: error: ‘SAM_TLEN’ undeclared (first use in this function)
cram/cram_decode.c: In function ‘cram_to_bam’:
cram/cram_decode.c:2387:31: error: ‘SAM_QNAME’ undeclared (first use in this function)
cram/cram_decode.c:2418:32: error: ‘SAM_SEQ’ undeclared (first use in this function)
cram/cram_decode.c:2418:42: error: ‘SAM_QUAL’ undeclared (first use in this function)
cram/cram_decode.c: In function ‘cram_next_slice’:
cram/cram_decode.c:2562:30: error: ‘SAM_POS’ undeclared (first use in this function)
make: *** [cram/cram_decode.o] Error 1

**Comment by jmarshall** [comment]
`SAM_QNAME` et al are defined in 1.2.1's htslib/hts.h, and were introduced in htslib 1.2.  Since other declarations in htslib/hts.h _were_ found, probably what has happened is that compiling this source code has found some htslib 1.1 headers instead.

This is likely the same problem as #117, but I wasn't able to reproduce it then.

Please compile with

    make CC='gcc -H' -B cram/cram_decode.o

and let us know what is printed for `.... <path>/htslib/hts.h`.  Do you have `$CPATH` or `$C_INCLUDE_PATH` environment variables set?

This information will hopefully help track down how this is happening and show what we can do in htslib to prevent it.

But you would also like to just fix it and get htslib compiled.  Presumably you have 1.0 or 1.1 htslib headers installed somewhere that the compiler can see; so you can work around this by uninstalling the previous headers.

**Comment by santiagorevale** [comment]
Hi John,

It was exactly as you said: I had the previous htslib version set in the $C_INCLUDE_PATH variable. After I removed it, it worked like a charm.

Thank you very much for your help and quick reply.

Keep up with the great work!
