### ISSUE TITLE
uninformative error message with Flag

### ISSUE THREAD

**Issue by brentp** [samtools/htslib#213]
This gives the uninformative message:
https://github.com/samtools/htslib/blob/30fb9eee41953958923c56f7ea0af5a5b0376b94/vcf.c#L1606

I have an admittedly wonky VCF here: https://gist.github.com/brentp/30c28855974f1526408a

you can recreate the core dump with vt: vt decompose -s wonky.vcf

which gives
```
[E::_vcf_parse_format] the format type 5 currently not supported
```

**Comment by pd3** [comment]
The VCF seems OK, the problem seens to be in the way `vt` is using `htslib`. It probably has something to do with reusing the same record multiple times without clearing or unpacking. A minimal example of the API usage would be helpful.

**Comment by brentp** [comment]
cc @atks

**Comment by atks** [comment]
in this case, for decompose, I'm not reusing bcf1_t objects at all.  it's really weird.  I'm looking into this.  will try to fix it by today.

**Comment by atks** [comment]
This is what I found out:

vt decompose wonky.vcf => error
vt decompose wonky.vcf.gz => error
vt decompose wonky.bcf => runs to completion
vt decompose wonky_remove_GATKcommandline_metaheader.vcf => runs to completion, GATK command line is very long.
vt decompose wonky_remove_AC_metaheader => runs to completion although [vcf_parse] complains about missing AC header

@pd3 do you think this might be a case of a vcf header processing problem?

**Comment by atks** [comment]
@brentp @pd3 
The problem appears to reside at the place when vt decompose attempts to add a meta header.  In this case I've changed the mechanism to check for existence of the header before using bcf_hdr_append.  For some reason, the presence of the OLD_MULTIALLELIC header caused problems.  

I understand that bcf_hdr_append() does check for presence of the header to be added but somehow something else got corrupted along the way.  It's highly possible that I am using bcf_hdr_append() wrongly.

**Comment by pd3** [comment]
@brentp @atks That's not it, adding a key multiple times should be OK. It was probably caused by this bug, now fixed by https://github.com/pd3/htslib/commit/3e924619772ba991b3a636d5ac86d42a2a49eb02. I am not sure if this fix covers all situations - when a header is modified, its dictionary may get out of sync with the tags used throughout the body. This should always work:

```    
#include <stdio.h>
#include <htslib/hts.h>
#include <htslib/vcf.h>

int main(int argc, char **argv)
{
    char *fname = argc>1 ? argv[1] : "wonky.vcf";
    htsFile *in  = hts_open(fname,"rb");
    htsFile *out = hts_open("-","w");
    bcf_hdr_t *hdr_in  = bcf_hdr_read(in);
    bcf_hdr_t *hdr_out = bcf_hdr_dup(hdr_in);
    bcf_hdr_append(hdr_out,"##INFO=<ID=OLD_MULTIALLELIC,Number=1,Type=String,Description=\"Original chr:pos:ref:alt encoding\">\n");
    bcf_hdr_write(out, hdr_out);
    bcf1_t *rec = bcf_init1();
    while ( bcf_read(in, hdr_in, rec)>=0 )
    {
        bcf_write(out, hdr_out, rec);
    }
    bcf_hdr_destroy(hdr_out);
    bcf_hdr_destroy(hdr_in);
    bcf_destroy(rec);
    hts_close(in);
    hts_close(out);
    return 0;
}
```

    gcc -Wall -Wc++-compat -O2 -I./htslib test.c htslib/libhts.a -lpthread -lz -o rmme
    ./rmme wonky.vcf

**Comment by atks** [comment]
@pd3 great! thanks!  Can you merge that change with the develop branch so that I may test it?

**Comment by mcshane** [comment]
Hi @atks this is in develop now. Can you confirm if it solves the issue?

**Comment by atks** [comment]
It's working.  Thanks! 

@brentp - I think we can close the issue now.

**Comment by brentp** [comment]
thanks all!
