### ISSUE TITLE
faidx + sam man pages in htslib - better in samtools?

### ISSUE THREAD

**Issue by tseemann** [samtools/htslib#222]
htslib has man pages for: htsfile tabix faidx sam vcf

fadix and sam: more appropriate to samtools?

Just a suggestion.

**Comment by jmarshall** [comment]
I added the file format man pages in htslib alongside the API that manipulates the corresponding files.  Another thought was that people might theoretically have other htslib-using programs installed but not samtools, so would have htslib installed so get these man pages.

Thanks for the suggestion, but I think moving them now would cause more disruption than improvement.
