### ISSUE TITLE
`hts_hopen` should have an exclusive mode

### ISSUE THREAD

**Issue by SamStudio8** [samtools/htslib#245]
`hts_hopen` should provide functionality akin to `O_EXCL` in `open` or `x` in `fopen` to allow applications to open handlers to files with exclusivity to avoid race conditions like those demonstrated in samtools/samtools#432.

**Comment by jmarshall** [comment]
You can already get this effect via `open(O_EXCL) / hdopen() / hts_hopen()`, but it would indeed probably be good if `hts_open()` and `hts_hopen()` followed glibc's `fopen()` mode extensions, such as `x`.

**Comment by jmarshall** [comment]
If I'd realised this would take just one line (+doco), I would have implemented it back in July—sorry!

Added because it'll be handy for _bgzip.c_ overhauling too.
