### ISSUE TITLE
Feature request: remote index files api

### ISSUE THREAD

**Issue by dcolligan** [samtools/htslib#247]
Requesting an API regarding index files from a remote source that htslib saves locally.  Specifically:

   1. whether remote index files are saved
   2. controlling where remote index files are written

(See discussion here https://github.com/ga4gh/server/issues/500#issuecomment-124166705 )

**Comment by jmarshall** [comment]
We've already added such functionality at your request: see e9b7db4474ee82fc33c883cc906985ec56b32802.

You can download remote indices under your own control by using `hopen(remote_index_url)` directly and save them wherever you like.

You can then load them with `hts_idx_load2(remote_bam_url, local_index_fname)`.
