### ISSUE TITLE
Header parsing bug leads to missing VCF columns in output

### ISSUE THREAD

**Issue by pd3** [samtools/htslib#248]
Please see the error description here https://github.com/atks/vt/issues/33

**Comment by cyenyxe** [comment]
There are two possible solutions for this, depending on how error tolerant the library is expected to be:

* VCF v4.1 and v4.2 specifications don't flag trailing spaces as errors, so they could be accepted (just by trimming the input line).
* VCF v4.3 won't allow them, so an error should be displayed.

Both are easy to implement. If #214 is acceptable for merging, then probably trimming the line would be the way to go, just for the sake of consistency.

And the implementation question is, in which of the *vcf_hdr_read* and *bcf_hdr_parse_line* functions the changes should be done? *bcf_hdr_parse_line* seems better to me, but then the way it notifies errors needs to be improved too.

**Comment by jmarshall** [comment]
Fixed by PR #267.
