### ISSUE TITLE
tabix -H does not work for VCF

### ISSUE THREAD

**Issue by mktrost** [samtools/htslib#249]
Tabix help says: 
   -H, --only-header          print only the header lines
But when I try running with that option on a vcf, it returns nothing.  If I use an old version of tabix, I get the VCF header.

**Comment by jmarshall** [comment]
This worked in 1.1, but was broken in 1.2 and 1.2.1 by a ed3efe902d11a65a2f782bf40051e6cf06942fc3 thinko.
