### ISSUE TITLE
Cannot seek over (1 << 16) - (1 << 8) - 1

### ISSUE THREAD

**Issue by yelliver** [samtools/htslib#264]
I have an original file with size of 770.048 bytes
```
    int BUFF_SIZE = 1024;
    size_t pos = (1 << 16) - (1 << 8); //65279 < fileSize
    bgzf_seek(f, pos, SEEK_SET);
    ssize_t size = bgzf_read(f, buff, BUFF_SIZE); //size == 0
```
And when
```
    int BUFF_SIZE = 1024;
    size_t pos = (1 << 16) - (1 << 8) - 1; //65279
    bgzf_seek(f, pos, SEEK_SET);
    ssize_t size = bgzf_read(f, buff, BUFF_SIZE);
    fprintf(stderr, "\nCurrent position: %d\n", bgzf_tell(f));
``` 
The current position returned by bgzf_tell should be pos + size, but the result is 1131480063 > fileSize

**Comment by jmarshall** [comment]
As you may have just realised, 1131480063 is actually a representation of 17265:1023, i.e., about a thousand bytes into a BGZF block starting at 17265, which is well within your 770KB file length.

I assume any problems here are now resolved…

**Comment by yelliver** [comment]
Now I know that I haven't understand this lib yet. So can I really seek random position in BGZF file?

**Comment by tommycarstensen** [comment]
@yelliver Yes, also check this blog post from 2011 by Peter Cock:
http://blastedbio.blogspot.com/2011/11/bgzf-blocked-bigger-better-gzip.html
