### ISSUE TITLE
htslib doesn't set User-Agent when using libcurl, which upsets some? proxies

### ISSUE THREAD

**Issue by daviesrob** [samtools/htslib#295]
Not sure how globally-relevant this is, but...

I tried using the new libcurl plugin to download a file using https via a squid proxy and got:

```
$ HTS_PATH=. ./htsfile -c 'https://genome.ucsc.edu/goldenPath/help/examples/samExample.sam'
htsfile: can't open "https://genome.ucsc.edu/goldenPath/help/examples/samExample.sam": Success
```

while trying the same using curl works:

```
curl https://genome.ucsc.edu/goldenPath/help/examples/samExample.sam | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  294k  100  294k    0     0   156k      0  0:00:01  0:00:01 --:--:--  157k
   1986   24241  301122
```

After a bit of stracing, it looks like the difference is that curl sends a User-Agent string.

htslib does this:
```
sendto(3, "CONNECT genome.ucsc.edu:443 HTTP/1.1\r\nHost: genome.ucsc.edu:443\r\nProxy-Connection: Keep-Alive\r\n\r\n", 97, MSG_NOSIGNAL, NULL, 0) = 97
[...]
recvfrom(3, "HTTP/1.0 407 Proxy Authentication Required\r\nServer: squid/3.1.21\r\n...", 16384, 0, NULL, NULL) = 3649
```

curl does this:
```
sendto(3, "CONNECT genome.ucsc.edu:443 HTTP/1.1\r\nHost: genome.ucsc.edu:443\r\nUser-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3\r\nProxy-Connection: Keep-Alive\r\n\r\n", 210, MSG_NOSIGNAL, NULL, 0) = 210
[...]
recvfrom(3, "HTTP/1.0 200 Connection established\r\n\r\n", 16384, 0, NULL, NULL) = 39
```

Telling curl not to send a user-agent stops it from working:
```
curl -H 'User-Agent:' https://genome.ucsc.edu/goldenPath/help/examples/samExample.sam | wc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Received HTTP code 407 from proxy after CONNECT
```
So it looks like we need to get htslib to send a User-Agent string to stop poxy proxies from dropping https connections on the floor.

**Comment by jmarshall** [comment]
I have a feeling we have an especially badly configured squid in this regard.  Hacking in even `User-Agent: foo` makes it work.

Anyway, it's easy to add a User-Agent and I want to add the equivalent for the iRODS backend too.  At least, it's easy to add one like

    User-Agent: htslib/VERSION

It might be nice to arrange for callers to override this (`User-Agent: samtools/VERSION`) but that can be a separate API addition some day…

**Comment by jmarshall** [comment]
> htsfile: can't open "https://genome.ucsc.edu/…/samExample.sam": **Success**

I'm still working on fixing that error message, which comes down to [proxy errors being reported separately](http://curl.haxx.se/mail/lib-2015-10/0137.html).
