### ISSUE TITLE
htslib fails to install to prefix directory

### ISSUE THREAD

**Issue by wkretzsch** [samtools/htslib#296]
Hi,
I checked out the current `develop` branch, which is commit 2e4226f. I then attempted to build and install htslib with the commands:
````
autoconf
./configure --prefix=$HOME
make CFLAGS='-g -Wall -O3' -j 16
make install
````
but I get the following messages and an error from `make install`
````
mkdir -p -m 755 /homes/kretzsch/bin /homes/kretzsch/include /homes/kretzsch/include/htslib /homes/kretzsch/lib /homes/kretzsch/share/man/man1 /homes/kretzsch/share/man/man5 /homes/kretzsch/lib/pkgconfig
test -n "" && mkdir -p -m 755 
Makefile:356: recipe for target 'installdirs' failed
make: *** [installdirs] Error 1
````

I can get htslib to install if I comment out the line
````
test -n "$(BUILT_PLUGINS)" && $(INSTALL_PROGRAM) $(BUILT_PLUGINS) $(DESTDIR)$(plugindir)
````
in the file `Makefile` and install with the command
````
make install plugindir=$HOME/libexec
````

As I did not configure with plugins enabled, I would expect htslib not to create or touch `$HOME/libexec/htslib`.  I'd submit a patch, but I'm not sure what the best way would be to implement a fix here.

**Comment by jmarshall** [comment]
Odd; I tested that, but apparently too briefly.  It needs `|| true` or so on the end, or probably rewriting with `if`.  Don't worry, I'll take care of it.
