### ISSUE TITLE
Potential uncaught write error in hts_idx_save_as()

### ISSUE THREAD

**Issue by atks** [samtools/htslib#298]
We've been indexing 100,000s of files and occasionally (~ 3 cases) the indexing fails and our pipeline fails to catch the error.  The error is not reproducible. 

A possible reason is that in hts_idx_save_as() which we are using, the return value from bgzf_write() is not tracked and no error is returned if it fails (), i.e. a negative value is returned. 

See: https://github.com/samtools/htslib/blob/develop/hts.c#L1491
https://github.com/samtools/htslib/blob/develop/hts.c#L1495

**Comment by jmarshall** [comment]
Fixed now that PR #271 has been merged.
