### ISSUE TITLE
samtools: -r <regionspec> is MUCH faster than -l <regionfile.bed>

### ISSUE THREAD

**Issue by jblachly** [samtools/htslib#304]
mpileup `-r <regionspec>` and `-l <regionfile.bed>` appear to operate in different fashions. Indeed, the manual indicates that -r requires an indexed BAM but does not mention this requirement for -l

For ten 2-3 GB RNA-seq BAM files (each indexed), `-r` completes in < 5 seconds (usually faster), whereas `-l` for the exact same 20nt window takes > 5 minutes

see also my other issue, issue#305

**Comment by dpryan79** [comment]
Yeah, `-r` grabs a single region while `-l` can be used for multiple. This isn't an issue, they're just doing different things.

**Comment by jkbonfield** [comment]
The reason for the difference in speed is that -r uses the BAM index to do random access while -l does linear streaming, filtering in/out regions specified in the bed file.

This confused me too, and needs better explanations IMO.  However the intention is that you use both simultaneously.  -r to narrow down your search to a general area (eg a gene) and -l to then filter that area on specific sites.

**Comment by jblachly** [comment]
Fascinating and puzzling. Is there a reason why `-l` doesn't/shouldn't/can't use the BAM index to seek to the start site of each range?

**Comment by jmarshall** [comment]
Several reasons.

For example, depending on the nature of your BED file (e.g., consider lots of separate exons within a small region) there can be a trade-off between seeking to each exon range in turn, and just seeking to the small region and filtering the whole region.  In different circumstances, different strategies will be faster.

Probably one day someone will write a "query optimiser" for BED files.  In the meantime, you get to do it yourself with a judicious combination of `-r` and `-l`.

This has been discussed on the mailing lists from time to time, e.g. [here](https://sourceforge.net/p/samtools/mailman/message/28530778/).
