### ISSUE TITLE
samtools: mpileup -r <regionspec> or -l <regionfile.bed> includes wrong areas

### ISSUE THREAD

**Issue by jblachly** [samtools/htslib#305]
`samtools mpileup -r chrA:nnn-mmm` includes region chrA:nnn-mmm correctly, but for some combinations of BAM files it also returns pileups from the same coordinates on other contigs, for example chrF:nnn-mmm and chrQ:nnn-mmm

It is not yet clear to me under what circumstances this behaviour is triggered. I have only experienced this when passing a list of bamfiles with `-b`, and notably when passing the following
`-b <(head bamfiles.txt | tail -n [1..x])`
to narrow down to a specific file that could trigger it, I triggered the behaviour at `tail -n 4`. However, passing the 4th bamfile ALONE does not trigger the error.

This behaviour happens with both `-r` but NOT `-l`; see also my other Issue#304

**Comment by jblachly** [comment]
I need to correct the above: the error was NOT triggered when using `-l`, but as I mentioned `-l` is abysmally slow.

**Comment by jkbonfield** [comment]
Closing this as it doesn't sound like an error.  The -l being slow issue is a different thing (streaming vs random access).

Feel free to reopen the ticket if I've misinterpreted your last comment.
