### ISSUE TITLE
htslib dev branch cannot compile

### ISSUE THREAD

**Issue by atks** [samtools/htslib#307]
test/sam.c: In function ‘faidx1’:
test/sam.c:186:5: warning: ‘faidx_fetch_nseq’ is deprecated (declared at ./htslib/faidx.h:94): Please use faidx_nseq instead [-Wdeprecated-declarations]
     n = faidx_fetch_nseq(fai);
     ^
In file included from /usr/include/fcntl.h:252:0,
                 from bgzip.c:30:
In function ‘open’,
    inlined from ‘main’ at bgzip.c:249:27:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:51:24: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments
    __open_missing_mode ();

**Comment by jmarshall** [comment]
Already fixed.
