### ISSUE TITLE
Missing symbols in htslib 1.3

### ISSUE THREAD

**Issue by satta** [samtools/htslib#311]
Hi,

I'm trying to update Debian's htslib package to the recently released version 1.3. This worked nicely with the exception of a few exported symbols having disappeared from the shared library, most of which were either made static, replaced by a macro or renamed. This would cause the ABI version to be bumped in Debian, which is probably not intended for a minor version update like the new 1.3. I was able to add some  wrappers for most of them (see attached [fixup_symbols.patch.txt](https://github.com/samtools/htslib/files/71600/fixup_symbols.patch.txt)) to ensure they are still in the library for backwards compatibility.

Three more puzzle me a bit:
```
libhts.so.1 libhts1 #MINVER#
- MD5_Final@Base 1.0
- MD5_Init@Base 1.0
- MD5_Update@Base 1.0
+#MISSING: 1.3-1# MD5_Final@Base 1.0
+#MISSING: 1.3-1# MD5_Init@Base 1.0
+#MISSING: 1.3-1# MD5_Update@Base 1.0
```

It appears like at some earlier point in time libhts exported these OpenSSL functions in its own symbol table, and now that the implementation changed in 1.3 they are gone. I have simply wrapped these as well (though I doubt anyone linking to the shared htslib library uses them) -- is the new internal implementation really binary compatible to the OpenSSL one? Can I do this?

I would be glad to get some advice whether my patches make sense... thanks in advance!

Happy holidays,
Sascha

**Comment by jmarshall** [comment]
`bcf_empty1()` was previously not declared or even mentioned in a header file, so was not useable in previous htslib releases.  Effectively `bcf_empty()` and `bcf_empty1()` have been **freshly added** to the public htslib API in 1.3.  See d4482eb578aada0080eb30239ff57e9f6a6de93b for details.

`int32_get()` and `int32_put()` were internal functions private to the library.  They were not declared in any header file and were not part of the API.  Similarly `hts_idx_load_local()` is not declared in any header and is not part of the API, so making it `static` was intended and does not affect either public API or ABI.

`MD5_Update()`/`MD5_Final()`/`MD5_Init()` were badly-named internal functions private to the library.  Defining these functions with their OpenSSL names (and via implementations unlikely to be using the context data compatibly) was a bug, and removing them fixed the bug.  See 3accd1934472e2bdd501404f4c1a2e570f868cd1 and PR #180 for details.

There were no declarations for these `MD5_*` functions in HTSlib's header files and they were not part of the HTSlib API.  To be affected by this change, client code would have to be including declarations from OpenSSL headers and linking against libhts.so and libssl.so, in which case functions previously satisfied by libhts will be satisfied by libssl and all will be well; or it would have to be including OpenSSL headers but linking only against libhts.so, in which case it will fail and deservedly so.

None of these symbols that have been removed from the library are part of the public HTSlib API, and none of them even appear in previous releases' public header files.  Thus to use these symbols, client code would have had to go out of its way to create its own declarations for these functions — which is a kind of client code that essentially **no** library supports.

We considered each of these symbol removals as we made them, and judged in each case that as they are not part of the documented/supported HTSlib API their removal does not cause backwards-compatibility problems and does not constitute a change in the library's public ABI.  Therefore we considered that no soversion bump was necessary.

Now that you have the rationale for each case, we hope that Debian will agree that neither the proposed _fixup_symbols.patch.txt_ wrappers nor a soversion bump are needed.
