### ISSUE TITLE
VCF parsing errors not propagated from the synced reader

### ISSUE THREAD

**Issue by pd3** [samtools/htslib#318]
When the reader encounters an error while parsing VCF or BCF (https://github.com/samtools/htslib/blob/develop/synced_bcf_reader.c#L457) it merely stops processing the stream but has no way of propagating the error.

Ideally the bcf_sr_next_line() should return a negative value on errors but this is backward incompatible, see the recommended usage https://github.com/samtools/htslib/blob/develop/htslib/synced_bcf_reader.h#L41.

Alternatively a new function could be added that checks for any errors encountered while processing after the loop is done.

**Comment by jrandall** [comment]
PR #332 fixes this
