### ISSUE TITLE
Simple code to add a new FORMAT field and values to a record?

### ISSUE THREAD

**Issue by bioinformed** [samtools/htslib#327]
I'm working on adding VCF/BCF read/write capabilities to the pysam Python wrapper to htslib.  Reading has been fairly easy to implement, however I'm finding that writing/mutating access requires extremely low-level knowledge of the internal storage formats.  For example, the task of adding a new FORMAT field to a record and then populating the samples with non-missing data is turning out to be highly non-trivial.  

Before I spend much more time slogging through the inner bowels of the code, can anyone sanity check that this is indeed incredibly hard or else point me to the nice training-wheels API that I've obviously overlooked?

**Comment by pd3** [comment]
It shouldn't be hard, will this code help?
https://github.com/samtools/htslib/blob/develop/test/test-vcf-api.c#L111

**Comment by bioinformed** [comment]
Thanks for the pointer to the test code.  I didn't know that existed.  That said, it only covers the simplest case of adding FORMAT values to all samples at once.  The point of my pysam API is to be more flexible and hide many of the htslib API details.  Thus it was a pain to implement a transparent object-oriented API that allows efficient getting and setting of individual samples values.  My code has to handle many cases:

- when no memory has been allocated
- when a value can be set directly within the memory already allocated
- when a value does not fit within the current allocated memory, due to either too small an integer type, too long a string, or too many items.
- when the values happen to be for the GT field, which has distinct encoding and decoding rules

Anyhow, I was just complaining and have managed to tackle most of the complexity.  See lines 232-828 in [cbcf.pyx](https://github.com/bioinformed/pysam/blob/master/pysam/cbcf.pyx#L232).  Please let me know if there are any easy simplifications or areas where I'm making unsafe assumptions.
