### ISSUE TITLE
HTSlib should prefer its own headers when being compiled

### ISSUE THREAD

**Issue by jmarshall** [samtools/htslib#347]
If you have an old version of HTSlib installed in a built-in or `$CPATH` location, or otherwise have external copies of _hts.h_ etc available, building HTSlib itself should always use the headers within itself rather than external ones.

See #117, #205, and samtools/samtools#544 where this has been encountered before but the reporters keep closing the issues when they've been resolved for themselves but before we've sorted it out once and for all! :smile:

This probably comes down to combinations of `#include <htslib/hts.h>` vs `#include "htslib/hts.h"` vs `#include "hts.h"`, but this is complicated by the various subdirectories (perhaps _cram/cram_io.c_ wants to say `#include "../htslib/hts.h"`?) and the fixed `-I.` (but cf configuring in a separate build directory) used.

(There is probably also a samtools/etc followup, along the lines of _when building samtools, ensure that it's using the headers from the desired htslib_.  There the question of `<htslib/hts.h>` vs `"htslib/hts.h"` is more fraught, as `"…"` is not appropriate when building against an installed htslib.)

**Comment by jkbonfield** [comment]
Possible candidates in htslib for editing:

```
@ deskpro[samtools.../htslib]; egrep 'include <(htslib|cram)' {,*/}*.[ch]
cram/cram_io.h:#include <cram/misc.h>
htslib/khash_str2int.h:#include <htslib/khash.h>
test/test-regidx.c:#include <htslib/regidx.h>
test/test-vcf-api.c:#include <htslib/hts.h>
test/test-vcf-api.c:#include <htslib/vcf.h>
test/test-vcf-api.c:#include <htslib/kstring.h>
test/test-vcf-api.c:#include <htslib/kseq.h>
test/test-vcf-sweep.c:#include <htslib/vcf_sweep.h>
```

I don't think ../htslib/hts.h should be needed though -I ought to take precedence over CPATH.   (I'm not quite sure how come in samtools/samtools#544 this wasn't the case.)

**Comment by jkbonfield** [comment]
Maybe CPATH or -I ordering was changed for Centos?  Something to check. See:

https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html
https://gcc.gnu.org/onlinedocs/cpp/Environment-Variables.html#index-C_005fINCLUDE_005fPATH-205

Basically, it shouldn't be possible for #include "htslib/sam.h" to find anything other than the one in the htslib main directory itself provided -I. does what the gcc documentation states it does (and indeed verified does do on Ubuntu).  We're missing something here.
