### ISSUE TITLE
htslib has problems with positions above ~500000000

### ISSUE THREAD

**Issue by bunop** [samtools/htslib#348]
Dear all,

we faced an issue when dealing with vcf in plant genomes, which can have big chromosomes. Briefly, we can't extract with tabix positions above `5e8`, and also softwares which uses `htslib` have such issue. I've uploaded a [gist](https://gist.github.com/bunop/2ced1915e55e74348e62) with a sample VCF. Here are the instruction to reproduce the issue:

Download the latest htslib from [github](https://github.com/samtools/htslib.git). Compile code, then download `moved.vcf` from [gist](https://gist.githubusercontent.com/bunop/2ced1915e55e74348e62/raw/c1a6f2f6a7b35e9b9d284d2332b2b1dd0ab7d621/moved.vcf). Inspect last vcf lines with `tail`:

```
$ tail -2 moved.vcf | cut -f 1-7
12      1060240521      .       G       T       203.196 .
12      1070240615      .       C       A       378.781 .
```

Now pack the file with bgzip and index it with tabix:

```
$ ./bgzip moved.vcf 
$ ./tabix moved.vcf.gz
```

Finally, query the VCF using tabix and chrom `12`:

```
$ ./tabix moved.vcf.gz 12 | tail -2 | cut -f 1-7
12      520164811       .       G       A       73.6504 .
12      530164817       .       T       C       83.1434 .
```

All lines after 109 (POS `530164817`) were lost.

Thanks for your support.

**Comment by jmarshall** [comment]
The coordinates in the VCF file are fine up to 2<sup>31</sup> (about 2 billion), but the BAI and TBI index formats do not work beyond 2<sup>29</sup> (about 536 million).

The CSI index format on the other hand does support coordinates up to 2<sup>31</sup>.  If you repeat your sequence of commands but indexing the VCF with

> $ ./bgzip moved.vcf 
> $ ./tabix **--csi** moved.vcf.gz

your query command will produce the expected results.

**Comment by bunop** [comment]
thank you, I've indexed with `--csi` and `tabix` now works. Could you update the [tabix](http://www.htslib.org/doc/tabix.html) documentation? the `--csi` parameter has the same description of `--comment` parameter
