### ISSUE TITLE
Remote files should fail if the "Accept-Ranges" header is not present

### ISSUE THREAD

**Issue by david4096** [samtools/htslib#371]
When working with remote files it is assumed the remote server can use byte range queries, however, this functionality is not always available. If it is, the `Accept-Ranges` header should be present. http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

Currently, when accessing a remote file that does not support Accept-Ranges, htslib will still attempt to read blocks, which leads to IO errors.

Python's simple HTTP server does *not* support byte ranges and can be used to replicate (`python -m SimpleHTTPServer`).

**Comment by jmarshall** [comment]
Where exactly are you claiming this is assumed?  (Also, are you talking about the knetfile backend or the libcurl backend?)

If you try to do a seek (perhaps via an htsFile index or iterator), htslib will make a byte range request.  This will fail if the server does not support it, and the seek will fail.

OTOH purely streaming through a file does not cause a byte range request and works fine on such servers.

(See also pysam-developers/pysam#107 for other reasons why using SimpleHTTPServer for this game is less than ideal.)

**Comment by david4096** [comment]
@jmarshall I'm using the libcurl backend. I'll move over to pysam, thanks!

**Comment by jmarshall** [comment]
It turns out that the legacy knetfile backend **was** always emitting a `Range` header; fixed by fc062fb86bd5f0440f8725b801cdc516ae2ed80d.

Closing on the basis that the reporter appears to be happy…
