### ISSUE TITLE
FAIDX type inconsistency

### ISSUE THREAD

**Issue by reedacartwright** [samtools/htslib#372]
In `faidx.c`, the variable type for the length of a sequence is inconsistent.

-  `faidx1_t` uses `int64_t` 
-  `fai_build_core` uses `int64_t`
-  `fai_insert_index` uses `int`

As a result, the value may be narrowed when `fai_build_core` calls `fai_insert_index` to add a `faidx1_t` object.  I don't know if this is a bug or a feature.  `fai_fetch` assumes `int`, so narrowing is consistent with that.

**Comment by jmarshall** [comment]
Narrowing is not intended here, and it's easily fixed for this static function.  Less easily fixed for `fai_fetch()` et al as there are compatibility concerns for that public API function.

It's pretty much moot however, as SAM and BAM limit chromosome length to 2<sup>31</sup>-1 anyway: see [SAMv1.pdf](http://samtools.github.io/hts-specs/SAMv1.pdf) and also this [mailing list thread](https://sourceforge.net/p/samtools/mailman/message/31534601/).
