### ISSUE TITLE
Why set b_qual to 0 in tweak_overlap_quality()

### ISSUE THREAD

**Issue by sfchen** [samtools/htslib#396]
```C
        if ( bam_seqi(a_seq,a_iseq) == bam_seqi(b_seq,b_iseq) )
        {
            #if DBG
                fprintf(stderr,"%c",seq_nt16_str[bam_seqi(a_seq,a_iseq)]);
            #endif
            // we are very confident about this base
            int qual = a_qual[a_iseq] + b_qual[b_iseq];
            a_qual[a_iseq] = qual>200 ? 200 : qual;
            b_qual[b_iseq] = 0;
        }
```

For matched bases in overlap, why set b_qual[b_iseq] to 0 while increase a_qual[a_iseq], why don't increase both?

**Comment by pd3** [comment]
Hi, 
it's from the same reason we remove duplicates - overlapping read pairs sequenced the same DNA fragment twice.

**Comment by sfchen** [comment]
Did you mean for the overlapped bases, only one will be presented in, and the other will be removed from the pileup file?

**Comment by pd3** [comment]
Ideally the duplicated, lower quality, base would be removed from the pileup. However, for speed and simplicity, we only set its quality to 0. This way it becomes invisible to variant calling.

**Comment by sfchen** [comment]
See, thanks!

Closing this issue...
