### ISSUE TITLE
0-based formats like bed are queried using 1 based co-ordinates

### ISSUE THREAD

**Issue by abrown25** [samtools/htslib#407]
I was getting off-by-one errors since I assumed that the co-ordinates I used to query bed files should match the co-ordinate system of the file. If it's not possible/desirable to change this behaviour, could you update the documentation to make it clear co-ordinates are 1-based?

**Comment by jmarshall** [comment]
Which specific functions or tools did you run into difficulty with?

**Comment by abrown25** [comment]
Sorry, I mean when using tabix. I may have something wrong, but if I have a bed file with a line:

1  100	110   Gene

and I run tabix bedfile.bed.gz 1:110-120, it will extract this region. But in 1 based co-ordinates, these regions are 101-110 and 111-120 so they don't actually overlap.

**Comment by jmarshall** [comment]
The human-focused `seq:start-end` text notation is always one-based.

This is spelt out in the samtools man page, but not the tabix man page.  You are quite right that this should be clarified in the tabix man page and ideally also the tabix help/usage display.

**Comment by jmarshall** [comment]
(When both are expressed in the same 1-based inclusive text format as used on the tabix/samtools command line, your bed region named Gene is `1:101-110` and your command line one is `1:110-120`; we see that they do indeed overlap at one base.)
