### ISSUE TITLE
What's the latest stable release?

### ISSUE THREAD

**Issue by dbolser-ebi** [samtools/htslib#414]
Please add to the readme.

**Comment by mp15** [comment]
1.3.2

**Comment by jmarshall** [comment]
This information is on [the Releases tab](https://github.com/samtools/htslib/releases) and at <http://www.htslib.org/download/>.

**Comment by dbolser-ebi** [comment]
Thanks, I never saw the releases tab before!

**Comment by jmarshall** [comment]
GitHub's layout currently underemphasises it; this is isaacs/github#666 (and isaacs/github#769 but IMHO the former is the more sensible proposal).
