### ISSUE TITLE
tabix does not work for very large begin and end coordinates

### ISSUE THREAD

**Issue by XingGenimi** [samtools/htslib#427]
rs	1921	1921	chr1	949607	949608	G
rs	2032653	2032653	chrY	15591536	15591537	G
rs	2032664	2032664	chrY	15526694	15526695	C
rs	34289137	34289137	chrY	21751448	21751449	C
rs	76264143	76264143	chr1	982843	982844	G
rs	113737327	113737327	chr1	2160492	2160493	C
rs	137852297	137852297	chrX	9711676	9711677	G
rs	137852386	137852386	chrX	154225285	154225286	A
rs	137852387	137852387	chrX	154225247	154225248	C
rs	137852516	137852516	chrX	8553379	8553380	G
rs	137852553	137852553	chrX	601785	601786	C
rs	137852554	137852554	chrX	595468	595469	C
rs	137852554	137852554	chrY	545468	545469	C
rs	137852557	137852557	chrX	601570	601571	C
rs	137852557	137852557	chrY	551570	551571	C
rs	137852558	137852558	chrX	595378	595379	G
rs	137852558	137852558	chrY	545378	545379	G
rs	139739199	139739199	chr1	935070	935071	C
rs	145997634	145997634	chr1	1168075	1168076	C
rs	193922466	193922466	chrX	595421	595422	A
rs	193922466	193922466	chrY	545421	545422	A
rs	267606886	267606886	chr1	11855170	11855171	A
rs	374188319	374188319	chrX	595467	595468	G
rs	374188319	374188319	chrY	545467	545468	G
rs	376575233	376575233	chr1	2160485	2160486	C
rs	387906488	387906488	chrX	11312921	11312930	TTTTATTTG
rs	397514461	397514461	chrX	601576	601577	G
rs	397514461	397514461	chrY	551576	551577	G
rs	397514462	397514462	chrX	601577	601578	C
rs	397514462	397514462	chrY	551577	551578	C
rs	397518425	397518425	chrX	8507702	8507703	A
rs	398122889	398122889	chr1	2160487	2160496	GACCGCTCC
rs	398122914	398122914	chr1	2160484	2160496	TCCGACCGCTCC
rs	558454078	558454078	chr1	1167998	1167999	C
rs	587781266	587781266	chr1	17349148	17349152	AGAG
rs	672601312	672601312	chr1	949738	949739	G
rs	751668763	751668763	chrX	8553378	8553379	C
rs	751816384	751816384	chr1	1168000	1168001	C
rs	757235287	757235287	chrX	11312925	11312926	A
rs	759446340	759446340	chr1	17349147	17349148	T
rs	762606889	762606889	chr1	1168079	1168080	C
rs	764445293	764445293	chr1	1168080	1168081	C
rs	764859016	764859016	chr1	1167981	1167982	C
rs	768360897	768360897	chr1	2160489	2160490	C
rs	772413940	772413940	chr1	949737	949738	C
rs	775184604	775184604	chr1	1167993	1167994	G
rs	786200942	786200942	chr1	1168072	1168081	ATGCTGGCC
rs	786200943	786200943	chr1	1167980	1168002	CCCTGGAGCGGGAGCAGGCGCG
rs	786201005	786201005	chr1	949522	949523	C
rs	794728950	794728950	chr1	17349146	17349150	ATAG

--------
1. save this code into a try.bed file
2. bgzip try.bed
3. tabix -s 1 -b 2 -e 3 try.bed.gz
4. tabix -s 1 -b 2 -e 3 try.bed.gz rs:398122914-398122915  work
return "rs	398122914	398122914	chr1	2160484	2160496	TCCGACCGCTCC"
5. tabix -s 1 -b 2 -e 3 try.bed.gz rs:587781266-587781267  **DON'T WORK**
return nothing

**Comment by jmarshall** [comment]
Use `tabix -C` when you have coordinates beyond 2<sup>29</sup>.

The documentation says

> **-C, --csi** Produce CSI format index instead of classical  tabix  or  BAI style indices.

but it needs to also say **why** you would want to produce a CSI index.

**Comment by XingGenimi** [comment]
Thanks.  

Redid indexing with -C, then the search for the large coordinates worked perfectly.

I was indexing rsIDs from dbSNP, so that I could quickly query a rsID to get its genomic coordinates. (not a typical way to use tabix)

**Comment by lh3** [comment]
@XingGenimi you can actually use one integer column like:
```txt
rs 768360897  chr1 2160489 2160490 C
rs 772413940  chr1 949737 949738 C
```
and index with
```sh
tabix -s1 -b2 -e2 input.txt.gz
```

**Comment by XingGenimi** [comment]
👍
