### ISSUE TITLE
Tabix maximum index position

### ISSUE THREAD

**Issue by willmclaren** [samtools/htslib#435]
In indexing [opossum's rather large chromosome 1](http://www.ensembl.org/Monodelphis_domestica/Location/Chromosome?r=1) with tabix I've hit an issue.

The largest position it will index is 536870912, which is 2^29.

I find this surprising as I'd expect it to be 2^31 (INT_MAX) or 2^32 (UINT_MAX).

Worse still, this failure is completely silent, the only way you know is if you try to retrieve the data back. This tested just now on develop branch:

```
$ echo "1 536870912n1 536870913" | tr " " "\t" | tr "n" "\n" | bgzip -c > test.gz
$ tabix -s 1 -b 2 test.gz
$ tabix test.gz 1
1	536870912
$ gzip -dc test.gz
1	536870912
1	536870913
```

**Comment by mp15** [comment]
This is a limitation of the BAI format and is documented in that specification (http://samtools.github.io/hts-specs/SAMv1.pdf):

> In the BAI format, each bin may span 229, 226, 223, 220, 217 or 214 bp. Bin 0 spans a 512Mbp region, bins 1–8 span 64Mbp, 9–72 8Mbp, 73–584 1Mbp, 585–4680 128Kbp, and bins 4681–37448 span 16Kbp regions. This implies that this index format does not support reference chromosome sequences longer than 229 − 1.
> The CSI format generalises the sizes of the bins, and supports reference sequences of the same length as are supported by SAM and BAM.

I recommend you index in CSI mode.

**Comment by willmclaren** [comment]
Thanks @mp15 , was struggling to find that information.

Any disadvantages to using CSI as the general case?

**Comment by pd3** [comment]
CSI can be thought of as an extension of TBI, so no, it's safe to use. The only disadvantage is that older version of tabix cannot read it.
