### ISSUE TITLE
How to get alignments at special region?

### ISSUE THREAD

**Issue by vanney9** [samtools/htslib#449]
I`m using htslib-1.3.2. And I have the BAM and BAI file. Is there a way to get all the alignment records between a special region. Like  a region at : chr6:20000..30000.

**Comment by valeriuo** [comment]
Yes. Use one of `sam_itr_queryi`, `sam_itr_querys` or `sam_itr_regions` methods to generate an `hts_itr_t` iterator. Then use `sam_itr_next` on the iterator to get the alignments. See [sam_view.c](https://github.com/samtools/samtools/blob/develop/sam_view.c) for examples ([multi-region](https://github.com/samtools/samtools/blob/a6a160bba842d6afc3da061a8aa4f199fd7b729b/sam_view.c#L648-L669), [single-region](https://github.com/samtools/samtools/blob/a6a160bba842d6afc3da061a8aa4f199fd7b729b/sam_view.c#L714-L728)).
