### ISSUE TITLE
bgzf_is_bgzf checks validity of file based on unspecified behaviour of bgzf

### ISSUE THREAD

**Issue by kortschak** [samtools/htslib#451]
~~[`bgzf_is_bgzf`](https://github.com/samtools/htslib/blob/6d927dfa3192492f3015b1bc9a0026f585e93acc/bgzf.c#L1494) reads the first 16 bytes of the given file name and compares this to the magic block. The SAM specification for BGZF says that "an end-of-file (EOF) trailer or marker block should be written at the end of BGZF files", not the beginning.~~

~~Either `bgzf_is_bgzf` needs to `lseek(fd, -28, SEEK_END)` or the `pread` equivalent, so that valid bgzf files are not excluded from use by tabix. Note that `bgzf_check_EOF_common` does the correct thing here.~~

**Comment by kortschak** [comment]
I've just realised that is not what you are doing. You are not checking for the EOF marker block, you are checking that the file is actually a BGZF file. This is worse.

The spec leaves open the bytes that you are checking except in the EOF marker block. The only check that can be valid is of the first 4 bytes (more later) and `SI1`, `SI2` and `SLEN` for at least one extra field.

Related to this, the SAM spec notes that FLG should be 4. There does not appear to be any real reason for this. Why make this restriction?

**Comment by kortschak** [comment]
>Indeed. The clue is in the name of the function (bgzf_is_bgzf() — compare bgzf_check_EOF()) and in its documentation.

Yes, except the code does it a way that is clearly incorrect, So I was not sure.

>The real test whether a file is a BGZF file is whether it starts with an RFC-1952 GZIP member header that has an extra field containing a “BC” subfield. As there is a grand total of zero other subfield IDs in common (or even rare) use, the main BGZF implementations have always assumed that BGZF files have an exactly 6-byte extra field containing precisely one 2-byte “BC” subfield, and use a simplified test accordingly.

>Is this actually a problem? Have you seen or are you planning to make a BGZF-formatted file for which this assumption does not hold?

[Yes](https://github.com/biogo/hts/issues/57). [Fix](https://github.com/biogo/hts/pull/58).

>Stating that only this FLG bit may be set is likely unintended. Please raise an hts-specs issue if you think this is worthy of being addressed.

Thanks.

>Is this actually a problem? Have you seen or are you planning to make a BGZF-formatted file in which FLG would not be exactly 4?

The issue above.

**Comment by jmarshall** [comment]
> > Indeed. The clue is in the name of the function (bgzf_is_bgzf() — compare bgzf_check_EOF()) and in its documentation.
>
> Yes, except the code does it a way that is clearly incorrect, So I was not sure.

In the light of the assumptions that I explained, the code is correct.  You are asking (very graciously I'm sure) for (one of) those historic assumptions to be relaxed, which is a different thing.

Since `check_header()` and HTSJDK check only that the FLG.FEXTRA bit is set, it is not difficult to relax this check here too.  That done, it's possible that files with filename, comment, or header CRC extras (i.e. a value other than 4 for FLG) claiming to be BGZF files (even though that is pedantically outwith the BGZF spec) will now work throughout HTSlib.  Whether they would work with other implementations is an open question.

**Comment by kortschak** [comment]
Thank you.

> In the light of the assumptions that I explained, the code is correct. You are asking (very graciously I'm sure) for (one of) those historic assumptions to be relaxed, which is a different thing.

I don't understand how this claim can be made; specifications for BGZF and, arguable, tabix exist. So no assumptions are required other than that implementations follow the specification.

The spec says that a BGZF file header prefix looks like this (0xXX is don't care):

```
0x1f 0x8b 0x08 0x04 0xXX 0xXX 0xXX 0xXX 0xXX 0xXX 0xXX 0xXX ..(n bytes).. 0x42 0x43 0x02 0x00
```

(n bytes is due to the possibility of including additional extra subfields - allowed in RFC1952 *and explicitly* by the BGZF specification.)

The behaviour of `bgzf_is_bgzf()` was to check whether the header prefix looked exactly like:

```
0x1f 0x8b 0x08 0x04 0x00 0x00 0x00 0x00 0x00 0xff 0x06 0x00 0x42 0x43 0x02 0x00
```

This is clearly assessing the `is bgzf` status of the file on the basis of 8 (or more) bytes that are unspecified in the BGZF header specification.

The function of header checking is to provide a capacity to return a boolean indicating whether the given file path has a file which is a BGZF with p(FP) and p(FN) minimised. Now, p(FP) has a provably non-zero value without reading the entire file, however p(FN) has a zero minimum when the specification is followed (i.e. no non-specified behaviours are assumed). Given that refusing a correctly written BGZF is an undesirable behaviour and and the theoretical mininum p(FN) achievable is zero, I would argue that the implementation *was* incorrect. Whether this was due to a coding bug or an implementation design decision (the historical assumptions mentioned above) is not really relevant.

> Since `check_header()` and HTSJDK check only that the FLG.FEXTRA bit is set, it is not difficult to relax this check here too. That done, it's possible that files with filename, comment, or header CRC extras (i.e. a value other than 0x04 for FLG) claiming to be BGZF files (even though that is pedantically outwith the BGZF spec) will now work throughout HTSlib. Whether they would work with other implementations is an open question.

This is not what I'm asking for here.

Currently the BGZF spec requires that the header's 4th byte be 0x04. While that exists in the spec, I have to accept that a spec-compliant BGZF decompressor may refuse to accept headers with FLG.FNAME or FLG.FCOMMENT set (i.e. with the Name or Comment fields not zero). Thus the biogo/hts implementation of BGZF is a superset of the spec. However, with documentation that currently exists it can be ensured to be completely spec compliant, under user control.

I think that the spec *should* allow the use of FLG bits other than FLG.FEXTRA, but this is https://github.com/samtools/hts-specs/issues/181. I will not rely on any implementation accepting FLG != 0x04 prior to that spec change and will maintain documentation on biogo/hts that the Name and Comment fields should not be set if interoperability between it and other implementations is required.

**Comment by jmarshall** [comment]
The SAM(/BGZF/BAM) specification was not brought down from a mountaintop engraved on a tablet.

It is a historical document that was written in conjunction with the original implementations, mostly samtools, by the same authors.  In the old days, trying to understand the spec was hopeless without referring to the extant implementations.  These days the spec is rather better, but it remains wise to study the widely-used implementations as well if one is interested in interoperability.

It's great that you can write polemics like this.  However I would suggest your time would be better spent proposing clarifying spec pull requests than teaching the rest of us to suck eggs.  Thanks in advance.

**Comment by kortschak** [comment]
Thank you.

I have spent time trying to read the implementations, I have spent time trying to commit improvements to the code base and I have spent time trying to clarify the specifications. I all cases this has been time wasted. I have sent PRs that have languished for months, I have asked questions on the samtools-devel mailing list that have been ignored and I have filed issues against the specs asking for clarification that have not even yet been recognised by a member of the samtools github organisation. You will excuse me if I feel some degree of frustration when I have to deal with a spec that is more of a post hoc advisory.

**Comment by jmarshall** [comment]
> [In] all cases this has been time wasted.    [[citation needed](https://github.com/issues?utf8=✓&q=org%3Asamtools+author%3Akortschak)]

To be sure, 7 out of 12 successfully resolved is not a perfect record — but neither is it zero.

We do read all issues filed and questions posted on mailing lists, but sometimes they are a low priority or it is a deep question and there is no particularly good answer or …, so it is not always _apparent_ that they have most certainly not been ignored.  Perhaps we could sometimes do better at acknowledging things.

Our funders seem to want us to focus on Actually Doing Science, so sadly these specifications are always going to be imperfect sidelines.  So questions, issues, and proposed PRs from people like you are useful contributions to focus efforts on the parts of the specs that are unclear.
