### ISSUE TITLE
Support AWS Signature Version 4 authentication

### ISSUE THREAD

**Issue by jenniferliddle** [samtools/htslib#454]
Amazon S3 uses two types of signature, called type 2 and type 4.
htslib currently only supports type 2. Later regions in S3 (for example, eu-west-2 (ie London)) only support type 4.
HTSlib needs to support type 4 authentication in order to be used with more recent regions on S3.

**Comment by jmarshall** [comment]
Amazon says all regions (even the early ones) do support type 4, but I suppose there might be local installations that only support type 2.

I think it might be appropriate to use type 4 if you have a `region` (or `bucket_location` for _.s3cfg_) specified in your config file, or type 2 otherwise.

**Comment by daviesrob** [comment]
Fixed by #839
