### ISSUE TITLE
Index querying broken by 5869a67

### ISSUE THREAD

**Issue by pd3** [samtools/htslib#455]
This commit broke indexing, see test case here https://github.com/samtools/htslib/commit/5869a67c3c19aa9e2b3b356269dadaf9aff1c669#commitcomment-20454507

**Comment by jmarshall** [comment]
>  bcftools query -f'%POS\n' -r X:154931044-1000000000 chr20-X.bcf

Your index is of the usual 14:5 geometry, so allows chromosome lengths up to 2<sup>29</sup>.

1000000000 > 2<sup>29</sup>.  The following produces the expected result:

    bcftools query -f'%POS\n' -r X:154931044- chr20-X.bcf

as does this:

    bcftools query -f'%POS\n' -r X:154931044-536870911 chr20-X.bcf

You might wish to file a low-priority issue to make stupidly-large coordinates be treated the same as an open-ended region.

**Comment by pd3** [comment]
I lived under the impression that `.csi` indexes allow to index bigger chromosomes. In any case, the behavior is unexpected. The library should complain or handle this internally. Still considering this as a bug.

**Comment by jmarshall** [comment]
Already fixed.

**Comment by pd3** [comment]
Yes, just tested it. Your comment above somehow failed to mention it, instead seemed to offer a workaround. Thanks
