### ISSUE TITLE
Improve CRC in htslib

### ISSUE THREAD

**Issue by jkbonfield** [samtools/htslib#467]
The CRC32 supplied by zlib, as used in BAM and CRAM is ancient and slow.  (Why don't linux distributions replace the archaic zlib with one of the many newer and faster versions? Grrr!)

The remains of PR #361 after merging all the aux tag code is a faster CRC, but as mentioned in that PR it should be its own thing.  Since then I've found a better source of fast CRCs:  https://github.com/ebiggers/libdeflate

```
b21c634a	"../enwik9bwt1024"	830 ms	1203 MB/s     Zlib
b21c634a	"../enwik9bwt1024"	541 ms	1845 MB/s     Libdeflate -O3
b21c634a	"../enwik9bwt1024"	290 ms	3441 MB/s     Crc32 16-way (as PR361)
b21c634a	"../enwik9bwt1024"	76 ms	13139 MB/s    Libdeflate -O3 -march=native
```

The march=native build uses PCMULQDQ SIMD on x86-64 machines meaning it's around .62 cycles per byte.  This means we can speed up CRC further still, but not on default builds.  Libdeflate's code is a compatible license, so we'd need to decide whether to lift in the algorithm (just 1 or 2 files) or to add the option to externally link.

Probably externally link is a good choice as the library has a whole replacement of zlib and it's around 2.4x faster at both compression and decompression.

**Comment by kyleabeauchamp** [comment]
I think this issue can be closed now, right?

Also, it I've got a working bioconda build ready to be merged with libdeflate (https://github.com/bioconda/bioconda-recipes/pull/8521).  The speed improvements (with conservative optimization settings) are still pretty substantial!

**Comment by jkbonfield** [comment]
Yes well spotted and thanks.
