### ISSUE TITLE
Is the bgzip index format (.gzi) produced by faidx documented anywhere?

### ISSUE THREAD

**Issue by tfenne** [samtools/htslib#473]
I've been poking around in the code and issues trying to find a solid description of the `.gzi` file created when running `faidx` on a bgzipped fasta file, but the best I could find was a pretty loose description (that it contained the compressed and uncompressed offset for the start of each block).

Is there a description of exactly what's expected in that file?  And if not, would it be possible to add one, e.g. to the bgzip or faidx man pages?

The reason I'm asking for this is that `htsjdk` works well with uncompressed fasta files and indices, but doesn't yet support bgzipped indices, and I'd like to change that.

**Comment by daviesrob** [comment]
I'm not sure if it's documented anywhere beyond `bgzf_index_load()` in `bgzf.c`, but it's pretty simple.  The format is:

```
uint64_t number_of_entries;
struct Mapping {
   uint64_t compressed_offset;
   uint64_t uncompressed_offset;
} map_entries[number_of_entries];
```
Hopefully that's understandable.  The values are all stored in little-endian form.  The map_entries array stores the offset to each BGZF block in the compressed file, and the corresponding offset into the uncompressed data.  The first mapping `(0,0)` is not stored in the file.  If you look in `bgzf_index_load()` you'll see that it is pushed on the front of the list before reading the rest.

To seek to a position, you do a binary search to find the BGZF block with the highest uncompressed_offset less than or equal to the position you want.  You seek to the corresponding compressed offset, start decoding and discard any data between uncompressed_offset and the desired file position.

You're right that this should be documented properly somewhere.  I'll leave this open until we get around to doing it.

**Comment by tfenne** [comment]
Thanks @daviesrob - I was looking around for something like that.  That's perfect.

**Comment by mdshw5** [comment]
As you can see referenced above, I'm trying to figure out if the way I'm handling BGZF compressed FASTA in https://github.com/mdshw5/pyfaidx is compatible with htslib's implementation. Thanks for the useful description of the .gzi format. Currently I am storing virtual offsets in the .fai as this was the simplest way to implement t BGZF support, but I'm a bit confused and want to maintain htslib compatibility.  I have a couple of outstanding questions:

1. For uncompressed FASTA, the .fai stores the byte offsets to the start of each sequence entry. For the BGZF case does `samtools faidx` store BGZF virtual offsets or byte offsets pointing directly to the sequence entry start in the compressed data? 

2. If the .fai for BGZF compressed files does not store virtual offsets do you use the .gzi block indices to recreate virtual offsets?

**Comment by daviesrob** [comment]
A bit of a late answer, but:
1. `faidx` stores offsets to the uncompressed data.
2. For bgzf files, it uses the `.gzi` data to find the block that contains the desired offset.

The gzi format is now documented in the new [bgzf man page](http://www.htslib.org/doc/bgzip.html).

**Comment by 7PintsOfCherryGarcia** [comment]
Link [bgzf man page](http://www.htslib.org/doc/bgzip.html) broken. Find doc info here:
[bgzip(1)](http://www.htslib.org/doc/bgzip.1.html)

**Comment by jmarshall** [comment]
@7PintsOfCherryGarcia: See samtools/www.htslib.org#25.

**Comment by daviesrob** [comment]
It will be restored soon....
