### ISSUE TITLE
bcf_sr_next_line never returns

### ISSUE THREAD

**Issue by dancooke** [samtools/htslib#478]
Hi,

I've found a case where `bcf_sr_next_line` never returns with bcf input (test case attached). Confirmed in 1.3.2.

BW,
Dan

[htslib-bug.zip](https://github.com/samtools/htslib/files/813591/htslib-bug.zip)

**Comment by pd3** [comment]
Thank you for the bug report. 

I looked at this only briefly so far. It can be traced to `bcf_itr_queryi`, from some reason it never returns. This is an empty BCF, which contains only a header and no records. BCFtools can operate on the file without a problem.

**Comment by pd3** [comment]
This is should be now fixed

**Comment by dancooke** [comment]
Great, thanks! Any idea when this will be pushed into a release?

**Comment by jkbonfield** [comment]
I've just merged it, so hopefully very soon.  (Intention is early next week unless we spot any show-stoppers.)
