### ISSUE TITLE
Clarify --threads in --help output wrt 1.4 release

### ISSUE THREAD

**Issue by tseemann** [samtools/htslib#491]
The release notes say:
```
BAM and CRAM decoding is now multi-threaded
too, using the pool to automatically balance the number of threads
between decode, encode and any data processing jobs.
```

But the tools still say
```
      --threads INT       number of extra output compression threads [0]
```

The above implies its still just compression?

Does it depend on which tool or sub-command is used as to how the threads are used?

**Comment by jkbonfield** [comment]
Is this specifically just bcftools? For samtools they appear to all now say "Number of additional threads to use" to clarify that these are in addition to the main thread and to not be specific to any single task.

Bcftools appears to have a mixture of "number of extra output compression threads", "number of extra decompression threads" and "number of extra (de)compression threads" messages.  I think the decompression text was added by me, but maybe I didn't amend the tools that did multi-threaded compression already.

I suspect this is simply something which is incomplete.  For example bcftools isec looks to not use the thread pool directly (internally it'll be using it for the bgzf encoder, but that's output side only) so the usage message is probably correct.  This is therefore a defect that should be specifically raised as a bcftools issue instead.

**Comment by jkbonfield** [comment]
Addendum - I forget which tools I checked (sorry!) but I know for samtools not all tools gained threading support because adding it didn't help.  An example of this is phase and targetcut; the main algorithms are so slow that the time spent decoding the BAM file is basically irrelevant.   You can however still forcibly specify threads for a specific stream in samtools by using the --output-fmt-option and input-fmt-option opts or with eg ```-I bam,nthreads=4``` and ```-O bam,nthreads=4``` if those options are supported by the tool.

I don't know so much about the bcftools command line though.  I think it may lack the file format option support.

**Comment by tseemann** [comment]
I guess `bcftools` was my main concern.  I have of cores, but variant calling is slow. I wanted to check if more threads would parallelize it. But it seems they are mainly for compression/decompression?   I currently use freebayes-parallel wrapper script to divide reference into regions and then merge at end.

**Comment by jkbonfield** [comment]
The thread pool is a generic system designed to be used by any algorithm, but at the time of writing it the only threading was for bgzf / cram compression and a small amount in samtools sort.  I added bgzf decompression too (and cram threaded decompression which already existed but was tricky to enable).  It is clear there is a lot more that could be done, but it's not really an issue with the htslib thread pool itself.

Hence I'm closing this in favour of a bcftools specific issue (the erroneous usage text is in bcftools, but also the general comments about threading variant calling are there too).  It's probably best if you add this issue yourself (although I can do it if you prefer). 

Regards.
