### ISSUE TITLE
samtools sort (-m 4G vs -m 4.00G) - 1 temp file for EVERY read

### ISSUE THREAD

**Issue by blajoie** [samtools/htslib#494]
Hi!

**samtools 1.3.1
Using htslib 1.3.2**

It looks like if the -m param (for samtools sort) is passed a float, then samtools seems to default to either 4B? or 0 memory per thread...  With such a small memory allotment per thread, samtools creates a temp file for EVERY single read in the input!  This has the potential to create millions/billions of temp files....!

-m Set maximum memory per thread; suffix K/M/G recognized [768M]

e.g. 
_samtools view -F 4 -bh test.bam chr22 | samtools sort -n -T 8e2f521c0175 -@ 2 -m 4G - | samtools view_
This sorts AOK and uses 4GB per thread, creating a reasonable number of temp files.

_samtools view -F 4 -bh test.bam chr22 | samtools sort -n -T 8e2f521c0175 -@ 2 -m 4.00G - | samtools view_
The 4.00G seems to be interpreted as 4K (or perhaps 0?) memory per thread, and ends up placing EVERY read into its own separate temp file - **be careful running.**

1)  Please consider allowing float inputs to the -m param with a provided suffix (e.g. 4.00G,  0.004T)
2) Build in a check to never create more than NNNN temp files or default to a real-world memory size (e.g. 256M per thread?) or set some hard-lower-limit for the minimal memsize.

Thanks!

**Comment by kyleabeauchamp** [comment]
I've done this too :+1:

**Comment by jkbonfield** [comment]
This has already been fixed in 1.4.  Please upgrade to this.

It doesn't support floats, but it does emit a complaint on badly formatted values.
