### ISSUE TITLE
l_qname overflows for QNAMEs of 252 or more characters

### ISSUE THREAD

**Issue by jmarshall** [samtools/htslib#520]
5d114ebd8e9b80622769b8e575c5a9359cd51273 added extra NULs in memory to ensure that CIGAR data is 4-byte aligned.  To avoid breaking bad code that does not use the accessor macros, these extra bytes were included in in-memory `l_qname`.  For QNAMES of length ≥252 characters, this means that `l_qname` needs to have the value 256, but it is a `uint8_t`.

There are various ways of fixing this, though it's less straightforward to do so while minimising binary compatibility implications.

This is the cause of pysam-developers/pysam#447.

**Comment by dpryan79** [comment]
@jmarshall: Thanks for so quickly noticing this issue on the pysam repo!

**Comment by jmarshall** [comment]
PR #523 suggests a fix for this that I believe maximises binary compatibility.  If the libhts .so-version were to be bumped, less convoluted fixes become available.
