### ISSUE TITLE
`faidx` returns a 0-length sequence if a reference not in the index is suffixed with a colon

### ISSUE THREAD

**Issue by SamStudio8** [samtools/htslib#522]
```
[sam@tatl faidx]$ cat seq.fa
>one
ACGT
>two
ACGT
[sam@tatl faidx]$ samtools faidx seq.fa
[sam@tatl faidx]$ samtools faidx seq.fa 'one'
>one
ACGT
[sam@tatl faidx]$ samtools faidx seq.fa 'one:'
>one:
ACGT
[sam@tatl faidx]$ samtools faidx seq.fa 'three'
>three
[fai_fetch] Warning - Reference three not found in FASTA file, returning empty sequence
Failed to fetch sequence in three
[sam@tatl faidx]$ samtools faidx seq.fa 'three:'
>three:
```

**Comment by daviesrob** [comment]
This is down to a slight difference between the two places where `fai_fetch()` can exit if it doesn't find the sequence name in the index.

If it's just given the name, it will exit at https://github.com/samtools/htslib/blob/af89ccb/faidx.c#L489 after printing the warning and setting `*len = -2`.

If it finds a colon, it will first try the part before the colon, and if that fails it will try the whole string.  If both fail, it exits at https://github.com/samtools/htslib/blob/af89ccb/faidx.c#L481 setting `*len = 0` and without printing anything.

Arguably the second one is wrong.  I'll change it to do the same as the first.
