### ISSUE TITLE
v1.4.1 read bam possible bug?

### ISSUE THREAD

**Issue by bowentan** [samtools/htslib#534]
When I use htslib v1.4.1 to read a bam file, I found it could not read alignment properly. My codes are following.
```c++
samFile * bf = sam_open(bam_fn, "rb");
bam_hdr_t * bam_header = sam_hdr_read(bf);
bam1_t * aln = bam_init1();
sam_read1(bf, bam_header, aln);

cout << aln->core.n_cigar << endl;
cout << aln->core.l_qseq << endl;
```
The output is
```
0
2
```
The query sequence length was only 2 here. However after I returned to v1.3.2 and compiled the same codes, the problem was gone and the results were correct
```
2
90
```
The related bam alignment is
```
FCD1720ACXX:5:1108:9423:125276#ACTACAAG 163     chr1    10038   0       59M31S  =       10041   95      AACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCGAACCTTAGCCCGACCCCTGACCGTACCCCA      ;;9;>?==>==><<;<=6:<<=<>:;;;;=;<<<=><<<<<<;9===>889==>;*==################################   MC:Z:14M1D58M1D18M      BD:Z:GGFHHJJGGIEHHFEGDGGEEGDGGEEGDGGEEGDGGEEGDGGEEGDGGEEGDGGEEGFFFFFFFFFFFFFFFGGGGGGGHHHIIJGGGG MD:Z:59 PG:Z:MarkDuplicates     RG:Z:120725_I125_FCD1720ACXX_L5_HUMassXYGFAAAPEI-45  BI:Z:HHGIHKJHGIFJIGGIFIHFFIEJHGFIEIIFFHEIIFFHEIIFFHFIIGGIFJIGFIHHHHHHHHHHHHHHHIIIIIIJJJKKLLHHHH NM:i:0  MQ:i:0  AS:i:59 XS:i:62
```
So what's wrong here? Anyone encountered similar problems?

**Comment by jkbonfield** [comment]
Did you fully recompile your program (eg make clean first)?  The ABI (application binary interface) changed including some structure layout changes.

**Comment by bowentan** [comment]
@jkbonfield Sure, I did make clean and make distclean before I recompiled the library. But it did not work.

**Comment by jkbonfield** [comment]
Actually looking again I think it's the 16-bit to 32-bit n_cigar change which will have caused this slippage in structure offsets.

Anyway, specific cause aside, you also need to fully recompile your application, not just the htslib library.  If your application was built using one set of header files (from an old htslib) and you have relinked it against a newer htslib library version then the code *in your application* that unpacks BAM structures will be out of sync with the *code in htslib* that packs them.

The same issue can also apply if you're somehow finding htslib include files from one source and the libhts.so from somewhere else.

**Comment by bowentan** [comment]
@jkbonfield Owing to your suggestions, I have found the cause. Thanks for your detailed explanations!
