### ISSUE TITLE
CIGAR sequence pointer error in sam_read1

### ISSUE THREAD

**Issue by dzerbino** [samtools/htslib#535]
Hello,

I think I hit a bug reading CIGAR sequences in a [Bam file](https://github.com/Ensembl/WiggleTools/blob/master/test/bam.bam). 

If I use the generic code:
```
#include <stdlib.h>
#include <stdio.h>
#include "htslib/sam.h"
#include "htslib/hts.h"

int main(int argc, char ** argv) {
        samFile * fp = hts_open("bam.bam", "r");
        bam_hdr_t * header = sam_hdr_read(fp);
        bam1_t *aln = bam_init1();

        while (sam_read1(fp, header, aln))
                printf("%p\n", bam_get_cigar(aln));
}
```

I get: 
```
0x114
0x114
0x114
0x114
[...]
```

Which naturally is not a valid accessible memory block.

However, if I use the bam specific code:
```
#include <stdlib.h>
#include <stdio.h>
#include "htslib/bgzf.h"
#include "htslib/sam.h"
#include "htslib/hts.h"

int main(int argc, char ** argv) {
	BGZF * fp = bgzf_open("bam.bam", "r");
	bam1_t *aln = bam_init1();

	while (bam_read1(fp, aln))
		printf("%p\n", bam_get_cigar(aln));
}
```

I get:
```
0x4000003c
0x4000003c
0x4000003c
0x4000003c
0x4000003c
0x4000003c
[...]
```

Which is valid...

Am I doing something wrong?

Cheers,

Daniel

**Comment by jkbonfield** [comment]
Odd.  I get completely the opposite happen.  The generic interface works fine while the BGZF specific one does not.  Investigating.

However can you make sure you are finding the correct include files and that they match the same location as the library you're linking against?  ```cc -E``` should help with this.

**Comment by jkbonfield** [comment]
Ah ok the second example works once you add a call to bam_hdr_read() too.  I cannot explain why your first one is not working though as it works fine for me.  What is your actual compile / link line?  I just had a totally naive one:

```cc -g -Wall _a.c -I ~/work/samtools_master/htslib -L ~/work/samtools_master/htslib/ -lhts -lpthread -lz -llzma -lbz2
```

**Comment by dzerbino** [comment]
Rah, you are right, I was pointing to another copy of htslib, sorry for wasting your time, and thank you for teaching me the -E trick.
