### ISSUE TITLE
Errors while reading cram + index when there are only headers

### ISSUE THREAD

**Issue by AndreasHeger** [samtools/htslib#556]
Hi, this has come up on pysam (https://github.com/pysam-developers/pysam/issues/483).

When a CRAM file is created with only headers, samtools view XYZ.cram will work, but samtools view XYZ.cram chr1 will raise an error:
```
>samtools view -O CRAM ../tests/pysam_data/ex1.cram 'chr1:138532877-139175172' > empty_region.cram
>samtools view empty_region.cram
>samtools view -h empty_region.cram
@SQ     SN:chr1 LN:1575 M5:426e31835a6dfdcbf6c534671edf02f7     UR:/ifs/devel/andreas/pysam/tests/pysam_data/ex1.fa
@SQ     SN:chr2 LN:1584 M5:b6853ffe730ece50076db834dea18e3b     UR:/ifs/devel/andreas/pysam/tests/pysam_data/ex1.fa

> samtools view empty_region.cram chr1
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
```

This seems to be an issue in the sam_index_load2 function, though I could not immediately spot how it comes about.

**Comment by jkbonfield** [comment]
Thankfully the most mundane of bugs!  Thanks for the report.
