### ISSUE TITLE
Linear index is unused when querying with a .bai

### ISSUE THREAD

**Issue by tmdefreitas** [samtools/htslib#557]
The spec for the BAI index format describes in detail the linear index format and algorithm, yet in hts.c, the only code that references the index is when an hts_index is created, modified, or saved to a file. Notably, itr_query() does not reference the linear index when determining which file offsets need to be searched. 

Commenting out the declaration for lidx_t and removing the references to the object in hts_idx_init/load/destroy etc. still allows samview to function correctly, since the it's value is never read. 

Shouldn't itr_query() also check the linear index? And if it doesn't, is the linear index needed at all? Or am I missing something?

**Comment by jmarshall** [comment]
`hts_itr_query()` uses the `bins_t::loff` field, which is a generalisation of the linear index — the linear index corresponds to the `loff` fields in the lowest level row of the index, but CSI generalises this to have a `loff` field in the bins in the higher levels too.

When `hts_idx_load_core()` loads a BAI index, it reconstructs the whole tree's `loff` fields from the linear index loaded from the index file.

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/htslib/pull/1031
