### ISSUE TITLE
distribution does not include configure file

### ISSUE THREAD

**Issue by kemin711** [samtools/htslib#558]
The source.targ.gz file is missing the configure file

**Comment by jkbonfield** [comment]
The htslib-1.5.tar.bz2 is the distribution built by us as a release tar-ball, which does contain the configure script.

The "Source code" 1.5.zip and 1.5.tar.gz are built by github and simply contain an archived copy of the git repository.  These do not contain the configure script as we do not check in the auto-generated code.  Sorry this is confusing, but I am unaware of a way of preventing github from offering these files.

Please ignore the "Source code" links and use the named .tar.bz2 files instead.
