### ISSUE TITLE
CIGAR * treated as unmapped data

### ISSUE THREAD

**Issue by jkbonfield** [samtools/htslib#561]
See samtools/hts-specs#40 for background info.

https://github.com/samtools/htslib/blob/develop/sam.c#L999

```
// cigar
if (*p != '*') {
     ...
} else {
    _parse_warn(!(c->flag&BAM_FUNMAP), "mapped query must have a CIGAR; treated as unmapped");
    c->flag |= BAM_FUNMAP;
    ...
}
```

The above code modifies the SAM flags during reading, so a flag 16 with CIGAR ```*``` gets turned into flag 20 instead.  The SAM spec states quite clearly: "The CIGAR operations are given in the following table (set ‘*’ if unavailable)".   Note **unavailable**.  This does not imply *unmapped*.

Why is this modification done?  Does it break things elsewhere?  This issue dates back many years.

**Comment by jenniferliddle** [comment]
Isn't this the same issue as #430 ?

**Comment by jkbonfield** [comment]
Ah yes, closing this then.  Why was it totally ignored last year I wonder?
