### ISSUE TITLE
tabix on gff3 with overlapping genes on different strands failed

### ISSUE THREAD

**Issue by carrere** [samtools/htslib#564]
Dear team,

I'm facing a problem with the use of tabix on a gff3 containing overlapping genes on the opposite strand.

I sort my GFF3 with genometools using the following command:

`gt gff3 -sort -retainids`

I use the -sort option instead of the -sortlines in order to keep the canonical GFF3 structure (gene -> mRNA -> exon -> CDS ...).

So the sorted GFF3 looks like:

`
##gff-version 3
##sequence-region   C1 1 5000
C1	T	gene	335	4768	0	-	0	ID=gene:C1g1;Name=C1g1
C1	T	mRNA	335	4768	0	-	0	ID=mRNA:C1g1;Parent=gene:C1g1;Name=C1g1
C1	T	three_prime_UTR	335	371	0	-	0	ID=three_prime_UTR:C1g1.0;Parent=mRNA:C1g1
C1	T	exon	335	3668	0	-	0	ID=exon:C1g1.1;Parent=mRNA:C1g1
C1	T	CDS	372	1898	0	-	0	ID=CDS:C1g1.1;Parent=mRNA:C1g1
C1	T	five_prime_UTR	1899	3668	0	-	0	ID=five_prime_UTR:C1g1.2;Parent=mRNA:C1g1
C1	T	exon	3813	4768	0	-	0	ID=exon:C1g1.utr4;Parent=mRNA:C1g1
C1	T	five_prime_UTR	3813	4768	0	-	0	ID=five_prime_UTR:C1g1.4;Parent=mRNA:C1g1
###								
C1	T	gene	2112	3057	0	+	0	ID=gene:C1g2;Name=C1g2
C1	T	mRNA	2112	3057	0	+	0	ID=mRNA:C1g2;Parent=gene:C1g2;Name=C1g2
C1	T	five_prime_UTR	2112	2342	0	+	0	ID=five_prime_UTR:C1g2.0;Parent=mRNA:C1g2
C1	T	exon	2112	3057	0	+	0	ID=exon:C1g2.1;Parent=mRNA:C1g2
C1	T	CDS	2343	2708	0	+	0	ID=CDS:C1g2.1;Parent=mRNA:C1g2
C1	T	three_prime_UTR	2709	3057	0	+	0	ID=three_prime_UTR:C1g2.2;Parent=mRNA:C1g2
###
`

And tabix (v 1.5) crashes with the following error:

`[E::hts_idx_push] Unsorted positions on sequence #1: 3813 followed by 2112
tbx_index_build failed: C1.gff3.gz`

Is there a solution to use tabix without loosing the canonical structure of my GFF3 in that case ?

Sincerely,

Sebastien Carrere

**Comment by pd3** [comment]
It seems that the GFF was not sorted correctly? Also, what was the tabix command used to index the file? 

The file must be sorted by the first column (chromosome name) and the chromosome blocks must be sorted by the region start (4th column) and end (5th column). An easy way to check the order in the file using standard unix sort is:

      cat file.gff | grep -v ^# | sort -c -k1,1d -k4,4n -k5,5n

(This command assumes the chromosomes are sorted in sort's "dictionary order".)

**Comment by carrere** [comment]
The GFF3 is sorted using the genometools command:

gt gff3 -sort

that conserves the canonical order of gene features. Unfortunately, in some cases, canonical order is not the same as the region start order.

In my case, the two gene features are correctly sorted (gene:335..4768- then gene:2112..3057+) but the first gene as you can see ends (its 3' utr region) after the start of the second gene (these genes are overlapping on opposite strands).

That's why tabix (used with -p gff option only) crash.

My aim is to keep the canonical feature order, but it seems that tabix is not compliant.

**Comment by pd3** [comment]
I understand. Unfortunately, `tabix` requires the data sorted (for good reasons) as explained above.
