### ISSUE TITLE
hts_set_threads cleanup

### ISSUE THREAD

**Issue by brentp** [samtools/htslib#577]
it seems that using `hts_set_threads` leads to a memory leak that's visible after opening about 100 files.

Is there something in the API to allow cleaning up? If, the recommendation is to use the pool, then could that be added to the header (I think it's only mentioned in the .c).

**Comment by daviesrob** [comment]
Any memory used should be cleaned up by the time you've closed all of the files, so if that's not happening there's a bug somewhere. What exactly are you doing to get this?

If you're opening lots of files then you may want to manage the thread pool yourself as it's likely to be more efficient.  `hts_set_threads` is there to make the simple case of reading/writing a single file easier.  For more complicated cases it's better to make your own pool like test_view does [here](https://github.com/samtools/htslib/blob/e1380c820/test/test_view.c#L165).
