### ISSUE TITLE
hts.c test_and_fetch ignores fwrite errors

### ISSUE THREAD

**Issue by depristo** [samtools/htslib#580]
We recently discovered an bug in the test_and_fetch routine in hts.c. We were running on a filesystem that doesn't allow large files and were directly processing a BAM file stored in a GCS bucket. The automatic detection of the index worked as expected, but the run unexpected crashed.

The root cause is the unchecked call to fwrite in:

https://github.com/samtools/htslib/blob/cc55632993313cf4c23be82f8b13f7113d61e675/hts.c#L2285

That call should be updated to check that l bytes have been written and raise an appropriate error if a write failure occurred.

**Comment by daviesrob** [comment]
Yes, it should be checking.  Pull request incoming...
