### ISSUE TITLE
Request time too skewed error after 15 minutes on the same s3 file

### ISSUE THREAD

**Issue by bozhonghu** [samtools/htslib#588]
Currently the headers for a s3 file are created at the opening of the file and the same signature will be used to access the file but AWS does not allow a request with a signature with the time stamp over 15 minutes in the past. http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html
The requests will yield a 403 Permission Denied from the server and there is no attempt to resign or reopen the file. To fix this I added an update header callback to hfile_libcurl that will be set by hfile_s3 for s3 urls. The function will update the cURL headers for each seek request with a signature created from the current system time. I don't know if this is the best solution but it fixed the issue for me.

**Comment by daviesrob** [comment]
That's annoying.  Yes, some sort of callback approach to get the headers is likely to be the best answer.
