### ISSUE TITLE
Could there be a public cram API?

### ISSUE THREAD

**Issue by detrout** [samtools/htslib#619]
In discussing packaging issues with htslib in #616 we discussed that there are applications like SeqLib that are embedding copies of htslib to access the cram API.

In an ideal world there would be an official supported htslib cram api.

I filed an issue with SeqLib about this topic here: https://github.com/walaj/SeqLib/issues/21

**Comment by jmarshall** [comment]
There **is** an official supported HTSlib CRAM API, in _htslib/cram.h_. All SeqLib has to do is use it, and in fact the general htsFile API suffices for SeqLib's needs. Addressed by walaj/SeqLib#53.
