### ISSUE TITLE
VCF parsing speed

### ISSUE THREAD

**Issue by jkbonfield** [samtools/htslib#624]
VCF parsing is horribly slow.

On a small 1000 genomes combined VCF, I got 75% speed increase purely by replacing the strtoll calls with something naive.  Old code is in the diff, commented out:

```
diff --git a/vcf.c b/vcf.c
index f95ffc0..580b4e1 100644
--- a/vcf.c
+++ b/vcf.c
@@ -2039,7 +2039,11 @@ static int vcf_parse_format(kstring_t *s, const bcf_hdr_t *h, bcf1_t *v, char *p
                     int32_t is_phased = 0, *x = (int32_t*)(z->buf + z->size * m);
                     for (l = 0;; ++t) {
                         if (*t == '.') ++t, x[l++] = is_phased;
-                        else x[l++] = (strtol(t, &t, 10) + 1) << 1 | is_phased;
+                        else {
+                            uint64_t v = 0;
+                            while (*t >= '0' && *t <= '9') v = v*10 + *t++-'0';
+                            x[l++] = (v + 1) << 1 | is_phased;
+                        }
 #if THOROUGH_SANITY_CHECKS
                         assert( 0 );    // success of strtol,strtod not checked
 #endif
@@ -2057,7 +2061,11 @@ static int vcf_parse_format(kstring_t *s, const bcf_hdr_t *h, bcf1_t *v, char *p
                 int32_t *x = (int32_t*)(z->buf + z->size * m);
                 for (l = 0;; ++t) {
                     if (*t == '.') x[l++] = bcf_int32_missing, ++t; // ++t to skip "."
-                    else x[l++] = strtol(t, &t, 10);
+                    else {
+                        uint64_t v = 0;
+                        while (*t >= '0' && *t <= '9') v = v*10 + *t++-'0';
+                        x[l++] = v;
+                    }
                     if (*t != ',') break;
                 }
                 if ( !l ) x[l++] = bcf_int32_missing;
```

Now my trivial little numeric decoding loop doesn't bother with things like checking for EINVAL (eg starting with "z" instead of 0 to 9) or ERANGE (value overflows), but the existing parser wasn't checking for errors anyway so there is no difference here.

I'm not at the stage of wanting to do a PR on this yet as it's just the tip of the iceberg,  but given VCF is the dominant format (hardly anywhere shares bcf around due to incompatibilities in implementations) we really should try optimising it at least a bit.

**Comment by jkbonfield** [comment]
Of course one could be left wondering why on earth strtoll is apparently so slow!  I consistently run across these issues though; on any time critical code, don't use the standard string parsing functions.

**Comment by pd3** [comment]
@jkbonfield Wow!!! This is amazing work James.

**Comment by jmarshall** [comment]
> Of course one could be left wondering why on earth strtoll is apparently so slow!

Usually it's localisation. Does most of the slowness disappear with `LC_ALL=C bcftools blah blah`?

Anyway, yes writing one's own non-locale-aware simple versions for parsing non-locale-dependent files is definitely a win. (Sadly probably the existing `hts_parse_decimal()` is different enough that it can't just be dropped in here.)

**Comment by valeriuo** [comment]
Fixed by https://github.com/samtools/htslib/pull/1057
