### ISSUE TITLE
HTS_IDX_START support in cram?

### ISSUE THREAD

**Issue by jts** [samtools/htslib#625]
Hi,

I use the HTS_IDX_START [macro](https://github.com/samtools/htslib/blob/develop/htslib/hts.h#L494) with `hts_itr_query` to iterate over entire bam files. When running on a cram file, I get this error:

```
[cram_itr_query] tid=-3 not implemented for CRAM files -- Exiting Aborted
```

Is there a plan to implement this feature? Alternatively, is there an easy way to iterate over an entire cram file?

Thanks,
Jared

**Comment by jkbonfield** [comment]
That's a good spot.  I'm not sure why this wasn't implemented, but it should be fixed.

We'd need to experiment a bit to see how easy it is.  Have you tested whether opening the file (or seeking to the start if opened earlier) followed by an HTS_IDX_REST iterator works?  At the start of the file REST and START mean the same thing, and it looks like the code already supports HTS_IDX_REST.

**Comment by jkbonfield** [comment]
I forgot to add, to iterate over an entire file there is always the open and while(read...) style loop.  It's a different API to the iterator, which is a pain if you want to have code that permits the entire file or a specified region, but I guess this is what people have done in the past.

**Comment by jkbonfield** [comment]
Sorry for the spam, but we looked at this quick.  HTS_IDX_REST does indeed work on CRAM, hence opening the file and calling that instead will work.

We also know how to seek to the start of a file (just seek to the start of the 1st reference listed in the index file), so it is trivial to implement support for HTS_IDX_START too.  We'll work on this soon.

**Comment by jts** [comment]
Great, thanks for the quick response. My calling code is based on iterators ([here](https://github.com/jts/nanopolish/blob/master/src/common/nanopolish_bam_processor.cpp#L62)) so I'll try the seek/HTS_IDX_REST workaround for now. Could you help me out with the right way to seek to the start of the 1st reference in the index?

Jared

**Comment by jkbonfield** [comment]
I don't think there is a good external way to do this right now.  We can't ask it to seek to the first reference as if it is in the header but having no data aligned to it, I think, it'll fail.  I'm not sure whether this constitutes a bug or not.  Maybe seeking should work and let the caller discover we're beyond the reference on the next iterator call.

I think our plan of attack should be something like modifying ```cram_index_query```  to understand ```refid == HTS_IDX_START``` and scan through the appropriate index records and perform the relevant seek.  This could also be coded to make seeking to references with no data "work", in as far as positioning the file at the correct location in the data stream.  We'd then need to modify hts.c appropriately, but the changes there would be minimal.

**Comment by jts** [comment]
Ok, I'll wait for your fix. Thanks for the help.

**Comment by valeriuo** [comment]
Merged in https://github.com/samtools/htslib/tree/develop
