### ISSUE TITLE
Not building on OSX 12 (Sierra) 

### ISSUE THREAD

**Issue by skaller** [samtools/htslib#636]
I do:

```
autoconf
./configure CC=clang
make
```

and I get

```
clang -Wall -g -O2 -I.  -c -o hfile_s3.o hfile_s3.c
hfile_s3.c:84:2: error: No HMAC() routine found by configure
#error No HMAC() routine found by configure
 ^
hfile_s3.c:267:26: error: use of undeclared identifier 'DIGEST_BUFSIZ'
    unsigned char digest[DIGEST_BUFSIZ];
                         ^
hfile_s3.c:296:18: warning: implicit declaration of function 's3_sign' is
      invalid in C99 [-Wimplicit-function-declaration]
    digest_len = s3_sign(digest, &ad->secret, &message);
                 ^
1 warning and 2 errors generated.
make: *** [hfile_s3.o] Error 1
```

**Comment by skaller** [comment]
BTW: without CC=clang .. it builds. With CC=clang .. it builds. I ran make clean and autoreconf. Those auto* tools are all seriously broken. No idea what happened.

**Comment by daviesrob** [comment]
You need to run `autoheader` as well as `autoconf` (see [INSTALL](https://github.com/samtools/htslib/blob/189f77b83f/INSTALL#L57).)  Running `autoreconf` will have run both of these (along with some other programs that aren't needed) which is why it worked later.

**Comment by skaller** [comment]
Yeah, thanks.
