### ISSUE TITLE
cram_get_ref: Failed to populate reference error

### ISSUE THREAD

**Issue by jts** [samtools/htslib#639]
Hi,

I use htslib within nanopolish to read bam and cram files. Recently a user provided me with a locally-generated cram file to help me reproduce an issue they are having. When I run nanopolish with this cram I get connection timeouts and an error message:

```
connect: Connection timed out
Failed to populate reference for id 21
```

The relevant code appears to be here:

https://github.com/samtools/htslib/blob/develop/cram/cram_io.c#L2482

I suspect what is happening is that the reference information is read from the header of the cram file, but not fully populated, so it tries to resolve this and fails. My guess is this resolution fails because the header `UR` tag points to a path on the user's system, which is different than the reference path on my system. The connection time out is due to the node I'm running on not having internet access, so the fallback to querying the EBI times out.

The comment suggests that manually loading the .fai file (which I have) is a possible solution - how do I do this and tell `hts_itr_next` to use the .fai file to make everything work?

Thanks,
Jared

**Comment by jkbonfield** [comment]
From what I recall the UR file is used only as a last resort if nothing else worked.  M5 is the primary search method.  Hopefully you have M5: tags in your SQ header?  The samtools man page (sadly we haven't found time to write any for htslib) documents the search order under the "REFERENCE SEQUENCES" section.

Where this goes wrong is if you have no way for it find sequences by their md5sum.  As you can see it defaults to using EBI if no environment variables have been defined.

The way to get this working for non-networked machines is either to embed the reference segments in each slice of the CRAM file (this is doable with ```scramble -e``` or ```samtools view -O cram,embed_ref```) or for existing CRAM files to download and populate a directory of sequences named after their MD5 sums and set REF_PATH or REF_CACHE to point to this location.

We provide a tool for this in the samtools/misc directory named `seq_cache_populate.pl`.  It takes a fasta file and explodes it into a directory structure.

**Comment by jts** [comment]
Thanks. I do have M5 tags in the header but REF_PATH/REF_CACHE are not set. I'll try `seq_cache_populate.pl` as a workaround. For a longer term solution is it possible to force htslib via the C api to look first at the .fai file? I'd like to replicate the behaviour [here](
https://sourceforge.net/p/samtools/mailman/message/34746974/) where `samtools view` fails unless `-T` is provided.

Jared

**Comment by jkbonfield** [comment]
This is what the `hts_set_fai_filename` does, but there isn't a way to change the default search order to look at UR tags before M5 tags, so you have to manually call the function.

Long term though maintaining your own local cache of references will be the less painful solution.  It's how all of Sanger works and it avoids hammering EBI except when we need to populate new entries into the cache.

And yes, references are probably the achilles heel of CRAM.

**Comment by jts** [comment]
Ah ok - I didn't see your edits before writing my reply, sorry.

I agree setting a local cache of references is a good solution for many cases but here we're working with a genome assembly where keeping a local cache may be inconvenient. I appreciate the help though as I'm now able to read the cram file and make progress on my issue. I'll close this ticket.

**Comment by jkbonfield** [comment]
Ah yes fair enough, genome assemblies don't work well for references.  Infact I'd argue genome assemblies ought to have the reference embedded when making the CRAM file so the whole debacle is neatly sidestepped. :-)

Glad you got it working.
