### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [samtools/htslib#643]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [main](https://github.com/samtools/htslib/blob/936a3a72f1e8a500c3158e640f817f6a869948fc/bgzip.c#L165)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex") ⇒ [hts_tpool_init](https://github.com/samtools/htslib/blob/199ab974b250380290540a63a6d6c83fdc044544/thread_pool.c#L655)

**Comment by daviesrob** [comment]
These are being fixed as and when we can.  However, some are distinctly non-trivial due to the need to propagate the failure up to callers, which may or may not be written in a way that can handle the problem.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by daviesrob** [comment]
I'm very much in favour of this.  Pull requests to add more checks are welcome.

**Comment by elfring** [comment]
* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by jkbonfield** [comment]
No: we don't want additional dependencies, especially against complex C++ libraries, when a simple C method would suffice.

We also don't want C++ full stop unless there is a *very* good reason for it, and then we'd require it to be some plugin so we can avoid dependencies.  The main library is in C and we wish to keep it that way.

Incidentally, are all of your problems coming out of an automated tool, such as cppcheck?  (It's been on my wishlist for a while to go through such tools and generally have a code tidyup, but it takes time.)  If so, one issue listing problems found by cppcheck would be preferable to dozens of individual ones.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?
