### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [samtools/htslib#645]
I have seen that [no loop is used around a call](https://github.com/samtools/htslib/blob/44c6a36f2894b45ad6cb491833d27c6a2106410f/bgzf.c#L1495 "Update candidate: bgzf_check_EOF()") of the function “[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "Wait on a condition")”.
Would you like to reuse anything from my message on the topic “[spurious wakeup](https://groups.google.com/d/msg/comp.programming.threads/Gpe38hgZlsQ/1_1SRoCZgrsJ)”?

**Comment by lh3** [comment]
I didn't write that part of code, but I don't see what's wrong with it. Those few lines seem to be switching the context to a thread pool and wait until that pool finishes jobs. The main thread is not really waiting on conditions that may be modified by the thread pool.

**Comment by jkbonfield** [comment]
It's my code, but to be honest I forget all the intrincacies!

I think it's a non issue because it's a message from *one* thread (the background reader) to *one* other thread (the main loop) so there are no other threads to get spuriously woken up.

**Comment by elfring** [comment]
I find your assumptions unsafe and therefore inappropriate.
