### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [samtools/htslib#646]
Would you like to add the configuration script “[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads")” to [your build specification](https://github.com/samtools/htslib/blob/78dbcce8616228c5b4a5ac8a141386995e0747ea/configure.ac#L358 "Update candidate")?

**Comment by daviesrob** [comment]
All the platforms we target manage to build with pthreads at the moment.  We may consider this if we find one that doesn't work, but not until then.

**Comment by elfring** [comment]
Do you care for safer build checks because of variations for this software library?
