### ISSUE TITLE
Support operations with references stored in S3

### ISSUE THREAD

**Issue by jmtcsngr** [samtools/htslib#656]
Dear htslib maintainers,

Wondering if it will be possible to add support for references stored in S3.

Thanks!

**Comment by jkbonfield** [comment]
Does S3 have an http style interface?  Htslib supports http and https already via the hfile layer, which in theory could be used for all I/O including references.   It looks like most tools are using fai_load and fai_fetch for querying references, which rely on hopen and bgzf_open (which uses hopen).  So maybe this already works with an http interface.

There is also an s3 scheme in hfile_s3.c, so *maybe* we can do s3://blah.ref.fa already.

Do you have a public s3 bucket with a reference and a specific samtools command to test with? (samtools calmd was the one I thought of, but maybe you have a specific case which is coded differently).

**Comment by valeriuo** [comment]
Feature added by #1017
