### ISSUE TITLE
Is htslib threadsafe?

### ISSUE THREAD

**Issue by jordi-vaquero** [samtools/htslib#663]
I will start apoligizing if this questions has been previously answered, and I was unable to find it. 
I would like to know if htslib is threadsafe to be run in a multithredes environment, in this case I was trying to implement an openmp where all the threads reads different parts of a set of bam/cram files. 
Is that taken in care? Should each thread open the file on its own or they can share the fp?. 

Thanks again for your time.

Jordi

**Comment by jkbonfield** [comment]
The file pointers themselves are not thread safe, so each thread should open the file itself.

However htslib does have multi-threading capabilities of its own, for doing multi-threaded encode / decode.

Additionally there is a more general purpose thread pool (used internally by, eg, the BAM encoder and decoder) which permits your own work packages to be shared with the same pool of threads doing decompression and compression steps.  See https://github.com/samtools/htslib/blob/develop/htslib/thread_pool.h for the thread pool API.  The end of https://github.com/samtools/htslib/blob/develop/thread_pool.c#L984 also contains some example usage.

Obviously if the rest of your application is already openmp elsewhere then you're best off just using htslib in the non-threaded mode and letting openmp to the concurrency for you.

**Comment by jordi-vaquero** [comment]
One further question about this, 
What about hts_itr_query? There is no reason why a process can not open a file and then several threads read the the iterator in order to multithread going over the file, right?

**Comment by daviesrob** [comment]
You would need to put a lock around it.  Trying to use hts_itr_query() from more than one thread without a lock would almost certainly end in disaster.
