### ISSUE TITLE
Error compiling htslib

### ISSUE THREAD

**Issue by huangzhibo** [samtools/htslib#681]
When I  compile htslib 1.8/master, I get the following error:

In file included from ./hts_internal.h:29:0,
                 from cram/cram_index.c:65:
./htslib/hts.h:142:10: error：expected ‘,’ or ‘}’ before ‘HTS_DEPRECATED_ENUM’
     json HTS_DEPRECATED_ENUM("Use htsExactFormat 'htsget' instead") = htsget,
          ^
make: *** [cram/cram_index.o] error 1

**Comment by daviesrob** [comment]
That shouldn't happen.  What compiler are you using?  Could you also attach a full build log, please?

**Comment by daviesrob** [comment]
Assuming you got it to work.  Please re-open and post a build log if not.

**Comment by r-barnes** [comment]
I get this error with gcc version 6.5.0 20181026 (Ubuntu 6.5.0-2ubuntu1~18.10).

**Comment by daviesrob** [comment]
@r-barnes Please could you attach logs from `./configure` and `make`?
