### ISSUE TITLE
Issues of using tabix -R to extract given a bed file

### ISSUE THREAD

**Issue by mingliu815** [samtools/htslib#683]
Hi All,

I am using tabix -R to do extraction from a huge sorted and indexed WGS annotation file given a .bed file with all indexes that need to be filtered, but got problems-

- Say if I wanted positions from 1757280-1757281 at chromosome 1, the format in bed file is 
1 1757280 1757281
I did 'tabix -R annotationfile.bgz bedFile.bed', it didn't show any output, while if I did 'tabix annotationfile.bgz chr1:1757280-1757281', I can see the correct output.   

- If I did some small indexes, like to extract positions 10000-11111, I can get output either way. But for large indexes 'tabix -R' didn't work, only 'chr:Start-End' worked. And actually, if bed file includes a long list of indexes, 'tabix -R' could work for some of them but not all- output was not correct anyway.

Really confused on this. Does anyone have any idea or even meet the similar problems?

Thanks a lot,
Ming

**Comment by finswimmer** [comment]
Hello Ming,

you are using the options in the wrong order. If you want to use a region file you have to do it this way:

`tabix -R bedFile.bed annotationfile.bgz`

fin swimmer
