### ISSUE TITLE
regiidx.c LIDX_SHIFT

### ISSUE THREAD

**Issue by betteridiot** [samtools/htslib#685]
@pd3 In [regidx.c](https://github.com/samtools/htslib/blob/44c47501378e537632526b8e033985a912554093/regidx.c), is `LIDX_SHIFT` supposed to be 13 or 14? I thought it was 14 since the linear index is 2^14kbp.

**Comment by pd3** [comment]
This code is independent of and unrelated to .tbi and .csi indexing. Note also that there is a newer version of the same in bcftools.

**Comment by betteridiot** [comment]
Thank you
