### ISSUE TITLE
configure: error: libbzip2 development files not found

### ISSUE THREAD

**Issue by mianasbat** [samtools/htslib#702]
I am trying to install samtools on Centos 6.9 (Final). I download samtools-1.8 from sourceforge.
when I run `./configure` 
I get the error `configure: error: libbzip2 development files not found`
I checked the bzip2-devel `yum list bzip2-devel` and it is installed.
I reinstalled bzip2-devel `yum reinstall bzip2-devel` but no success.
I dont want to disable the bz feature. 
I dont know what to do now, please help.

**Comment by daviesrob** [comment]
Please could you send us copies of your config.log files?  If you're building from the samtools-1.8 release, we would want to see both `config.log` and `htslib-1.8/config.log`.

The best way to send them would be by adding them as an attachment to your reply.  Please don't cut and paste them into the reply box as they tend to get cut off just before the interesting parts.

**Comment by mianasbat** [comment]
Thanks for reply. Both the required files are attached.
[htslib_config.log](https://github.com/samtools/htslib/files/2030916/htslib_config.log)
[samtools_config.log](https://github.com/samtools/htslib/files/2030917/samtools_config.log)

**Comment by jmarshall** [comment]
Why/how do you have a CentOS 7 bzip2-devel package installed on your CentOS 6 machine?

(Your problem occurs because this package is disagreeing with the CentOS 6 bzip2-libs package that is installed, and will be fixed if you use a bzip2-devel package appropriate for your CentOS 6.9 computer.)

**Comment by mianasbat** [comment]
I removed bzip2-devel by rpm -e --nodeps bzip2-devel and now yum and rpm both not working. They say cannot open shared library libbz2.so.1 
I tried to build from source but it is giving error. I am looking it, any idea?

**Comment by mianasbat** [comment]
Okay rpm and yum started working after I copied the file from backup to
`cp /xyz/lib64/libbz2.so.1 /lib64/`
Now back to step 1 :)

**Comment by mianasbat** [comment]
Now I got the right versions of bzip2 and bzip2-devel (el6) using yum. The installation of htslib and samtools went well. Thanks a lot for your quick help.
