### ISSUE TITLE
M_PI undeclared

### ISSUE THREAD

**Issue by alicepeter** [samtools/htslib#707]
OS:MSYS_NT-6.1 x86_64
./configure
configure: loading site script /etc/config.site
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking location of HTSlib source tree... ../htslib-1.8
checking for NcursesW wide-character library... yes
checking for working ncursesw/curses.h... yes
checking for working ncursesw.h... no
checking for working ncurses.h... yes
checking for zlib.h... yes
checking for inflate in -lz... yes
checking for library containing regcomp... none required
configure: creating ./config.status
config.status: creating config.mk
config.status: creating config.h
config.status: config.h is unchanged

bam2bcf.c:453:48: **error**：‘M_PI’ undeclared (first use in this function); did you mean ‘__P’?
     return mann_whitney_1947(na,nb,U) * sqrt(2*M_PI*var2);

**Comment by pd3** [comment]
Apparently M_PI is not required by the C standard, so we may just add
````
#ifndef M_PI
#    define M_PI 3.14159265
#endif
````

**Comment by jkbonfield** [comment]
Does `./configure CPPFLAGS=-D_XOPEN_SOURCE=600` fix this?

I thought we had this working under Windows fine, but maybe it's a version of windows / gcc thing.  Regardless M_PI is defined in math.h only if using BSD extensions or XOPEN.  I think it may be needed for things like lgamma too, so it's possible the trivial fix above will just expose the next weakness.

**Comment by valeriuo** [comment]
This seems to be the configure process for [samtools](https://github.com/samtools/samtools), not htslib, under which you opened the issue.
Can you also show the content of the file **config.mk** from the samtools root folder?

**Comment by valeriuo** [comment]
Assumed fixed. Otherwise, reopen with requested info.
