### ISSUE TITLE
htsfile gives nonsensical results for .fq and .fq.gz files

### ISSUE THREAD

**Issue by tseemann** [samtools/htslib#719]
I do realise that `htsfile` does not specifically claim to work with fastq data, but i think it should be able to parse these common formats and return a correct answer:

```
$ htsfile reads.fq
reads.fq:       SAM version 1 sequence text

$ htsfile reads.fq.gz
reads.fq.gz:    SAM version 1 BGZF-compressed sequence data
```

**Comment by jmarshall** [comment]
You already reported this as #200 :smile:. I must dust off my “recognise particular text formats” branch…
