### ISSUE TITLE
error with cram queries and multiple threads.

### ISSUE THREAD

**Issue by brentp** [samtools/htslib#734]
with devel of samtools and htslib, the command:
```
samtools view -T Homo_sapiens_assembly38.fasta -c subset.cram chr22
```
gives exit code 0 and the expected number of alignments (1108).
however, when using multiple threads, an error is returned:
```
samtools view -@ 2 -T Homo_sapiens_assembly38.fasta -c subset.cram chr22
[main_samview] retrieval of region "chr22" failed due to truncated file or corrupt BAM index file
```
I have attached subset.cram and the corresponding index.

[cram-issue.tar.gz](https://github.com/samtools/htslib/files/2193439/cram-issue.tar.gz)

(re: https://github.com/brentp/mosdepth/issues/44)

**Comment by jmarshall** [comment]
Bisection shows that the problem was introduced with 6b6c8a3fdd5aee98f1ae7c50545c2d0ce2eb89a5.

**Comment by jkbonfield** [comment]
Thanks for the clear bug report - it really helped a lot.  I think the error is simply a failure to set the eof flag in one specific scenario, but I'm conducting further tests as experience shows this is very hard to get right.

Assuming I'm correct though, the incoming fix will be this:

```
diff --git a/cram/cram_decode.c b/cram/cram_decode.c
index f77fed4..8a831b1 100644
--- a/cram/cram_decode.c
+++ b/cram/cram_decode.c
@@ -3212,8 +3212,10 @@ static cram_slice *cram_next_slice(cram_fd *fd, cram_container **cp) {
         hts_tpool_result *res;
         cram_decode_job *j;
 
-        if (fd->ooc && hts_tpool_process_empty(fd->rqueue))
+        if (fd->ooc && hts_tpool_process_empty(fd->rqueue)) {
+            fd->eof = 1;
             return NULL;
+        }
 
         res = hts_tpool_next_result_wait(fd->rqueue);
```

**Comment by brentp** [comment]
thanks for the quick fix!
