### ISSUE TITLE
htslib-1.8 build fails, Centos 6.x, gcc 4.9.3

### ISSUE THREAD

**Issue by jbsysadmin** [samtools/htslib#735]
./configure build step passes without incident. However, at "make," all breaks down.

gcc -Wall -g -O2 -I.  -c -o kfunc.o kfunc.c
gcc -Wall -g -O2 -I.  -c -o knetfile.o knetfile.c
gcc -Wall -g -O2 -I.  -c -o kstring.o kstring.c
/tmp/ccptG2m8.s: Assembler messages:
/tmp/ccptG2m8.s:1392: Error: expecting string instruction after `rep'
/tmp/ccptG2m8.s:1488: Error: expecting string instruction after `rep'
make: *** [kstring.o] Error

Any leads? This is a depndency for another tool which fails to build.

**Comment by jmarshall** [comment]
This is nothing to do with htslib.

A little searching shows that [your GCC and binutils are incompatible with each other](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57017) and you need to upgrade binutils.

**Comment by jbsysadmin** [comment]
Thank you for the lead. I did have a more recent binutils, but didn’t include it in the path with the gcc at compile-time.
The related “lancet” build still failed, but not for this reason, as it got much further.

Regards,
-John
