### ISSUE TITLE
Inconsistent tabix results between index-jumping and streaming

### ISSUE THREAD

**Issue by juliangehring** [samtools/htslib#753]
Querying a tabix-indexed file yields different results, depending on whether the `-R` or the `-T` options is used to supply the query. Judging from the documentation, I would expect to get the same results in both cases. It seems that streaming (`-T`) through the file incorrectly outputs adjacent regions as well.

A small example:

`test.txt.gz`:
```
chr1	1	Site1
chr1	3	Site2
chr1	4	Site3
chr1	6	Site4
chr1	7	Site5
chr1	7	Site6
chr1	12	Site7
chr1	18	Site8
```

`query.txt`:
```
chr1	7	7
```

Query with index-jumping:

```sh
tabix -R query.txt test.txt.gz
```

```
chr1	7	Site5
chr1	7	Site6
```

Query with streaming:
`chr1:6` gets returned as well, this looks wrong.

```sh
tabix -T query.txt test.txt.gz
```

```sh
chr1	6	Site4
chr1	7	Site5
chr1	7	Site6
```

Generation of the tabix file used above:
```sh
bgzip -c test.txt > test.txt.gz
tabix -b 2 test.txt.gz
```

Tested with: htslib v1.8 and v1.9

**Comment by finswimmer** [comment]
Can confirm this. Looks like a off-by-one problem when using `-T`. Have also tried it with a bed file (just renamed the `query.txt` above to `query.bed`).

Using` -R` the result is empty (as expected). Using `-T` the result is now:
```
chr1	7	Site5
chr1	7	Site6
```

fin swimmer

**Comment by valeriuo** [comment]
Thanks for the comprehensive report! We managed to reproduce it.
