### ISSUE TITLE
tabix fails to load tbi file from AWS S3

### ISSUE THREAD

**Issue by andrew-slater** [samtools/htslib#763]
I was able to compile htslib (release 1.9) to work with AWS s3 to an extent. I can stream my bgzip compressed VCF file with htsfile confirming my credentials are authenticating. But if I try tabix on the same file, I get this error:
```
$ ./tabix -l s3://omicsofttest1/10samp.10kvar.vcf.gz
Could not load .tbi index of s3://omicsofttest1/10samp.10kvar.vcf.gz
```
If I try htsfile on the .tbi file, it gives a similar file access error but then does stream the contents of the tbi file so it seems it can access:
```
$ ./htsfile -h -v  s3://omicsofttest1/10samp.10kvar.vcf.gz.tbi | more
[E::hts_hopen] Failed to open file s3://omicsofttest1/10samp.10kvar.vcf.gz.tbi
\x1f\x8b\x08\x04\0\0\0\0\0\xff\x06\0BC\x02\0\xb7'\xed\x9d       \x98N\xe5\xff\xc6\xc7\x96$\xfcH\xf6-KJ\x89a\xacM\xb6\xec[vII\x92dKdM\xb2%I\xb2\xa5\xac\xd9\x92\x90%\x11"d\x8d\x
acY\x13I\x96RR\xa2\x90\xf4\xcfu\x7f\xee\xfe\xbf\xcee\x99\x193\x83_\xd3u\xe9s=\xdf\xb9\
```

**Comment by daviesrob** [comment]
Tabix hasn't been updated to support AWS S3 yet.  It is on our todo list, though.

**Comment by valenciacristian** [comment]
I don't know what you mean by this response. Tabix is partially working with aws s3. Is there a timeline/eta when tabix will fully support AWS S3?

**Comment by valeriuo** [comment]
@andrew-slater Your `s3://omicsofttest1/10samp.10kvar.vcf.gz.tbi` may be corrupt or not have the proper format. Can you rebuild it and try again?

**Comment by andrew-slater** [comment]
I re-tested with 10e6de3774cb1517f842b0b12943b69aab64db07 and tabix streaming from S3 is working now. Thanks!
