### ISSUE TITLE
bcf_hdr_add_sample leaves bcf_hdr_t in inconsistent state; segfaults

### ISSUE THREAD

**Issue by jblachly** [samtools/htslib#767]
Calls `bcf_hdr_add_sample` leave the header in an inconsistent state, whereby `h->n[2]` (the length of the samples dictionary) is not updated to match `h->dict`.  

Calling `bcf_update_format` with the header in an inconsistent state (in particular, when `h->n[2] == 0`) leads to segmentation fault due to bad memory access.

This can be mitigated with a call to `bcf_hdr_sync()`, or, as in your test code (`test/test-vcf-api.c`) by calling `bcf_hdr_write` which in turn calls the sync function if header is dirty (which it is).

That the length of the samples dictionary can be out of sync is apparently known in at least a general sense:
https://github.com/samtools/htslib/blob/b7e5a51abf0953b27ee469ad639d383d45b549b1/vcf.c#L149-L154

In any case, this is documented nowhere in particular and I just spent several hours working it out. 👎  
 Given that the calls to `bcf_hdr_add_sample` are unlikely to be called repetitively in critical loops (except maybe in exceptional cases such as 1kG ?) **does anyone object to including a sync after each sample is added?**

**Comment by pd3** [comment]
You are right, this should be documented. We don't want to sync after each added sample, though.

**Comment by jblachly** [comment]
@pd3 Thanks for your quick followup!

**Comment by jblachly** [comment]
Commit e7379a1 addressed my documentation concerns; thank you.
