### ISSUE TITLE
samtools error after simple install

### ISSUE THREAD

**Issue by bioprog** [samtools/htslib#770]
I have installed htslib on my system via configure / make / sudo make install. Then I tried to do the same with samtools ... configure **--with-htslib=system** / make / sudo make install. No errors. Then I type samtools on the command line:

samtools: error while loading shared libraries: libhts.so.2: cannot open shared object file: No such file or directory

What's the problem?

**Comment by daviesrob** [comment]
You may need to run `sudo ldconfig` so that the linker can find htslib.

You may also want to check that `/usr/local/lib` is in the set of directories that `ldconfig` searches, as it's not always put in by OS distributors.  Take a look in `/etc/ld.so.conf` and any files that it includes.

**Comment by bioprog** [comment]
I called `sudo ldconfig`. Right after that I called `samtools` and it works. So when I call an executable, the linker tells it at runetime where the libraries are. Interesting. I never had to do a `sudo ldconfig` to make something run.

**Comment by valeriuo** [comment]
This can also happen if the HTSlib folder is user supplied, which raises the question of whether we should bake the HTSlib path (the user supplied one) into the RUNPATH of the executable.
Otherwise, the install instructions should specify that the HTSlib path has to be acknowledged by the environment, either through `ldconfig` or `LD_LIBRARY_PATH`.

**Comment by gpatkinson** [comment]
> You may need to run `sudo ldconfig` so that the linker can find htslib.
> 
> You may also want to check that `/usr/local/lib` is in the set of directories that `ldconfig` searches, as it's not always put in by OS distributors. Take a look in `/etc/ld.so.conf` and any files that it includes.

Also had success with just calling sudo ldconfig, thanks for the help.
