### ISSUE TITLE
bgzf_mt not honoring number of threads?

### ISSUE THREAD

**Issue by daheise** [samtools/htslib#775]
I'm using htslib 1.9 in a project to do parallel bgzip. When giving `bgzf_mt` a number of threads, I observe that no matter the argument I give for n_threads, subsequent calls to bgzf saturate all processors.

My usage can be seen [here](https://github.com/daheise/libStatGen/blob/bfeea63bbae6260b4ddf3ecad310387bedea0302/general/BgzfFileType.cpp#L61).

**Comment by jkbonfield** [comment]
You seem to be using a mode string such as "w@4" for 4 threads, but leaving this in the mode string when opening the file.  I'm worried that the 4 there may be interpreted as a compression level, so w@1 vs w@9 may change far more than is expected.   I'm not 100% certain on that though.

I don't understand though why the number of threads would change outside of your control.  If you use things like htop, is it really running the a different number of threads as specified, or could something else be using the CPU?

**Comment by daheise** [comment]
>You seem to be using a mode string such as "w@4" for 4 threads, but leaving this in the mode string when opening the file. I'm worried that the 4 there may be interpreted as a compression level, so w@1 vs w@9 may change far more than is expected. I'm not 100% certain on that though.

That is a good point and you are correct. I noticed that `mode2level()` breaks on encountering the first number. Since compression level is optional, then the number used for threads could be interpreted as a compression level. I will need to think more about the strategy here. In my code at the moment, I am not using the mode string.

>If you use things like htop, is it really running the a different number of threads as specified

Yes, this is the output from `ps -T` when using `bgzf_mt` hard coded with nthread=1, n_sub_blocks=1 (I think the latter is ignored in the current implementation?)

`bgzf_mt(bgzfHandle, 1, 1);`

```
$ ps -Ta
   PID   SPID TTY          TIME CMD
  5945   5945 pts/0    00:00:23 minimac4
  5945   5956 pts/0    00:00:00 minimac4
  5945   5957 pts/0    00:00:13 minimac4
  5945   5971 pts/0    00:00:00 minimac4
  5945   5972 pts/0    00:00:20 minimac4
  5945   6075 pts/0    00:00:02 minimac4
  5945   6076 pts/0    00:00:00 minimac4
  5945   6077 pts/0    00:00:00 minimac4
  5945   6078 pts/0    00:00:01 minimac4
  5945   6079 pts/0    00:00:00 minimac4
  5945   6080 pts/0    00:00:01 minimac4
  5945   6081 pts/0    00:00:00 minimac4
  5945   6082 pts/0    00:00:01 minimac4
  5945   6083 pts/0    00:00:00 minimac4
  5945   6084 pts/0    00:00:01 minimac4
  5945   6085 pts/0    00:00:00 minimac4
  5945   6086 pts/0    00:00:01 minimac4
  5945   6087 pts/0    00:00:00 minimac4
  5945   6088 pts/0    00:00:01 minimac4
  5945   6089 pts/0    00:00:00 minimac4
  5945   6090 pts/0    00:00:01 minimac4
  5945   6091 pts/0    00:00:00 minimac4
  5945   6092 pts/0    00:00:01 minimac4
```

This is the output with `bgzf_mt` commented out:

```
$ ps -Ta
   PID   SPID TTY          TIME CMD
  6711   6711 pts/0    00:00:18 minimac4
```

**Comment by jkbonfield** [comment]
Are you opening multiple files?  If so, this will be adding N threads for each and every file.

There is a newer interface where you can supply a thread pool, which can then be shared between file descriptors.  This is the method that samtools mostly uses.

**Comment by daheise** [comment]
Several files are opened and closed in sequence. Is there a method to clean up the threads when a file is closed?

Could you provide an link to an example of samtools using the newer strategy you mentioned?

**Comment by jkbonfield** [comment]
See https://github.com/samtools/htslib/blob/develop/test/test_view.c#L172-L183 which uses the same pool for both input and output file descriptors.  Note it has tidy up code later on too (hts_tpool_destroy).  This should use the same number of threads regardless (plus main thread, but it's up to you whether you -1 for that or not, depending on whether you're doing any work there).

**Comment by daheise** [comment]
Thank you for your help and note for improvement on my code. I will close this issue.
