### ISSUE TITLE
bgzip empty index with pipes

### ISSUE THREAD

**Issue by fungs** [samtools/htslib#793]
Hi, when using the following command with the htslib 1.9 suite, the resulting compressed FASTA gets created as well as the index file, but the latter is empty (actually 8 bytes).

    cat input.fna | bgzip -@ 20 -l 9 -i -I input.fna.gzi > input.fna.gz

I have to run a second pass, it works.

    bgzip -r input.fna.gz

I believe this is a bug and should be fixed. Piping is important when streaming large FASTA from the network, for instance.

Best,
Johannes

**Comment by daviesrob** [comment]
This looks like a threading-related bug, as it works in single-threaded mode.

Compare:
```
cat test/ce.fa | ./bgzip -l 9 -i -I /tmp/ce.fa.gzi > /tmp/ce.fa.gz
ls -l /tmp/ce.fa*
-rw-rw-r-- 1 xx xx 311885 Nov 14 12:21 /tmp/ce.fa.gz
-rw-rw-r-- 1 xx xx    264 Nov 14 12:21 /tmp/ce.fa.gzi
```

With:
```
cat test/ce.fa | ./bgzip -@ 20 -l 9 -i -I /tmp/ce.fa.gzi > /tmp/ce.fa.gz
ls -l /tmp/ce.fa*
-rw-rw-r-- 1 xx xx 117 311885 Nov 14 12:21 /tmp/ce.fa.gz
-rw-rw-r-- 1 xx xx 117      8 Nov 14 12:21 /tmp/ce.fa.gzi
```

So running in single-threaded mode is one work-around, albeit slow.  You could also try using the reindex option on the bgzip output in a more complicated pipeline like this (assuming you're using bash):

```
cat test/ce.fa | ./bgzip -@ 20 -l 9 | tee >(./bgzip -@ 20 -r -I /tmp/ce.fa.gzi) > /tmp/ce.fa.gz
ls -l /tmp/ce.fa*
-rw-rw-r-- 1 xx xx 311885 Nov 14 12:21 /tmp/ce.fa.gz
-rw-rw-r-- 1 xx xx    264 Nov 14 12:21 /tmp/ce.fa.gzi
```

In my tests the resulting index is byte identical to the one made by running single-threaded.

We'll look into fixing the multi-threading bug.

**Comment by fungs** [comment]
Cool, it's not urgent for me and 2-pass indexing worked fine. The tee double pipe solution might be a good workaround for others. I just thought that this behavior wasn't right and should be documented and eventually fixed. Thx.
