### ISSUE TITLE
add/expose free function, faidx usage

### ISSUE THREAD

**Issue by sg-james** [samtools/htslib#807]
#### Background:
I use msys2's mingw64 prompt to compile htslib.
I use msvc14.1 and link to htslib.

#### Example:
```cpp
const std::string filename = "human37.fa"
const std::string region = "chr1:15000-15100"
int length = 0;

faidx_t fai = fai_load(filename.c_str());

// Example 1: List sequence names:
for(int i = 0; i < faidx_nseq(fai); ++i) {
    char* seq = faidx_iseq(fai, i);
    std::cout << seq << std::endl;
    free(seq); // crash
}

// Example 2: Fetch seq
char* seq = fai_fetch(fai, region.c_str(), &length);
std::cout << seq << std::endl;
free(seq); // crash

fai_destroy(fai);
```

#### Problem
Various `faidx.h` documentation basically say that `char*` results are allocated by `malloc()` and should be freed with `free()`. In my use case, mingw64 uses`malloc` inside htslib dll and the msvc application tries to use its `free()`, but the two are not compatible (the whole alloc/free memory across dll boundary problem)

#### Possible Solutions:
1. Leave alone, users can customize htslib themselves
2. Add specific free functions, e.g. `fai_free_seq(char* seq)` + update doc / usage
3. Expose dll's `free()`, e.g. `hts_free(void*)`
4. Other?

Which (if any) of the solutions would be appropriate moving forward?

**Comment by dkj** [comment]
(From meeting) Number 3 is probably the easiest for us to implement.
