### ISSUE TITLE
hts_tpool_process_flush double prototype in header

### ISSUE THREAD

**Issue by jblachly** [samtools/htslib#816]
First with slightly better function documentation:
https://github.com/samtools/htslib/blob/a80f5fd602eb375dd4a9068ad53601a3fa51a4bc/htslib/thread_pool.h#L134-L145

Second:
https://github.com/samtools/htslib/blob/a80f5fd602eb375dd4a9068ad53601a3fa51a4bc/htslib/thread_pool.h#L231-L239

**Comment by jkbonfield** [comment]
Thanks for the bug report.   I'll remove the second copy.
