### ISSUE TITLE
Building with libcurl not able to be disabled

### ISSUE THREAD

**Issue by dnbaker** [samtools/htslib#824]
For distributed tools using htslib, I've started using this command to build libhts.a reproducibly without changing my flags:

```
htslib/libhts.a:                                                                                       
    cd htslib && autoheader && autoconf && \                                                           
    sed -i -e 's:enable_libcurl=check:enable_libcurl=no:' ./configure && \                             
    ./configure --disable-lzma --disable-bz2 && make libhts.a  
```

This is because`--disable-libcurl` is not supported by the configure script, and by default it looks for the presence of libcurl. I suggest either supporting `--disable-libcurl` or changing the default for libcurl from `check` to `no`.

**Comment by jmarshall** [comment]
In what way is `--disable-libcurl` not supported by the configure script?

**Comment by dnbaker** [comment]
Oh, my mistake. It wasn't `--disable-libcurl`, it was `--without-libcurl` wanted `configure: WARNING: unrecognized options: --without-libcurl`. I must have transposed the option in the process of reporting.

Thank you, I'll be closing this.
