### ISSUE TITLE
vcf: how to enumerate all INFO and FORMAT fields from header.

### ISSUE THREAD

**Issue by brentp** [samtools/htslib#825]
I want to create a lookup of `bcf_idpair_t.key -> (bcf_idpair_t.val.id, TYPE)`
where `TYPE` is either BCF_HL_INFO or BCF_HL_FMT.

During iteration over `bcf_hdr_t.id[0]` and looking at `bcf_idinfo_t`, how to tell if it's an INFO or a FORMAT?
Or is there another obvious way I am missing to accomplish this?

**Comment by brentp** [comment]
if hrec[1] is not null, it's an INFO
if hred[2] is not null it's a FMT

**Comment by pd3** [comment]
I think you want to use the `bcf_hdr_id2coltype` macro.

**Comment by brentp** [comment]
by the docs, that appears to take the `type` as a parameter and that's documented as:
```
@type:      one of BCF_HL_FLT, BCF_HL_INFO, BCF_HL_FMT
```
which is what I want to know.
