### ISSUE TITLE
Deadlock in multithreaded bam write

### ISSUE THREAD

**Issue by alexey-sbg** [samtools/htslib#831]
We observe deadlocks in bam_write1() function when htsFile is in MT mode. The problem is observed consistently with htslib 1.5 and htslib 1.9 on ubuntu 18.04, compiled with gcc7, but is believed to apply to all pthread implementations. The deadlock is triggered by running out of disk space and presumably by a premature destroy of the conditional variable after a failed call to either hwrite() or hflush() in bgzf_mt_writer().

**Comment by jkbonfield** [comment]
Thanks.  We'll investigate.

It's not surprising I guess that the error handling code could be a source of bugs as, thankfully, it very rarely get triggered.  The BGZF threading got a major revamp in 1.4 so I guess it's been there since then.

**Comment by jkbonfield** [comment]
Thanks for the bug report.  The error handling did work originally, but I think when I added the asynchronous multi-threaded decode side it caused a deadlock with the encoder when destroying the queue on error.

We could have worked around the issue by messaging within bgzf, but I felt the error was a more fundamental deficiency of the thread pool itself, so most of the fix resides there.

Please can you validate that #833 also fixes this for you?

Thanks.

**Comment by alexey-sbg** [comment]
> Please can you validate that #833 also fixes this for you?

Yes it does.
