### ISSUE TITLE
tabix segfaults on non-existant input file

### ISSUE THREAD

**Issue by diekhans** [samtools/htslib#862]
when given a non-existant file, tabix segfaults
`
%  tabix --version
tabix (htslib) 1.9
Copyright (C) 2018 Genome Research Ltd.

tabix --sequence 15 --begin 16 --end 17 --zero-based xxx
[E::hts_open_format] Failed to open file xxx
Segmentation fault

`

**Comment by valeriuo** [comment]
Looks like it was fixed by 7ff15099cbccf9d624da13d0a9cc4f974045c414, which is already merged in develop. It will be available with the next release.
