### ISSUE TITLE
Get tabix regions from BED file disappeared 

### ISSUE THREAD

**Issue by leipzig** [samtools/htslib#87]
this used to be an option:
```
         -B         region1 is a BED file (entire file will be read)
```

**Comment by slw287r** [comment]
it's my favorite option in tabix. plz add it back!

**Comment by pd3** [comment]
The option has been recently added as -R and -T:  the first uses the index to jump to regions, while the latter behaves the same way as -B did and streams the whole file skipping unlisted regions (https://github.com/samtools/htslib/commit/ed3efe902d11a65a2f782bf40051e6cf06942fc3). I am closing the issue now, please reopen in case of troubles.

**Comment by frahimov** [comment]
Could you show an example with -R and -T. These options do not work for me with a bed file in 
"chr13 26954184 26954185" format
