### ISSUE TITLE
kf_gammap precision 

### ISSUE THREAD

**Issue by Zilong-Li** [samtools/htslib#873]
hey guys,

I am developing a c program with dependence on htslib. And the basic statistic function in kfunc.h is necessary for my program.  But it seems the precision of `kf_gammap` function is not precise enough. Here is the instance.

In python, we can use `chi2.sf` from `scipy.stats` to acquire  more accurate pvalue result. With kfunc.h, I've tried to implement `1-kf_gammap` to get the pvalue.

```
inline double chisf(double x, double k)
{
    // sf = 1 - cdf
    return 1 - kf_gammap(k/2.0, x/2.0);
}
```
When I tried x = 40 and x= 80 ,  the `chisf` return 2.53963e-10 and 0. However, the `chi2.sf` from scipy can return more accurate value.
```
In [42]: chi2.sf(40,1)
Out[42]: 2.5396285894708634e-10

In [40]: chi2.sf(80,1)
Out[40]: 3.744097384202887e-19

```

May be there is something wrong with my implementation. How can i get the same precision as scipy.chi2.sf ?

Thanks.

**Comment by pd3** [comment]
You may try to lower KF_GAMMA_EPS in htslib/kfunc.c. For most practical purposes the precision 1e-14 is sufficient.

**Comment by Zilong-Li** [comment]
@pd3 Though I tried to lower KF_GAMMA_EPS to 1e-200, it doesn't work.

**Comment by pd3** [comment]
Right. I see you'd probably need to extend the approximation in `kf_lgamma` as well. This uses the Lanczos's approximation which is accurate to 14 significant digits.

**Comment by lh3** [comment]
You should use `kf_gammaq()` instead of `1-kf_gammap()`. With `1-x`, the resolution can never go higher than 1e-16.

**Comment by Zilong-Li** [comment]
@lh3 Many thanks! That makes sense.
