### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [samtools/htslib#888]
Greetings htslib developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project, especially now that you have a shiny fuzzers (#796) thanks to @markus-kusano. OSS-Fuzz will:

- Continuously run all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://github.com/google/oss-fuzz/blob/master/docs/faq.md ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Julien
OSS-Fuzz Team

**Comment by daviesrob** [comment]
Sorry, I got somewhat distracted from this by other work which took rather longer than expected.  We should be able to add it into OSS-Fuzz soon.

**Comment by Google-Autofuzz** [comment]
How is it going with the integration? If you need help with the integration, we can help to start the integration.

**Comment by daviesrob** [comment]
Sorry, been a bit busy.  I have an oss-fuzz branch ready to go so I'll turn it into a pull request now while I'm thinking about it.

**Comment by Google-Autofuzz** [comment]
Cool, thanks. You may need to sign the CLA :)

**Comment by daviesrob** [comment]
I suspect the CLA needs to be signed by my organisation.  I'm making enquiries.

**Comment by Google-Autofuzz** [comment]
> I suspect the CLA needs to be signed by my organisation. I'm making enquiries.

SGTM :)

**Comment by valeriuo** [comment]
Integration complete.
