### ISSUE TITLE
./configure --with-htslib=dir is ignored, overridden by system htslib

### ISSUE THREAD

**Issue by klmr** [samtools/htslib#889]
I’m using `$HOME/opt` as a general prefix. I therefore first install htslib-1.9 successfully and, afterwards, do

```sh
./configure --with-htslib=$HOME/opt --prefix=$HOME/opt
```

inside the unpacked `samtools-1.9` directory. This succeeds and generates the following `config.mk` fragment:

```makefile
prefix       = /home/konrad/opt
exec_prefix  = ${prefix}
bindir       = ${exec_prefix}/bin
datarootdir  = ${prefix}/share
mandir       = ${datarootdir}/man

…
#HTSDIR =
#include $(HTSDIR)/htslib.mk
#include $(HTSDIR)/htslib_static.mk
#HTSLIB = $(HTSDIR)/libhts.a
#HTSLIB_LIB = $(HTSLIB) $(HTSLIB_static_LIBS)
#HTSLIB_LDFLAGS = $(HTSLIB_static_LDFLAGS)
#BGZIP = $(HTSDIR)/bgzip
HTSLIB_CPPFLAGS = -I/home/konrad/opt/include
HTSLIB_LDFLAGS = -L/home/konrad/opt/lib
HTSLIB_LIB = -lhts

CURSES_LIB = -lncurses
```

When I now build samtools via `make`, samtools is built using

```sh
gcc -L/home/konrad/opt/lib -L./lz4  -o samtools [object files] ./lz4/lz4.o libbam.a libst.a -lhts -lncurses -lm -lz  -lpthread
```

… but for some reason, the system htslib takes precedence over the configured one:

```sh
⟩⟩⟩ ldd ./samtools
        linux-vdso.so.1 (0x00007fffd81dc000)
        libhts.so.2 => /usr/lib/x86_64-linux-gnu/libhts.so.2 (0x00007eff3235c000)
[…]
```

… which refers to `libhts.so.1.7-2`. Trying to execute `./samtools` therefore predictably gives me an error,

> ./samtools: symbol lookup error: ./samtools: undefined symbol: fai_load_format

How can I prevent this? I have no `LIBRARY_PATH` environment variable set. This is on Ubuntu 18.04.2.

I can avoid the above issue by simply not specifying `--with-htslib`, and letting `samtools-1.9` build using the provided, nested `htslib-1.9` source tree but I’d like to understand what’s going on, and I’d prefer dynamically linking htslib.

**Comment by daviesrob** [comment]
This is because the dynamic linker only knows where one copy of `libhts.so.2` is (the system one), and using that.  You need to give it a hint when building `samtools`.

`./configure --with-htslib=$HOME/opt --prefix=$HOME/opt LDFLAGS="-Wl,-R$HOME/opt/lib"` should do the trick.

It works with the embedded `htslib` because that gets statically linked into the `samtools` binary so the dynamic linker isn't involved.

**Comment by klmr** [comment]
Ah, of course that works. Bloody rpath. Thanks!
