### ISSUE TITLE
Understanding the format of bcf_fmt_t->p

### ISSUE THREAD

**Issue by Rakksor** [samtools/htslib#893]
I'm trying to read a vcf file using htslib and getting a list for each SNP with the nucleotides of all individuals. While my code seems to produce correct results I do not believe I am doing it properly.

By trial and error I found that values of 2 and 3 seem to stand for the reference allele (0 in the vcf file) and 4 and 5 seem to stand for the first alternate allele (1 in the vcf file). If this is true, why do the numbers not correspond to the ones in the vcf file and why are there two numbers associated with the same allele? Is this documented in any of the headers?

Short sample code without any error checking:
```
#include <stdio.h>
#include <stdlib.h>
#include <htslib/vcf.h>

int main(int argc, char **argv) {
	htsFile *bcf = bcf_open(argv[1], "r");
	bcf_hdr_t *header = bcf_hdr_read(bcf);
	bcf1_t *record = bcf_init();

	while (bcf_read(bcf, header, record) == 0) {
		printf("chromsome:\t%s\n", bcf_hdr_id2name(header, record->rid));
		printf("position:\t%i\n", record->pos);
		printf("n_alleles:\t%i\n", record->n_allele);

		bcf_unpack(record, BCF_UN_ALL);

		for (uint32_t i=0; i < record->d.fmt->p_len; i+=2) {

			uint8_t nuc1 = record->d.fmt->p[i];
			uint8_t nuc2 = record->d.fmt->p[i+1];

			char allele;

			if (nuc1 == 2 || nuc1 == 3) {
				if (nuc2 == 2 || nuc2 == 3) {         // 0|0
					allele = record->d.als[0];
				} else if (nuc2 == 4 || nuc2 == 5) {  // 0|1
					allele = ':';
				} else {                              // 0|.
					allele = '.';
				}
			} else if (nuc1 == 4 || nuc1 == 5) {
				if (nuc2 == 4 || nuc2 == 5) {         // 1|1
					allele = record->d.als[2];
				} else if (nuc2 == 2 || nuc2 == 3) {  // 1|0
					allele = ':';
				} else {                              // 1|.
					allele = '.';
				}
			} else {                                  // .|.
				allele='.';
			}
			printf("%c", allele);
		}
		printf("\n\n");
	}
	bcf_hdr_destroy(header);
	bcf_destroy(record);
	bcf_close(bcf);

	return EXIT_SUCCESS;
}
```

**Comment by lh3** [comment]
See Section 6.3.3 in the VCF spec on BCF2 encoding.

**Comment by Rakksor** [comment]
Awesome, thanks. So as a short summary if any one else comes accross this, here is what happens:

| Step | Binary | Decimal |
|-------|------------|----------|
| example entry | 000 \| 001 | 0 \| 1 | 
| 1) 1 is added to each value | 001 \| 010 | 1 \| 2 | 
| 2) each value is left shifted by 1 | 010 \| 100 | 2 \| 4 | 
| 3) if the file is phased: the last bit of the second value is set to 1 | 010 \| 101 | 2 \| 5 | 

So to get the index of the `d.als` entry, one has to right shift by 1 and subtract 1 (
`nuc1 = (record->d.fmt->p[i] << 1) - 1` in the above code). Missing values (`./.`) become -1 after this operation.
