### ISSUE TITLE
bgzf_seek on uncompressed data always seeks to the beginning of the block

### ISSUE THREAD

**Issue by adamnovak** [samtools/htslib#899]
The `bgzf_*` functions handle uncompressed files by presenting them as a series of maximum-sized blocks. In this way, virtual offsets as used by the BGZF layer correspond to actual offsets in the file. As far as I can make out, `bgzf_tell` and `bgzf_seek` should work correctly on such files.

However, this is not the case. `bgzf_tell` works fine, and `bgzf_seek` appears to work (i.e. a subsequent `bgzf_tell` gives you back the virtual offset you seeked to), but the next read will be fulfilled from the beginning of the block that contains the position you tried to go to, instead of from the actual position.

Here's where we set up the seek (setting `block_address` and `block_offset` and noting that we need to load the block):

https://github.com/samtools/htslib/blob/49058f4de0f91fb6200f722c79cbb4336587ac9c/bgzf.c#L1971-L1977

But here's where we load the block. If any data is actually read (**EDIT: This is wrong; we're really checking if any data was read since the most recent seek. I was bumping myself back to the beginning of the block in my own code.**), `block_offset` is cleared out, dumping us back at the beginning of the block instead of where we were supposed to be going.

https://github.com/samtools/htslib/blob/49058f4de0f91fb6200f722c79cbb4336587ac9c/bgzf.c#L976-L993

It looks like this may have been this way [since 2013](https://github.com/samtools/htslib/commit/9ec7860705a613c659992c437379a2f1374c71ac). This may be a contributor to the problems encountered in #388.

I want seeking in uncompressed files to work for vg, which uses HTSlib's BGZF layer in its own IO, so I am going to see if I can put together a patch.

**Comment by daviesrob** [comment]
I think the problem may actually be with `bgzf_tell()`, if you consider that on plain files (with no bgzf wrapping), the actual offset should be in the `block_address` part and the offset part should always be zero.

That would turn `bgzf_tell()` into something like:
```
#define bgzf_tell(fp) ((fp)->is_compressed ? (((fp)->block_address << 16) | ((fp)->block_offset & 0xFFFF)) : (((fp)->block_address + (fp)->block_offset) << 16))
```
.. or possibly better to use a static inline function at this point...

This would definitely need tests to ensure it's working as expected.

**Comment by adamnovak** [comment]
Hm. The implementation of `bgzf_useek` would support that use of `block_address`. It just dumps the destination uncompressed offset into `block_address`:

https://github.com/samtools/htslib/blob/49058f4de0f91fb6200f722c79cbb4336587ac9c/bgzf.c#L2286-L2302

To adopt it everywhere, we would have to adjust `bgzf_tell` as you mentioned to just add the block address and offset, and also adjust `bgzf_seek` to send the whole destination as the block address.

I think I was wrong about my assertion that the virtual offsets on uncompressed files are just normal offsets. That would be true after these changes, but right now we're taking the block address, which always ends in 0x0000 because it's reading in multiples of 0x10000, and then shifting it a *further* 16 bits left before mixing in the offset.

**Comment by jkbonfield** [comment]
> ```
> #define bgzf_tell(fp) ((fp)->is_compressed ? (((fp)->block_address << 16) | ((fp)->block_offset & 0xFFFF)) : (((fp)->block_address + (fp)->block_offset) << 16))
> ```

I need to do some debugging, but I don't agree with this.  I think bgzf_tell should be the same regardless, as should bgzf_seek.  Both of them are virtual offsets combined location of compressed block (which is a trivial 1:1 mapping for raw data) with a location within that block.  The maths is the same regardless of compression ratio.

I suspect the bug arises because `read_block` sets `block_offset` to the end of the data that it has read instead of the start of the block. That `fp->block_address += count` is probably wrong.  It should do the same as the compressed one and use htell to find the location prior to the hread.  Then seeks wouldn't need to behave differently, nor would tells, nor would the indices.

**Comment by jkbonfield** [comment]
Ie, something like this patch, which I came up with before looking at your code.  It works in my noddy test.  Can you confirm it works for you @adamnovak?

I'm happy to see that this is completely identical to the first bit of your solution (hurrah), however it doesn't have the latter half.  Basically it's not changing the meaning of the argument to `bgzf_seek` and thus it's also not changing the call to `bgzf_seek_common` either.

```
diff --git a/bgzf.c b/bgzf.c
index d62fc69..51055b6 100644
--- a/bgzf.c
+++ b/bgzf.c
@@ -972,6 +972,9 @@ int bgzf_read_block(BGZF *fp)
  single_threaded:
     size = 0;
 
+    int64_t block_address;
+    block_address = bgzf_htell(fp);
+
     // Reading an uncompressed file
     if ( !fp->is_compressed )
     {
@@ -987,14 +990,12 @@ int bgzf_read_block(BGZF *fp)
             return 0;
         }
         if (fp->block_length != 0) fp->block_offset = 0;
-        fp->block_address += count;
+        fp->block_address = block_address;
         fp->block_length = count;
         return 0;
     }
 
     // Reading compressed file
-    int64_t block_address;
-    block_address = bgzf_htell(fp);
     if ( fp->is_gzip && fp->gz_stream ) // is this is an initialized gzip stream?
     {
         count = inflate_gzip_block(fp);
```

Note this is following the standard semantics of what tell and seek do in POSIX.  Seek takes you to a location previously returned by tell.  They don't have to have any meaning other than that.  I think it's a mistake to try and add a dual meaning to these parameters.

**Comment by adamnovak** [comment]
@jkbonfield I will try your patch and see if it works; I have a bunch of tests from the vg project I can run. I'm a bit concerned about leaving the `if (fp->block_length != 0) fp->block_offset = 0;` line with no changes to seeking, because it looks like we might be throwing out the low 16 bits of the virtual offset that way.

**Comment by adamnovak** [comment]
OK @jkbonfield, I have tested your patch. It does not seem to work; I still end up reading from the beginning of a block when I seek to an offset in a block.

If I combine it with a change to `bgzf_seek` to combine both of the components of the virtual offset in uncompressed files into the desired block start address (basically starting the block at the position we are trying to seek to), then it works. I'm trying to work out why just leaving the offset in `fp->block_offset` (i.e. loading a whole block starting before the destination and reading from the middle) doesn't work, and where the block_offset is getting reset.

**Comment by adamnovak** [comment]
Sorry @jkbonfield, I made a mistake. I believe that your patch actually does work; all the tests I was running through vg go through a Protobuf ZeroCopyInputStream I implemented on top of BGZF, which reaches in and exposes some internal buffers, and I was mistakenly resetting `block_offset` when doing that.

I've adjusted my code and now it works with your patch; I've PR'd it to see if it also passes the htslib tests.

Now the problem I think is to choose between #901 (real offsets) and #904 (virtual offsets).

**Comment by jkbonfield** [comment]
> Now the problem I think is to choose between #901 (real offsets) and #904 (virtual offsets).

Indeed.  Anyone else care to weigh in on this argument?

**Comment by pd3** [comment]
Sorry for ignoring this thread for so long. I don't remember the motivation for adding the support for uncompressed data anymore. I believe it had to do something with deprecating the razf code and faidx and/or tview functionality on compressed vs uncompressed reference genomes. This is certainly a lesson for me what to put in commit messages.

In any case, the pull request #904 seems reasonable.
