### ISSUE TITLE
How can this project be compiled with MinGW on Windows 10?

### ISSUE THREAD

**Issue by bolunfeng** [samtools/htslib#907]
How can this project be compiled with MinGW on Windows 10? I really need this way to compile. Because other third-party libraries in my project are compiled with MinGW.

I need your help!
I need your help!
I need your help!

thanks!

**Comment by jkbonfield** [comment]
Take a look at our AppVeyor configuration which uses MinGW for automated testing.

https://github.com/samtools/htslib/blob/develop/.appveyor.yml

**Comment by bolunfeng** [comment]
@jkbonfield  thanks.It didn't seem to help me.who can help me?

**Comment by jkbonfield** [comment]
No one unless we know what the problem is.  What precisely isn't working?

Do you have a MinGW-64 installed?  Start by going to https://mingw-w64.org

**Comment by valeriuo** [comment]
Go to http://www.msys2.org/ and chose the correct installer for your architecture (32 bit or 64 bit). Follow the instructions on that page for a correct installation. With this step completed, go to the installation folder (**C:\msys64**, in the example) and open the MinGW command interpreter most appropriate for your machine. See picture below.

![msys2](https://user-images.githubusercontent.com/6553979/63008989-8bf73680-be7b-11e9-9740-2ff50156215e.PNG)

In the CLI window, type and run the following command, which will download and install the tools and libraries HTSlib depends on (64 bit version):
`pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-bzip2 mingw-w64-x86_64-xz mingw-w64-x86_64-curl`

Clone the HTSlib repo into your preferred folder:
`git clone -b master https://github.com/samtools/htslib.git`

Go to that folder and run the following command:
`autoheader && autoconf && ./configure && make -j4 && make install`

at the end of which:
- **hts-2.dll**, **bgzip**, **htsfile** and **tabix** should be in the folder **C:\msys64\mingw64\bin**
- **libhts.a** (the static library) should be in the folder **C:\msys64\mingw64\lib**
- all the header files should be in the folder **C:\msys64\mingw64\include\htslib**

**Comment by animesh** [comment]
Had to add few more dependencies to the following @valeriuo 
`pacman -S gcc git zlib-devel libbz2-devel  liblzma-devel ncurses-devel`

Clone the samtools repo
`git clone -b master https://github.com/samtools/samtools`

Install
`autoheader && autoconf && ./configure && make -j4 && make install`

And voila there is a working samtools.exe in C:\msys64\usr\bin\
```
$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 1.11-dirty (using htslib 1.11-dirty)

Usage:   samtools <command> [options]

Commands:
  -- Indexing
     dict           create a sequence dictionary file
     faidx          index/extract FASTA
     fqidx          index/extract FASTQ
     index          index alignment

  -- Editing
     calmd          recalculate MD/NM tags and '=' bases
     fixmate        fix mate information
     reheader       replace BAM header
     targetcut      cut fosmid regions (for fosmid pool only)
     addreplacerg   adds or replaces RG tags
     markdup        mark duplicates
     ampliconclip   clip oligos from the end of reads

  -- File operations
     collate        shuffle and group alignments by name
     cat            concatenate BAMs
     merge          merge sorted alignments
     mpileup        multi-way pileup
     sort           sort alignment file
     split          splits a file by read group
     quickcheck     quickly check if SAM/BAM/CRAM file appears intact
     fastq          converts a BAM to a FASTQ
     fasta          converts a BAM to a FASTA

  -- Statistics
     bedcov         read depth per BED region
     coverage       alignment depth and percent coverage
     depth          compute the depth
     flagstat       simple stats
     idxstats       BAM index stats
     phase          phase heterozygotes
     stats          generate stats (former bamcheck)
     ampliconstats  generate amplicon specific stats

  -- Viewing
     flags          explain BAM flags
     tview          text alignment viewer
     view           SAM<->BAM<->CRAM conversion
     depad          convert padded BAM to unpadded BAM


```
Thanks @valeriuo !

> Go to http://www.msys2.org/ and chose the correct installer for your architecture (32 bit or 64 bit). Follow the instructions on that page for a correct installation. With this step completed, go to the installation folder (**C:\msys64**, in the example) and open the MinGW command interpreter most appropriate for your machine. See picture below.
> 
> ![msys2](https://user-images.githubusercontent.com/6553979/63008989-8bf73680-be7b-11e9-9740-2ff50156215e.PNG)
> 
> In the CLI window, type and run the following command, which will download and install the tools and libraries HTSlib depends on (64 bit version):
> `pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-bzip2 mingw-w64-x86_64-xz mingw-w64-x86_64-curl`
> 
> Clone the HTSlib repo into your preferred folder:
> `git clone -b master https://github.com/samtools/htslib.git`
> 
> Go to that folder and run the following command:
> `autoheader && autoconf && ./configure && make -j4 && make install`
> 
> at the end of which:
> 
> * **hts-2.dll**, **bgzip**, **htsfile** and **tabix** should be in the folder **C:\msys64\mingw64\bin**
> * **libhts.a** (the static library) should be in the folder **C:\msys64\mingw64\lib**
> * all the header files should be in the folder **C:\msys64\mingw64\include\htslib**



> Go to http://www.msys2.org/ and chose the correct installer for your architecture (32 bit or 64 bit). Follow the instructions on that page for a correct installation. With this step completed, go to the installation folder (**C:\msys64**, in the example) and open the MinGW command interpreter most appropriate for your machine. See picture below.
> 
> ![msys2](https://user-images.githubusercontent.com/6553979/63008989-8bf73680-be7b-11e9-9740-2ff50156215e.PNG)
> 
> In the CLI window, type and run the following command, which will download and install the tools and libraries HTSlib depends on (64 bit version):
> `pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-zlib mingw-w64-x86_64-bzip2 mingw-w64-x86_64-xz mingw-w64-x86_64-curl`
> 
> Clone the HTSlib repo into your preferred folder:
> `git clone -b master https://github.com/samtools/htslib.git`
> 
> Go to that folder and run the following command:
> `autoheader && autoconf && ./configure && make -j4 && make install`
> 
> at the end of which:
> 
> * **hts-2.dll**, **bgzip**, **htsfile** and **tabix** should be in the folder **C:\msys64\mingw64\bin**
> * **libhts.a** (the static library) should be in the folder **C:\msys64\mingw64\lib**
> * all the header files should be in the folder **C:\msys64\mingw64\include\htslib**

**Comment by valeriuo** [comment]
@animesh 
Some additional info to your comment:

MSYS2 comes in two flavours:
- the **MSYS2** environment (`msys2.exe`), which is a fork of Cygwin, is more POSIX-like and links all programs with a compatibility library (`msys-2.0.dll`). This is what you are probably using (you can check by running `echo $MSYSTEM` and it should be `MSYS` or `MSYS2`). It usually ships `msys2-runtime` and takes its packages from the **msys** [repo](https://repo.msys2.org/msys/x86_64/). To build HTSlib (and SAMtools) on this environment one needs the packages that you mentioned, which come from this repo.
- the **MinGW** environment, with its 32-bit (`mingw32.exe`) and 64-bit (`mingw64.exe`) variants, which links with the native Windows libraries, uses the `mingw-w64-x86_64-toolchain` (for 64-bit) and takes its packages from the **mingw64** [repo](https://repo.msys2.org/mingw/x86_64/). This is what we are using in our CI environment (AppVeyor) and this is what I was offering details about in my previous comment.

A developer can use either of the two environments, but care should be taken as not to mix the runtimes and required packages. So, one ca use either the **MSYS2** env, with `msys2-runtime-devel`, `libcurl-devel`, `zlib-devel`, `liblzma-devel`, `libbz2-devel`, `libcurses-devel` or (exclusive or) the **MinGW64** env, with `mingw-w64-x86_64-toolchain`, `mingw-w64-x86_64-curl`, `mingw-w64-x86_64-zlib`, `mingw-w64-x86_64-bzip2`, `mingw-w64-x86_64-xz`, `mingw-w64-x86_64-ncurses`.
