### ISSUE TITLE
Expose bgzf cache option for faidx

### ISSUE THREAD

**Issue by jblachly** [samtools/htslib#913]
I recently had a problem being I/O bound on faidx `fai_retrieve`.

bgzf exposes `bgzf_set_cache_size` which requires a `BGZF *fp`, but faidx's header includes only `__faidx_t` as an opaque struct -- in reality, its first member is in fact a `BGZF *`.

By adding a BGZF cache, I improved my sequential workload runtimes significantly.

cache size|runtime impr
-----------|------------
64k        | unclear
1MB       | 33% 
16MB     | 37%

Now, because this is not exposed, I had to redefine `__faidx_t` to expose `->bgzf` before I could call `bgzf_set_cache_size`.

I can think of at least three solutions:
1. Move `__faidx_t` from `faidx.c` to `faidx.h`
2. Implement the `FAI_CACHE` flag which is mentioned in `faidx.h` but not implemented
3. In case bgzf functions are being deprecated in favor of htsFile, enable use of  `hts_set_cache_size` via 1 or 2 above, or add htsFile option flags to the faidx functions.

Option 2 seems simpler for the consumer, but because faidx_t would remain opaque, it's not clear the user would have control over cache size.

Option 1 has the advantage also that with exposure of `BGZF *fp` the user could add decompression threads.

Thanks for considering.

**Comment by daviesrob** [comment]
I think the best solution would be to add a `fai_set_cache_size()` function.

We don't want to expose `__faidx_t` because public structs tie down the ABI and make it harder to change things later.  The `FAI_CACHE` flag doesn't look very useful either as you can't say how big the cache would be.

**Comment by jblachly** [comment]
I also think that sounds like the most reasonable solution. If I can get around to it next weekend I'll implement unless y'all beat me to it. I will also strike mention of FAI_CACHE.
