### ISSUE TITLE
CRAM can't load reference data over a network

### ISSUE THREAD

**Issue by jmarshall** [samtools/htslib#92]
(Migrated from samtools/samtools#145.)

The CRAM code currently isn't plugged into a networking library (quoting @jkbonfield on the samtools issue):

> That's one thing currently missing from CRAM. It only support
> UR:file at the moment as I wasn't sure what network library we'd end
> up with for fetching remote data.
> 
> It could be extended at some time to use full ftp: and http: accessor
> methods, although it's probably not the correct solution as it'll end
> up being slow vs using the local MD5 archive.

See also notes in that issue re handling `-T ref.fa` and calling `cram_load_reference`.

**Comment by jmarshall** [comment]
Looking at  the code, I am unsure whether this has yet been plugged in.  In particular, I don't think we will look for a `.fai` for and chromosomes in `UR:http://host/ref/organism.fa`... @jkbonfield?

**Comment by jkbonfield** [comment]
On Mon, Feb 09, 2015 at 01:49:30AM -0800, John Marshall wrote:
> Looking at  the code, I am unsure whether this has yet been plugged
> in.  In particular, I don't think we will look for a `.fai` for and
> chromosomes in `UR:http://host/ref/organism.fa`... @jkbonfield? 

We could probably add it, but right now it only uses local UR codes
(ie straight filenames or file://).  It's not just the .fai searching
bit either, but also the requirement to have the reference itself.

This only really matters for converting from SAM/BAM to CRAM though.
Once you have a CRAM the headers are mandated to have an M5 tag, which
is the preferred accession route for fetching the reference.

James

-- 
James Bonfield (jkb@sanger.ac.uk) | Hora aderat briligi. Nunc et Slythia Tova
                                  | Plurima gyrabant gymbolitare vabo;
  A Staden Package developer:     | Et Borogovorum mimzebant undique formae,
https://sf.net/projects/staden/   | Momiferique omnes exgrabure Rathi. 


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by jmarshall** [comment]
May be worth plugging `UR` into `hopen()`.

**Comment by xunjieli** [comment]
@jmarshal: Any update on "_plugging `UR` into `hopen()`_" mentioned in your comment above?
Currently the fa and fai loading in `cram_io.c` uses raw POSIX APIs like `stat()` and `fopen()` bypassing the `hFile` plugins (e.g. for S3 and GCS plugins).
Can we make the fa and fai loading in `cram_io.c` use `hFile`? It will really help us adopt CRAM in our workflow. Thanks.

**Comment by valeriuo** [comment]
Solved by #1017
