### ISSUE TITLE
so name's version

### ISSUE THREAD

**Issue by junaruga** [samtools/htslib#932]
Hello,
I am working to create htslib's RPM package on Fedora project now. [1]
I tried below process.

```
$ git clone git@github.com:samtools/htslib.git
$ cd htslib
$ git checkout 1.9
$ make
$ make install prefix=$(pwd)/dist

$ ls -l dist/lib/
total 10576
-rw-r--r-- 1 jaruga jaruga 7165054 Sep 15 21:54 libhts.a
lrwxrwxrwx 1 jaruga jaruga      13 Sep 15 22:01 libhts.so -> libhts.so.1.9
-rw-r--r-- 1 jaruga jaruga 3653800 Sep 15 21:55 libhts.so.1.9
lrwxrwxrwx 1 jaruga jaruga      13 Sep 15 22:01 libhts.so.2 -> libhts.so.1.9
drwxr-xr-x 2 jaruga jaruga    4096 Sep 15 22:01 pkgconfig/
```

Then I noticed below behaviors in the the process.

* `make` creates `libhts.so` (actual file) and `libhts.so.2` (symbolic link).
* `make install` creates libhts.so.1.9 (actual file), libhts.so (symbolic link) and libhts.so.2 (symbolic link).

The software version ("1.9")is used as the so name's version.
But seeing some documents, the version has to be different from the software version. And the version has to be binary interface interface (ABI) version.

According to [2] about how to set the ABI version is
> the common practice with upstreams is to use only a single digit here.

For example, in case of `rpm`, it seems below version is used so name's version.

https://github.com/rpm-software-management/rpm/blob/master/rpm.am#L10
> rpm_version_info = 9:0:0

When building the so libraries, the version is like this.

```
$ git clone git@github.com:rpm-software-management/rpm.git
$ cd rpm
$ ./autogen.sh
$ ./configure --prefix=$(pwd)/dist
$ make
...
./lib/.libs/librpm.so.9.0.0
./lib/.libs/librpm.so
./lib/.libs/librpm.so.9
...
```

I am not familiar with this rule. Someone do you know it?

> * `make install` creates libhts.so.1.9 (actual file), libhts.so (symbolic link) and libhts.so.2 (symbolic link).

I suppose current situation using software version as a so name's version, and 2 versions "libhts.so.1.9" and "libhts.so.2" are used as some content might not be good.

[1] Fedora htslib: https://bugzilla.redhat.com/show_bug.cgi?id=1326504
[2] ABI: https://en.wikipedia.org/wiki/Application_binary_interface

**Comment by jmarshall** [comment]
The htslib soversion was 1 up to htslib 1.3.2, and has been 2 from htslib 1.4 up to 1.9.

> The software version ("1.9")is used as the so name's version.

This is incorrect. The shared library is built with `-Wl,-soname,libhts.so.2` in version 1.9 and similarly in previous releases.

1. In a build directory, libhts.so might be listed as a prerequisite for other executables hence should be a real file so that its timestamp is reliable. libhts.so.2 is used only at runtime and without any timestamp checks so can safely be a symlink.

   (The layout of the build directory is immaterial in an rpm-building context anyway.)

2. For the installed files, the considerations are different. No one should be doing timestamp checks against installed files. OTOH some may wish to install e.g. 1.7, 1.8, and 1.9 shared libs alongside each other. Having the fully-versioned shlibs being real files facilitates this and allows the user to adjust the version being used by updating the libhts.so.2 symlink.

   I would expect this arrangement of having the installed lib.so.soversion being a symlink to lib.so.pkgversion would be familiar to Fedora maintainers, because it was inspired by study of Fedora system library RPM contents and spec files, notably libc IIRC.

**Comment by junaruga** [comment]
@jmarshall thank you for the detailed explanation!

The "1." and "2." make sense to me.

> I would expect this arrangement of having the installed lib.so.soversion being a symlink to lib.so.pkgversion would be familiar to Fedora maintainers, because it was inspired by study of Fedora system library RPM contents and spec files, notably libc IIRC.

Great information. Now I checked glibc (libc) on my local Fedora 30. It's like htdlib!

```
$ rpm -q glibc
glibc-2.29-15.fc30.x86_64
glibc-2.29-15.fc30.i686

$ ls -l /usr/lib/libc[-.]*
-rwxr-xr-x 1 root root 6273648 Jun  6 14:08 /usr/lib/libc-2.29.so*
lrwxrwxrwx 1 root root      12 Jun  6 13:56 /usr/lib/libc.so.6 -> libc-2.29.so*

$ rpm -qf /usr/lib/libc-2.29.so
glibc-2.29-15.fc30.i686

$ rpm -qf /usr/lib/libc.so.6
glibc-2.29-15.fc30.i686
```

As my concern is solved, I close this ticket.
Thank you again!

**Comment by junaruga** [comment]
Sorry let me ask one more question.

In case of glibc (libc) libraries on my Fedora 30.

`libc-2.29.so` and `libc.so.6` (symbolic link) are in glibc-2.29-15.fc30.x86_64 RPM.
`libc.so` is in `glibc-devel-2.29-15.fc30.x86_64` RPM.

```
$ ls -l /usr/lib64/libc[-.]*
-rwxr-xr-x 1 root root  6699224 Jun  6 14:09 /usr/lib64/libc-2.29.so*
-rw-r--r-- 1 root root 16258354 Jun  6 14:10 /usr/lib64/libc.a
-rw-r--r-- 1 root root      253 Jun  6 13:55 /usr/lib64/libc.so
lrwxrwxrwx 1 root root       12 Jun  6 13:55 /usr/lib64/libc.so.6 -> libc-2.29.so*
```

But htslib has `libhts.so.2` (symbolic link) and `libhts.so.1.9`.
`libhts.so.1.9` should be renamed to `libhts-1.9.so`?

**Comment by jmarshall** [comment]
It’s likely that libc followed a `libc.so.2.29` convention at the time that htslib followed its example, and/or that htslib was also following the corresponding practices in Debian and for other system libraries such as libcurl.

The `major.minor` version number will always have at least two components while the soversion has only one, so there is no ambiguity. The htslib maintainers may wish to survey the landscape again and change the convention used if it has shifted, but it’s not very important.

In the meantime, the Fedora Packaging Guidelines are silent on this question, and in general Fedora users would be best served by a package that installs the files just as upstream htslib does.

**Comment by jkbonfield** [comment]
The Linux Filesystem Hierarchy Standard isn't explicit on this, but looking for ".so" it refers to "libm.so.*" and "libc.so.*" so it appears the norm is still to have versioning after .so and not before.

Looking on Ubuntu vs RedHat I also see the .so.<num> syntax used for zlib. On a local RedHat system I see 235 files matching `/usr/lib64/lib*-[0-9]*.so*` out of 1615 matching `/usr/lib64/lib*.so*`.  I think the way libc works isn't the norm therefore.

I see no reason to change how htslib works in this regard.

**Comment by junaruga** [comment]
@jmarshall @jkbonfield 

Thanks for sharing your thoughts. I agree.

On my Fedora 30, I could see many so files like `libhts.so.1.9` and the following pattern.

```
lrwxrwxrwx 1 jaruga jaruga      13 Sep 15 22:01 libhts.so -> libhts.so.1.9
-rw-r--r-- 1 jaruga jaruga 3653800 Sep 15 21:55 libhts.so.1.9
lrwxrwxrwx 1 jaruga jaruga      13 Sep 15 22:01 libhts.so.2 -> libhts.so.1.9
```

```
$ ls -l /usr/lib64/lib*.so.*
```

As you said, zlib's pattern is same with htslib.

```
$ ls -l /usr/lib64/libz.so*
lrwxrwxrwx 1 root root     14 Aug 15 09:30 /usr/lib64/libz.so -> libz.so.1.2.11*
lrwxrwxrwx 1 root root     14 Aug 15 09:30 /usr/lib64/libz.so.1 -> libz.so.1.2.11*
-rwxr-xr-x 1 root root 128904 Aug 15 09:30 /usr/lib64/libz.so.1.2.11*
```

```
$ rpm -qf /usr/lib64/libz.so
zlib-devel-1.2.11-17.fc30.x86_64
$ rpm -qf /usr/lib64/libz.so.1
zlib-1.2.11-17.fc30.x86_64
$ rpm -qf /usr/lib64/libz.so.1.2.11
zlib-1.2.11-17.fc30.x86_64
```

> In the meantime, the Fedora Packaging Guidelines are silent on this question, and in general Fedora users would be best served by a package that installs the files just as upstream htslib does.

I need to do action for that as a Fedora user in Fedora project.

Thanks. I would close this ticket. :)
