### ISSUE TITLE
samtools reference sequence from S3 or https

### ISSUE THREAD

**Issue by uitde007** [samtools/htslib#933]
Hi,

Although I can read and write the bam and cram files directly to and from an S3 bucket using a  local reference sequence, converting bam to cram using a reference sequence located on an S3 bucket or URI doesn't work.

s3://bucket/x.fa: No such file or directory
`samtools view -C s3://bucket/bam/x.bam -o s3://bucket/x.cram -T s3://bucket/x.fa` 

https://domain/x.fa : No such file or directory
`samtools view -C s3://bucket/bam/x.bam -o s3://bucket/x.cram -T https://domain/x.fa`

OK
`samtools view -C s3://bucket/bam/x.bam -o s3://bucket/x.cram -T x.fa`

**Comment by jkbonfield** [comment]
This is something that isn't currently supported, sorry.

We'll leave this open as it's something we should add, but probably won't appear in the immediate future.
