### ISSUE TITLE
large BAM to CRAM conversion hits S3 chunk limit

### ISSUE THREAD

**Issue by uitde007** [samtools/htslib#938]
(How) can I increase chunk size when converting a 200Gb BAM to CRAM on S3 so the chunk number stays under 10K?

`samtools view -C s3://bucket/bam/x.bam -o s3://bucket/x.cram -T x.fa`

\<Error>\<Code>InvalidArgument\</Code>\<Message>Part number must be an integer between 1 and 10000, inclusive\</Message>\<ArgumentName>partNumber\</ArgumentName>\<ArgumentValue>10001\</ArgumentValue>\<RequestId>

**Comment by whitwham** [comment]
Unless you want to change the code yourself there is no way of increasing the part size at the moment.

This is something that needs fixing.
