### ISSUE TITLE
CRAM license vs htslib license

### ISSUE THREAD

**Issue by tijyojwad** [samtools/htslib#940]
The LICENSE for htslib covers everything except the `cram` folder. What LICENSE is the `cram` folder released under? Could the current LICENSE be updated to reflect that?

Thanks!

**Comment by jmarshall** [comment]
Did you read the entire LICENSE file?

**Comment by tijyojwad** [comment]
Ah I evidently did not. Looks like it's BSD 3 for the cram folder. Thanks!
