### ISSUE TITLE
@rpath/libdeflate.so

### ISSUE THREAD

**Issue by kchowdhary4** [samtools/htslib#943]
Not sure if this is a pysam or htslib issue so opening here: 

Not sure how to deal with following error -- 
`ImportError: dlopen(/anaconda/envs/py27/lib/python2.7/site-packages/pysam/libchtslib.so, 2): Library not loaded: @rpath/libdeflate.so
  Referenced from: /anaconda/envs/py27/lib/libhts.2.dylib
  Reason: image not found`

my samtools is up to date when i try to update

**Comment by dpryan79** [comment]
This is a conda solver issue and has nothing to do with htslib or pysam. The conda solver has installed the wrong version of libdeflate in you environment. Please run `conda install -c conda-forge -c bioconda libdeflate=1.0".

**Comment by kchowdhary4** [comment]
That did the trick -- thank you!
