### ISSUE TITLE
Seq of read that mapped to revserse strand is converted to forward strand base except for mismatch base, is that true?

### ISSUE THREAD

**Issue by 0106WeiWeiDeng** [samtools/htslib#944]
I am writing a C++ program that extracted reads information from .bam file using htslib.
Extracted FLAG and interprete it:

`int flag = (int)aln->core.flag;`
`string flag_str = to_string(flag) + ";";`
`if((flag & BAM_FPAIRED) == BAM_FPAIRED) flag_str += "the read is paired;";`
`if((flag & BAM_FPROPER_PAIR) == BAM_FPROPER_PAIR) flag_str += "the read is mapped in a proper pair;";`
`if((flag & BAM_FUNMAP) == BAM_FUNMAP) flag_str += "the read itself is unmapped;";`
`if((flag & BAM_FMUNMAP) == BAM_FMUNMAP) flag_str += "the mate is unmapped;";`
`if((flag & BAM_FREVERSE) == BAM_FREVERSE) flag_str += "the read is mapped to the reverse strand;";`
`if((flag & BAM_FMREVERSE) == BAM_FMREVERSE) flag_str += "the mate is mapped to the reverse strand;";`
`if((flag & BAM_FREAD2) == BAM_FREAD2) flag_str += "this is read2;";`
`if((flag & BAM_FSECONDARY) == BAM_FSECONDARY) flag_str += "not primary alignment;";`
`if((flag & BAM_FQCFAIL) == BAM_FQCFAIL) flag_str += "QC failure;";`
`if((flag & BAM_FDUP) == BAM_FDUP) flag_str += "optical or PCR duplicate;";`
`if((flag & BAM_FSUPPLEMENTARY) == BAM_FSUPPLEMENTARY) flag_str += "supplementary alignment;";`

Extracted SEQ and QUAL:

`string seq, qual;`
`uint8_t* seqi = bam_get_seq(aln);`
`uint8_t *quali = bam_get_qual(aln);`
`for (int i = 0; i < aln->core.l_qseq; i++){
            seq += seq_nt16_str[bam_seqi(seqi, i)];
            qual += 33 + quali[i];
        }`

However, the seq of reads that mapped to reverse strand make me confused, i.e.:

TR:258919 | 147;the read is paired;the read is mapped in a proper pair;the read is mapped to the reverse strand;this is read2; | chr19 | 14213692(0-based) | 60 | 147M | chr19 | 14213693(0-based) | -146 | TCAGGGTGTGTTCGAT**A**TGTTTCAG**T**TTGACCACCTGGGAAGGGATGGAGGGGAGGGCAGATAGGAGGGGGAGGTGAGAGGTGCCTCATTTCCGCTAATGCGTGGAACTAGGGATGCCGGAGCCAGGCCGGTTCCTTCAGCCAGAAT

TR:258919 | 99;the read is paired;the read is mapped in a proper pair;the mate is mapped to the reverse strand;this is read1; | chr19 | 14213693(0-based) | 60 | 145M | chr19 | 14213692(0-based) | 146 | CAGGGTGTGTTCGAT**C**TGTTTCAG**A**TTCACCACCTGGGAAGGGAAGGAGGGGAGGGCAGAAAGGAGGGGGAGGTGAGAGGGGCCTCATTTCCCCTAATGCCTGGAACTAGGGATGCCGGAGCCAGGACGGTTCCTTCAGCCAGAA

As show above, the first one is read2, it mapped to reverse strand, the second one is read1, it mapped to forward strand. The ref is:

chr19:14213692-14213892(0-based):
TCAGGGTGTGTTCGAT**C**TGTTTCAG**T**TTCACCACCTGGGAAGGGAAGGAGGGGAGGGCAGAAAGGAGGGGGAGGTGAGAGGGGCCTCATTTCCCCTAATGCCTGGAACTAGGGATGCCGGAGCCAGGCCGGTTCCTTCAGCCAGAATCATTTGTGTGCCTGTGGCCTGTCGGGCCCTTAGCTGATGCTGAGGACACAGCAT

Mismatch base is in bold format. I guessed seq of read that mapped to revserse strand is converted to forward strand base except for mismatch base, it that true? I  am confused...

**Comment by valeriuo** [comment]
147 = 128 (READ2) + **16** (REVERSE) + 2 (PROPER_PAIR) + 1 (PAIRED)

From the [SAM spec](https://github.com/samtools/hts-specs/blob/master/SAMv1.pdf), section 1.4 (page 6):
> 2. FLAG
> 16 0x10 **SEQ** being reverse complemented

Page 7:

> Bit 0x10 indicates whether **SEQ** has been reverse complemented and **QUAL** reversed. When bit 0x4 is unset, this corresponds to the strand to which the segment has been mapped: bit 0x10 unset indicates the forward strand, while set indicates the reverse strand. When 0x4 is set, this indicates whether the unmapped read is stored in its original orientation as it came off the sequencing machine.

**Comment by daviesrob** [comment]
The entire read will have been reverse complemented, including any mismatched bases.
