### ISSUE TITLE
What is "R" op of CIGAR?

### ISSUE THREAD

**Issue by 0106WeiWeiDeng** [samtools/htslib#947]
I write a c++ program using htslib. When debugging, an error occurred, it related to "R" op of CIGAR. The bellow is debug info:

pos: 47103828
flag: 2211
rname: chr3
cigar: 91R47M2D9M
GTTCAGTTGCTAAGGGAAAAGGGTGGTTTGTTTGTTTTTTTTTTTTTATTTTATTT
000.2E/?0+7?./?DABB./D//ADA>CDA<>0>CCCC>>CC;>/.*,>CC*BC<

What is "R" op? I am sorry if the question was asked before.

**Comment by dpryan79** [comment]
No such cigar operation exists.

**Comment by 0106WeiWeiDeng** [comment]
> No such cigar operation exists.

But it appeared...

**Comment by dpryan79** [comment]
Did it really though, or is that instead a bug in your program (or whatever produced the BAM file)? What does `samtools view` say?

**Comment by jkbonfield** [comment]
It's just a number in BAM - the bottom few bits of the cigar uint32_t.  It's normally masked off and passed into an array to get a lookup.  If you code that wrongly maybe it's just read off the end of the lookup array?

As @dpryan79 says, look at the samtools view output.  If that differs, run your C++ through valgrind or use `-fsanitize=address` on your compiler if it supports it to see if it spots memory access bugs.  Either way, this isn't an htslib issue so I'm closing the ticket.  (Feel free to add further comments though.)

**Comment by 0106WeiWeiDeng** [comment]
samtools view result:

TR:244871	2211	chr3 	47103828	56	91H47M2D9M	=	47103854	174	GTTCAGTTGCTAAGGGAAAAGGGTGGTTTGTTTGTTTTTTTTTTTTTATTTTATTT
000.2E/?0+7?./?DABB./D//ADA>CDA<>0>CCCC>>CC;>/.*,>CC*BC<

**Comment by valeriuo** [comment]
>  (Feel free to add further comments though.)

Including the version of htslib and the particular methods (macros) you are using. A snippet of your C++ code would also be welcome.

**Comment by 0106WeiWeiDeng** [comment]
> > samtools view result:
> > TR:244871 2211 chr3 47103828 56 91H47M2D9M = 47103854 174 GTTCAGTTGCTAAGGGAAAAGGGTGGTTTGTTTGTTTTTTTTTTTTTATTTTATTT
> > 000.2E/?0+7?./?DABB./D//ADA>CDA<>0>CCCC>>CC;>/._,>CC_BC<
> 
> oh, "R" is really "H", it is my fault！

I am sorry that I wasted your time.
