### ISSUE TITLE
Querying aux field type

### ISSUE THREAD

**Issue by Shians** [samtools/htslib#974]
Is there a way to query the type of an aux field? This would be helpful for figuring out which `bam_aux..` function to use programatically without knowing ahead of time.

**Comment by whitwham** [comment]
As far as I know there is no existing function to do it.

The first byte returned from bam_aux_get should contain the aux type letter that you can use.  The various bam_aux2 functions are examples of its use.

**Comment by jkbonfield** [comment]
Further to the above comment, an example usage of this is in https://github.com/samtools/samtools/blob/develop/bam_fastq.c#L262-L299

Note that type 'd' is not an official SAM spec type, but has existing in samtools for many years.  (I believe it's unused though.)

**Comment by Shians** [comment]
Thanks @whitwham and @jkbonfield, the example code was very helpful.
