### ISSUE TITLE
unable to install HTSlib on Ubuntu 18.04

### ISSUE THREAD

**Issue by ishwarvh** [samtools/htslib#978]
Hello, 

I have installed the external libraries listed in the the INSTALL file and run the configure, make and make install commands as root. 

I have also installed the Debian/Ubuntu specific dependencies listed in the INSTALL file. i.e.

Debian / Ubuntu
---------------

sudo apt-get update  # Ensure the package list is up to date
sudo apt-get install autoconf automake make gcc perl zlib1g-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libssl-dev

./configure does not throw up any errors. Infact, I do not see any explicit error messages during installation. 

Here are the outputs for each of the installation steps. Can someone help me figure out whats going wrong here. 

Thank you,

`Precision-3630-Tower:~/Programs/htslib-1.9$ sudo ./configure

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ranlib... ranlib
checking for grep that handles long lines and -e... /bin/grep
checking for C compiler warning flags... -Wall
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for _LARGEFILE_SOURCE value needed for large files... no
checking shared library type for unknown-Linux... plain .so
checking how to run the C preprocessor... gcc -E
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for gmtime_r... yes
checking for fsync... yes
checking for drand48... yes
checking whether fdatasync is declared... yes
checking for fdatasync... yes
checking for library containing log... -lm
checking for zlib.h... yes
checking for inflate in -lz... yes
checking for library containing recv... none required
checking for bzlib.h... yes
checking for BZ2_bzBuffToBuffCompress in -lbz2... yes
checking for lzma.h... yes
checking for lzma_easy_buffer_encode in -llzma... yes
checking for libdeflate.h... no
checking for libdeflate_deflate_compress in -ldeflate... no
checking for curl_easy_pause in -lcurl... yes
checking for CCHmac... no
checking for library containing HMAC... -lcrypto
checking whether PTHREAD_MUTEX_RECURSIVE is declared... yes
configure: creating ./config.status
config.status: creating config.mk
config.status: creating htslib.pc.tmp
config.status: creating config.h
config.status: config.h is unchanged
`

`Precision-3630-Tower:~/Programs/htslib-1.9$ sudo make

make: Nothing to be done for 'all'.
`

`sudo make install

mkdir -p -m 755 /usr/local/bin /usr/local/include /usr/local/include/htslib /usr/local/lib /usr/local/share/man/man1 /usr/local/share/man/man5 /usr/local/lib/pkgconfig
if test -n ""; then mkdir -p -m 755 ; fi
install -p -m 644 libhts.so /usr/local/lib/libhts.so.1.9
ln -sf libhts.so.1.9 /usr/local/lib/libhts.so
ln -sf libhts.so.1.9 /usr/local/lib/libhts.so.2
sed -e 's#@-includedir@#/usr/local/include#g;s#@-libdir@#/usr/local/lib#g;s#@-PACKAGE_VERSION@#1.9#g' htslib.pc.tmp > /usr/local/lib/pkgconfig/htslib.pc
chmod 644 /usr/local/lib/pkgconfig/htslib.pc
install -p bgzip htsfile tabix /usr/local/bin
if test -n ""; then install -p  ; fi
install -p -m 644 htslib/*.h /usr/local/include/htslib
install -p -m 644 libhts.a /usr/local/lib/libhts.a
install -p -m 644 bgzip.1 htsfile.1 tabix.1 /usr/local/share/man/man1
install -p -m 644 faidx.5 sam.5 vcf.5 /usr/local/share/man/man5
`

**Comment by dpryan79** [comment]
What makes you think it failed?

**Comment by ishwarvh** [comment]
"which htslib" does not return anything!

**Comment by dpryan79** [comment]
Nor should it return anything, htslib isn't an executable. I bet `ls -l /usr/local/lib/libhts.a` will indicate that it was installed.

**Comment by ishwarvh** [comment]
Indeed. Thank you for clearing it up. I was able to install samtools and bcftools and call them and I expected HTSlib to behave similarly. 
Now I understand the difference between a tool and a library.

Thank you.
