### ISSUE TITLE
error exit code on tabix and bgzip is non-zero when running with --help

### ISSUE THREAD

**Issue by kantale** [samtools/htslib#982]
I noticed that when I run:

```bash
./tabix --help
```
And then:
```bash
echo $?
```
This print 1

The same happens with:
```bash
./bgzip --help
```

In contrary this:
```bash
./htsfile --help
echo $?
```
prints 0

Tools shouldn't return non-zero exit codes when run with the --help argument.

**Comment by jmarshall** [comment]
Thanks for the report. This has already been fixed on the **develop** branch by PR #754.
