### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Hoeze** [samtools/htslib#985]
Hi, would it be possible to make a new release?
The last version is older than one year.

**Comment by whitwham** [comment]
Yes, yes it is.

We are working on the release right now.  We are at the updating history files stage and putting in the last finishing touches.  We should have a release candidate out very soon.

**Comment by Hoeze** [comment]
Thank you very much @whitwham!

**Comment by whitwham** [comment]
Release [1.10](https://github.com/samtools/htslib/releases/tag/1.10) is now available.
