### ISSUE TITLE
Multiple issues found with cppcheck

### ISSUE THREAD

**Issue by walecome** [samtools/htslib#995]
Hi! Here is an output from cppcheck showing a range of different issues (memory leaks, resource leaks, double free). The command run was `cppcheck  --enable=warning -q -f --language=c ./` on the root directory. Output:
```
(htslib) ( develop ) ><> cppcheck  --enable=warning -q -f --language=c ./                                                                                                          17:40:31
[htslib/kbitset.h:106]: (error) Common realloc mistake: 'bs' nulled but not freed upon failure
[cram/cram_codecs.c:2232]: (error) Memory leak: t
[cram/cram_decode.c:1148]: (error) Common realloc mistake: 'cigar' nulled but not freed upon failure
[cram/cram_encode.c:552]: (error) Memory leak: buf
[cram/cram_io.c:2830]: (error) Invalid calloc() argument nr 1. The value is 0 but the valid values are '1:'.
[cram/cram_io.c:2439]: (error) Memory leak: seq
[cram/cram_io.c:3788]: (error) Memory leak: header
[cram/cram_io.c:3840]: (error) Memory leak: header
[cram/cram_io.c:4079]: (error) Memory leak: pads
[cram/mFILE.c:351]: (error) Resource leak: fp
[cram/pooled_alloc.c:68]: (error) Memory leak: p
[cram/pooled_alloc.c:202]: (error) Memory leak: items
[cram/rANS_static.c:902]: (error) Resource leak: infp
[cram/rANS_static.c:902]: (error) Resource leak: outfp
[cram/string_alloc.c:59]: (error) Memory leak: a_str
[header.c:643]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
[header.c:2406]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
[htslib/sam.h:639] -> [header.c:1645]: (warning) Function 'sam_hdr_remove_lines' argument order different: declaration 'h, type, id, rh' definition 'bh, type, id, h'
[header.c:531]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
[hfile_s3.c:922]: (error) Memory leak: queries
[hts.c:1435]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1452]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1457]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1465]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[hts.c:1473]: (error) Common realloc mistake: 's' nulled but not freed upon failure
[synced_bcf_reader.c:318]: (error) Uninitialized variable: n
[test/hfile.c:183]: (error) Memory leak: original
[test/hfile.c:183]: (error) Memory leak: text
[test/test_bgzf.c:381]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
[test/test_kstring.c:122]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
[thread_pool.c:644] -> [thread_pool.c:620]: (warning) Either the condition '!q' is redundant or there is possible null pointer dereference: q.
[thread_pool.c:644] -> [thread_pool.c:626]: (warning) Either the condition '!q' is redundant or there is possible null pointer dereference: q.
[thread_pool.c:644] -> [thread_pool.c:640]: (warning) Either the condition '!q' is redundant or there is possible null pointer dereference: q.
[thread_pool.c:63]: (error) va_list 'args' was opened but not closed by va_end().
[vcf.c:553]: (error) Memory pointed to by 'str' is freed twice.
```

**Comment by jmarshall** [comment]
What version of cppcheck are you using?

> [cram/cram_io.c:2830]: (error) Invalid calloc() argument nr 1. The value is 0 but the valid values are '1:'.

This code would require revising to work on a platform where `calloc(0, n)` returned NULL. That this hasn't been a problem to date means such platforms are not commonly used to run HTSlib.

> [header.c:643]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
> [header.c:2406]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.
> [header.c:531]: (warning) When using 'char' variables in bit operations, sign extension can generate unexpected results.

These and similar should be fixed at some point, but the problem is minor as valid input here is 7-bit ASCII (and other input will in any case give **consistent** results).

> [hfile_s3.c:922]: (error) Memory leak: queries

Indeed, there is a general lack of freeing on error paths in `order_query_string()`.

> [hts.c:1435]: (error) Common realloc mistake: 's' nulled but not freed upon failure
> [hts.c:1457]: (error) Common realloc mistake: 's' nulled but not freed upon failure
> [hts.c:1473]: (error) Common realloc mistake: 's' nulled but not freed upon failure

These reallocs always shrink the memory buffer, so the code is written with the assumption the call always succeeds. Could be improved, but the problem is minor.

> [hts.c:1452]: (error) Common realloc mistake: 's' nulled but not freed upon failure
> [hts.c:1465]: (error) Common realloc mistake: 's' nulled but not freed upon failure

These reallocs indeed have no error checking.

> [cram/pooled_alloc.c:202]: (error) Memory leak: items
> [cram/rANS_static.c:902]: (error) Resource leak: infp
> [cram/rANS_static.c:902]: (error) Resource leak: outfp
> [test/hfile.c:183]: (error) Memory leak: original
> [test/hfile.c:183]: (error) Memory leak: text
> [test/test_bgzf.c:381]: (warning) %d in format string (no. 1) requires 'int' but the argument type is 'unsigned int'.
> [test/test_kstring.c:122]: (warning) %u in format string (no. 1) requires 'unsigned int' but the argument type is 'signed int'.
> [thread_pool.c:63]: (error) va_list 'args' was opened but not closed by va_end().

These reports indeed reflect minor problems, but in test-only code within `#if 0` (_cram/*_, _thread_pool.c_) or that then immediately exits (_test/hfile.c_).

The remainder are false positives.

**Comment by jkbonfield** [comment]
I'll fix these, but they'll go in the next release as I'd rather have known ultra-trivial bugs involving not tidying up memory correctly once we've run out of memory (which invariably means we're about to shut down the application) than to run the risk of more serious bugs in my changes arriving late in the day.

**Comment by jkbonfield** [comment]
I also see things like:

```
[textutils.c:91]: (error) Shifting a negative value is undefined behaviour
[textutils.c:92]: (error) Shifting a negative value is undefined behaviour
[textutils.c:93]: (error) Shifting a negative value is undefined behaviour
```

I think technically this is an error in cppcheck - IIRC it's implementation defined behaviour rather than undefined behaviour, but frankly good luck finding a C implementation that doesn't conform to 2s complement arithmetic and changes like https://github.com/samtools/htslib/blob/develop/cram/cram_io.c#L481 just to silence over-zealous warnings are a step too far IMO and should be silenced in other ways.

There may still be issues in `hts_decode_base64` though, but frankly it's a case of garbage in, garbage out if you want to trigger the implementation defined behaviour.

**Comment by jmarshall** [comment]
Even after [N2412](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2412.pdf) lands, shifting negative values will remain undefined (`<<`) or implementation-defined (`>>`) in C as (at least historically) different processors shift the sign bit differently.

The cppcheck problem in _textutils.c_ is that it hasn't done enough value range propagation to realise that all the values being shifted are guaranteed to be non-negative. (Lack of value propagation and/or flow analysis is the cause of a lot of its other false alarms too.)

**Comment by jkbonfield** [comment]
I assume N2412 will fix the undefined behaviour of type conversion from signed to unsigned as it explicitly defines the bit-encoding of signed values, hence the code I linked above would be redundant (it was simply an assignment before).

Agreed looking at textutils.c again I see it bubbles through a whole series of -1s ending up in a break statement, which avoids the shift.   However there are things that cppcheck finds which are genuine and nothing else has warned us about them.  So I am inclined to silence it, perhaps with a comment (which can aid the reader too in some circumstances).  The alternative is an external cpp check config file, but it has to either be whole file exclusions or a tedious requirement to renumber lines every time we change something (not a hope!).
